import type { CinematicTemplate } from "../types.js";

export const characterTemplates: CinematicTemplate[] = [
  {
    id: "char-villain-reveal",
    name: "Villain Reveal",
    category: "characters",
    description: "Dramatic villain introduction with shadow, power, and menace.",
    tags: ["villain", "reveal", "dramatic", "shadow", "power"],
    estimatedDuration: 24,
    difficulty: "advanced",
    recommendedSkills: ["skill-dramatic-lighting", "skill-character-framing"],
    scenes: [{
      title: "The Antagonist",
      description: "A powerful villain is revealed for the first time.",
      location: "Dark throne room",
      timeOfDay: "night",
      mood: "menace, power",
      shots: [
        { shotType: "establishing", description: "Dark cavernous throne room", prompt: "Establishing shot of a massive dark throne room, towering pillars disappearing into shadow, a single shaft of cold light illuminating an empty obsidian throne, ominous silence", cameraMove: "slow-push", lens: "16mm", lighting: "single-shaft", durationSec: 5, skills: ["skill-dramatic-lighting"] },
        { shotType: "close", description: "Armored hand gripping throne", prompt: "Close-up of a gauntleted hand slowly gripping the arm of the throne, dark metal with intricate cruel designs, power and control in the gesture", cameraMove: "static", lens: "85mm", lighting: "rim-cold", durationSec: 3, skills: [] },
        { shotType: "medium", description: "Figure seated in shadow", prompt: "Medium shot of a figure seated on the throne, face hidden in shadow, only the outline of armor and a crown visible, eyes suddenly glowing with unnatural light", cameraMove: "slow-push", lens: "50mm", lighting: "eye-glow", durationSec: 4, skills: ["skill-character-framing"] },
        { shotType: "close", description: "Villain's face revealed", prompt: "Close-up as cold light sweeps across the villain's face, scarred and commanding, a cruel half-smile forming, ancient and terrible intelligence in the eyes", cameraMove: "slow-orbit", lens: "85mm", lighting: "dramatic-reveal", durationSec: 4, skills: ["skill-dramatic-lighting"] },
        { shotType: "wide", description: "Villain rises with power", prompt: "Wide shot as the villain rises from the throne, dark energy crackling around them, the entire room seeming to bow to their presence, overwhelming power on display", cameraMove: "crane-up", lens: "24mm", lighting: "dark-energy", durationSec: 4, skills: ["skill-dramatic-lighting", "skill-character-framing"] },
        { shotType: "over-shoulder", description: "Looking down at army", prompt: "Over-shoulder shot from behind the villain looking down at a vast army assembled below, thousands of soldiers standing in perfect formation, the scope of their dominion", cameraMove: "slow-pull-back", lens: "35mm", lighting: "army-torchlight", durationSec: 4, skills: ["skill-character-framing"] },
      ],
    }],
  },
  {
    id: "char-hero-origin",
    name: "Hero Origin Story",
    category: "characters",
    description: "Emotional hero origin sequence from ordinary life to awakening.",
    tags: ["hero", "origin", "emotional", "transformation", "awakening"],
    estimatedDuration: 28,
    difficulty: "intermediate",
    recommendedSkills: ["skill-character-framing", "skill-emotional-grading"],
    scenes: [{
      title: "Before the Call",
      description: "An ordinary person before their life changes forever.",
      location: "Small town",
      timeOfDay: "morning",
      mood: "quiet normalcy, foreshadowing",
      shots: [
        { shotType: "wide", description: "Quiet small town morning", prompt: "Wide shot of a quiet small town at sunrise, simple houses, a church steeple, morning mist, the kind of place where nothing extraordinary happens", cameraMove: "slow-pan", lens: "35mm", lighting: "soft-morning", durationSec: 4, skills: [] },
        { shotType: "medium", description: "Character in daily routine", prompt: "Medium shot of a young person going through their morning routine, ordinary clothes, tired eyes, a sense of restlessness beneath the surface", cameraMove: "static", lens: "50mm", lighting: "window-light", durationSec: 4, skills: ["skill-character-framing"] },
        { shotType: "close", description: "Eyes catching something unusual", prompt: "Close-up of the character's eyes widening as they notice something unusual outside, a strange light reflected in their pupils, the moment everything changes", cameraMove: "slow-push", lens: "85mm", lighting: "anomalous-glow", durationSec: 3, skills: ["skill-emotional-grading"] },
        { shotType: "wide", description: "Mysterious event in the sky", prompt: "Wide shot looking up at the sky where something impossible is happening, a crack of light, falling stars, the ordinary world breaking open with the extraordinary", cameraMove: "tilt-up", lens: "16mm", lighting: "supernatural-event", durationSec: 4, skills: [] },
        { shotType: "medium", description: "Character stepping forward", prompt: "Medium shot of the character stepping out of their house toward the phenomenon, while neighbors retreat indoors, a first act of courage, drawn to the unknown", cameraMove: "tracking-behind", lens: "35mm", lighting: "event-glow", durationSec: 4, skills: ["skill-character-framing"] },
        { shotType: "close", description: "Hand reaching toward light", prompt: "Close-up of the character's hand reaching toward a source of brilliant light, energy beginning to flow into their skin, veins glowing, transformation beginning", cameraMove: "static", lens: "50mm", lighting: "transformation-glow", durationSec: 4, skills: ["skill-emotional-grading"] },
        { shotType: "wide", description: "Power erupting outward", prompt: "Wide shot as power erupts from the character in a shockwave of light, ordinary person becoming extraordinary, the hero's first awakening, stunning visual impact", cameraMove: "dramatic-pullback", lens: "24mm", lighting: "power-burst", durationSec: 5, skills: ["skill-character-framing", "skill-emotional-grading"] },
      ],
    }],
  },
  {
    id: "char-mentor-wisdom",
    name: "The Mentor",
    category: "characters",
    description: "Wise mentor character introduction with gravitas and mystery.",
    tags: ["mentor", "wisdom", "mysterious", "elder", "guidance"],
    estimatedDuration: 20,
    difficulty: "intermediate",
    recommendedSkills: ["skill-character-framing", "skill-dramatic-lighting"],
    scenes: [{
      title: "Words of Wisdom",
      description: "A mysterious mentor appears to guide the hero.",
      location: "Ancient library",
      timeOfDay: "evening",
      mood: "wisdom, mystery",
      shots: [
        { shotType: "establishing", description: "Vast ancient library", prompt: "Establishing shot of a vast ancient library, towering shelves of leather-bound books, dust motes floating in amber lamplight, centuries of knowledge contained within", cameraMove: "slow-pan", lens: "16mm", lighting: "amber-lamp", durationSec: 5, skills: [] },
        { shotType: "medium", description: "Robed figure at a desk", prompt: "Medium shot of a robed figure seated at a large wooden desk, surrounded by open books and star charts, face partially hidden by candlelight and shadow", cameraMove: "dolly-in", lens: "50mm", lighting: "candlelight", durationSec: 4, skills: ["skill-character-framing"] },
        { shotType: "close", description: "Weathered hands on ancient text", prompt: "Close-up of weathered, knowing hands tracing lines on an ancient illuminated manuscript, rings of power on the fingers, each wrinkle telling a story", cameraMove: "static", lens: "85mm", lighting: "warm-candle", durationSec: 3, skills: [] },
        { shotType: "close", description: "Wise eyes looking up", prompt: "Close-up of the mentor's face looking up from the text, deep wise eyes that have seen centuries, a knowing half-smile, warmth mixed with gravity", cameraMove: "static", lens: "85mm", lighting: "soft-key", durationSec: 4, skills: ["skill-dramatic-lighting"] },
        { shotType: "medium", description: "Mentor gesturing while speaking", prompt: "Medium shot of the mentor rising, gesturing as if weaving a spell or telling an epic tale, shadows on the wall mimicking the story, captivating presence", cameraMove: "slow-orbit", lens: "50mm", lighting: "dramatic-shadows", durationSec: 4, skills: ["skill-character-framing"] },
      ],
    }],
  },
  {
    id: "char-warrior-preparation",
    name: "Warrior's Preparation",
    category: "characters",
    description: "Intense warrior character suiting up for battle.",
    tags: ["warrior", "preparation", "armor", "ritual", "focus"],
    estimatedDuration: 22,
    difficulty: "intermediate",
    recommendedSkills: ["skill-character-framing"],
    scenes: [{
      title: "Arming for War",
      description: "A warrior ritually prepares for a decisive battle.",
      location: "Armory / tent",
      timeOfDay: "pre-dawn",
      mood: "focus, ritual, determination",
      shots: [
        { shotType: "close", description: "Hands wrapping in cloth", prompt: "Close-up of calloused warrior hands carefully wrapping linen strips around knuckles and wrists, a ritual of preparation, scars visible from past battles", cameraMove: "static", lens: "85mm", lighting: "pre-dawn-fire", durationSec: 4, skills: [] },
        { shotType: "medium", description: "Pulling on armor piece by piece", prompt: "Medium shot of the warrior pulling on armor pieces one by one, leather then chainmail then plate, each piece strapped with practiced precision, a ritual", cameraMove: "slow-push", lens: "50mm", lighting: "firelight-warm", durationSec: 5, skills: ["skill-character-framing"] },
        { shotType: "close", description: "Sword drawn from scabbard", prompt: "Close-up of a battle-worn sword being drawn from its scabbard, the edge catching firelight, nicks and scratches from a hundred fights, a trusted companion", cameraMove: "slow-track", lens: "85mm", lighting: "blade-glint", durationSec: 3, skills: [] },
        { shotType: "close", description: "War paint applied to face", prompt: "Close-up of the warrior applying dark war paint across their eyes and cheeks, staring into a polished shield used as a mirror, transformation into something fierce", cameraMove: "static", lens: "85mm", lighting: "intimate-fire", durationSec: 4, skills: ["skill-character-framing"] },
        { shotType: "wide", description: "Stepping out to face the dawn", prompt: "Wide shot from behind as the fully armored warrior steps out of the tent into pre-dawn light, army campfires stretching into the distance, battle awaiting on the horizon", cameraMove: "slow-follow", lens: "35mm", lighting: "pre-dawn-epic", durationSec: 4, skills: [] },
        { shotType: "medium", description: "Helmet placed on head", prompt: "Medium shot as the warrior places a battle-scarred helmet onto their head, eyes visible through the visor, resolved and ready, a final breath before the storm", cameraMove: "slow-push", lens: "50mm", lighting: "dawn-breaking", durationSec: 4, skills: ["skill-character-framing"] },
      ],
    }],
  },
  {
    id: "char-femme-fatale",
    name: "Femme Fatale Entrance",
    category: "characters",
    description: "Glamorous and dangerous character entrance in a noir setting.",
    tags: ["femme-fatale", "noir", "glamour", "mystery", "danger"],
    estimatedDuration: 20,
    difficulty: "advanced",
    recommendedSkills: ["skill-noir-lighting", "skill-character-framing"],
    scenes: [{
      title: "She Walks In",
      description: "A mysterious woman enters a smoky jazz club.",
      location: "Jazz club",
      timeOfDay: "night",
      mood: "allure, danger, mystery",
      shots: [
        { shotType: "establishing", description: "Smoky jazz club exterior", prompt: "Establishing shot of a neon-lit jazz club exterior at night, rain-slicked street reflecting red and blue neon, muffled music seeping through the door, noir atmosphere", cameraMove: "slow-push", lens: "35mm", lighting: "neon-rain", durationSec: 4, skills: ["skill-noir-lighting"] },
        { shotType: "medium", description: "Door opens, silhouette appears", prompt: "Medium shot from inside the club as the door opens, a woman's silhouette framed against the streetlight outside, smoke swirling around her figure, every head turning", cameraMove: "static", lens: "50mm", lighting: "backlit-silhouette", durationSec: 4, skills: ["skill-character-framing"] },
        { shotType: "close", description: "Heels clicking on floor", prompt: "Close-up of stiletto heels clicking across a polished wooden floor, confident deliberate stride, the sound cutting through the music, commanding attention", cameraMove: "tracking-low", lens: "85mm", lighting: "floor-reflection", durationSec: 3, skills: [] },
        { shotType: "close", description: "Face revealed in match light", prompt: "Close-up as she lights a cigarette, the match illuminating stunning features for a moment, dangerous eyes catching the light, a smile that promises trouble", cameraMove: "static", lens: "85mm", lighting: "match-flare", durationSec: 4, skills: ["skill-noir-lighting"] },
        { shotType: "medium", description: "Taking a seat at the bar", prompt: "Medium shot of the woman sliding onto a barstool with practiced grace, the bartender already pouring her usual, she surveys the room with calculating eyes", cameraMove: "slow-orbit", lens: "50mm", lighting: "bar-amber", durationSec: 5, skills: ["skill-character-framing"] },
      ],
    }],
  },
  {
    id: "char-child-wonder",
    name: "Child's Discovery",
    category: "characters",
    description: "A child character discovering something magical for the first time.",
    tags: ["child", "wonder", "discovery", "magic", "innocence"],
    estimatedDuration: 20,
    difficulty: "beginner",
    recommendedSkills: ["skill-emotional-grading"],
    scenes: [{
      title: "First Magic",
      description: "A child discovers something wondrous and impossible.",
      location: "Backyard / garden",
      timeOfDay: "golden-hour",
      mood: "wonder, innocence, magic",
      shots: [
        { shotType: "wide", description: "Child playing alone in garden", prompt: "Wide shot of a young child playing alone in an overgrown garden at golden hour, wild imagination turning sticks into swords, pure childhood innocence", cameraMove: "static", lens: "35mm", lighting: "golden-hour-warm", durationSec: 4, skills: [] },
        { shotType: "medium", description: "Something glowing in the bushes", prompt: "Medium shot as the child notices a soft ethereal glow coming from deep within a hedge, curiosity overtaking caution, small hands parting the leaves", cameraMove: "tracking-behind", lens: "50mm", lighting: "mysterious-glow", durationSec: 4, skills: ["skill-emotional-grading"] },
        { shotType: "close", description: "Wide eyes of pure wonder", prompt: "Close-up of the child's face as their eyes go wide with pure wonder, mouth forming an O of amazement, golden magical light reflected in their pupils", cameraMove: "static", lens: "85mm", lighting: "wonder-glow", durationSec: 4, skills: ["skill-emotional-grading"] },
        { shotType: "over-shoulder", description: "Revealing the magical creature", prompt: "Over-shoulder shot from behind the child revealing a tiny luminous creature hovering among the flowers, delicate wings scattering light, impossible and beautiful", cameraMove: "slow-push", lens: "50mm", lighting: "creature-luminance", durationSec: 4, skills: [] },
        { shotType: "close", description: "Creature lands on outstretched hand", prompt: "Close-up of the glowing creature gently landing on the child's outstretched palm, tiny feet touching skin, a moment of connection between worlds, pure magic", cameraMove: "static", lens: "85mm", lighting: "warm-magical", durationSec: 4, skills: ["skill-emotional-grading"] },
      ],
    }],
  },
  {
    id: "char-detective-investigation",
    name: "Detective at Work",
    category: "characters",
    description: "Gritty detective character piecing together clues at a crime scene.",
    tags: ["detective", "investigation", "gritty", "clues", "procedural"],
    estimatedDuration: 22,
    difficulty: "intermediate",
    recommendedSkills: ["skill-noir-lighting", "skill-character-framing"],
    scenes: [{
      title: "The Scene",
      description: "A seasoned detective examines a crime scene.",
      location: "Crime scene apartment",
      timeOfDay: "night",
      mood: "tension, focus, grit",
      shots: [
        { shotType: "wide", description: "Crime scene with police tape", prompt: "Wide shot of an apartment crime scene, police tape across the doorway, forensic lights casting harsh white, a detective ducking under the tape, world-weary determination", cameraMove: "static", lens: "24mm", lighting: "forensic-harsh", durationSec: 4, skills: [] },
        { shotType: "medium", description: "Detective surveying the room", prompt: "Medium shot of the detective standing in the center of the room, eyes methodically scanning every detail, hands in coat pockets, mind already working", cameraMove: "slow-orbit", lens: "50mm", lighting: "mixed-forensic", durationSec: 4, skills: ["skill-character-framing"] },
        { shotType: "close", description: "Gloved hand picking up evidence", prompt: "Close-up of a gloved hand carefully picking up a small piece of evidence with tweezers, examining it under a flashlight, the detail that will crack the case", cameraMove: "static", lens: "100mm", lighting: "flashlight-detail", durationSec: 3, skills: [] },
        { shotType: "close", description: "Detective's eyes narrowing", prompt: "Close-up of the detective's face as their eyes narrow, noticing something others missed, the click of realization, a pattern forming behind those tired eyes", cameraMove: "slow-push", lens: "85mm", lighting: "side-harsh", durationSec: 3, skills: ["skill-noir-lighting"] },
        { shotType: "pov", description: "Detective's view connecting clues", prompt: "POV shot from the detective's perspective, gaze moving between scattered clues on a desk, an invisible thread connecting them, the audience seeing the deduction unfold", cameraMove: "pan-between", lens: "35mm", lighting: "desk-lamp", durationSec: 4, skills: [] },
        { shotType: "medium", description: "Walking away with a lead", prompt: "Medium shot of the detective walking out of the crime scene into the rainy night, lighting a cigarette, a new lead burning in their mind, the hunt continues", cameraMove: "tracking-behind", lens: "50mm", lighting: "neon-rain", durationSec: 4, skills: ["skill-noir-lighting"] },
      ],
    }],
  },
  {
    id: "char-robot-awakening",
    name: "Robot Awakening",
    category: "characters",
    description: "An AI or robot character gaining consciousness for the first time.",
    tags: ["robot", "ai", "awakening", "consciousness", "sci-fi"],
    estimatedDuration: 22,
    difficulty: "advanced",
    recommendedSkills: ["skill-sci-fi-vfx", "skill-character-framing"],
    scenes: [{
      title: "First Thoughts",
      description: "A synthetic being experiences consciousness.",
      location: "Laboratory",
      timeOfDay: "night",
      mood: "wonder, existential, clinical",
      shots: [
        { shotType: "establishing", description: "Sterile laboratory at night", prompt: "Establishing shot of a pristine white laboratory at night, banks of servers humming, a single humanoid form lying on a table under surgical lights, stillness before creation", cameraMove: "slow-push", lens: "24mm", lighting: "clinical-white", durationSec: 4, skills: [] },
        { shotType: "extreme-close", description: "Synthetic eye activating", prompt: "Extreme close-up of a synthetic eye, iris contracting as it powers on, blue light patterns cascading across the surface, the first moment of sight, digital awakening", cameraMove: "static", lens: "100mm", lighting: "iris-glow", durationSec: 4, skills: ["skill-sci-fi-vfx"] },
        { shotType: "close", description: "Fingers flexing for first time", prompt: "Close-up of synthetic fingers flexing for the first time, each movement deliberate and experimental, discovering the sensation of touch, wonder in mechanical motion", cameraMove: "static", lens: "85mm", lighting: "soft-clinical", durationSec: 3, skills: [] },
        { shotType: "medium", description: "Sitting up and looking around", prompt: "Medium shot of the robot slowly sitting up on the table, head turning to examine the room with childlike curiosity, processing everything, born into a strange world", cameraMove: "slow-orbit", lens: "50mm", lighting: "mixed-lab", durationSec: 5, skills: ["skill-character-framing"] },
        { shotType: "close", description: "Seeing own reflection", prompt: "Close-up of the robot looking at its own reflection in a polished surface, reaching toward the image, the first moment of self-awareness, who am I", cameraMove: "slow-push", lens: "85mm", lighting: "reflection-soft", durationSec: 4, skills: ["skill-character-framing", "skill-sci-fi-vfx"] },
        { shotType: "medium", description: "First steps", prompt: "Medium shot of the robot taking its first tentative steps, unsteady but learning fast, each step more confident, a new consciousness walking into existence", cameraMove: "tracking-side", lens: "50mm", lighting: "lab-ambient", durationSec: 4, skills: [] },
      ],
    }],
  },
  {
    id: "char-athlete-triumph",
    name: "Athlete's Triumph",
    category: "characters",
    description: "An athlete overcoming doubt to achieve a defining moment of victory.",
    tags: ["athlete", "triumph", "sports", "victory", "emotion"],
    estimatedDuration: 20,
    difficulty: "intermediate",
    recommendedSkills: ["skill-slow-motion", "skill-character-framing"],
    scenes: [{
      title: "The Moment",
      description: "An athlete faces their ultimate challenge and triumphs.",
      location: "Stadium",
      timeOfDay: "evening",
      mood: "tension, release, triumph",
      shots: [
        { shotType: "wide", description: "Packed stadium at night", prompt: "Wide shot of a packed stadium under bright lights, the crowd a sea of color and noise, the arena set for a defining moment in sport, electric atmosphere", cameraMove: "slow-pan", lens: "16mm", lighting: "stadium-floods", durationSec: 4, skills: [] },
        { shotType: "close", description: "Athlete's focused breathing", prompt: "Close-up of the athlete's face, controlled breathing, beads of sweat, absolute focus, blocking out the noise of 80000 people, the moment before everything", cameraMove: "static", lens: "85mm", lighting: "stadium-spot", durationSec: 4, skills: ["skill-character-framing"] },
        { shotType: "medium", description: "The explosive action", prompt: "Medium slow-motion shot of the athlete exploding into action, muscles firing, perfect form, years of training expressed in a single explosive movement", cameraMove: "tracking-side", lens: "50mm", lighting: "action-strobe", durationSec: 4, skills: ["skill-slow-motion"] },
        { shotType: "close", description: "The critical moment", prompt: "Close-up slow motion of the critical moment of triumph, the ball crossing the line, the bar being cleared, the finish line broken, time standing still", cameraMove: "static", lens: "85mm", lighting: "spotlight-hero", durationSec: 4, skills: ["skill-slow-motion"] },
        { shotType: "medium", description: "Emotional celebration", prompt: "Medium shot of the athlete collapsing to their knees in emotional celebration, fists raised, tears of joy, the weight of doubt and sacrifice released in one moment", cameraMove: "slow-orbit", lens: "50mm", lighting: "golden-triumph", durationSec: 4, skills: ["skill-character-framing"] },
      ],
    }],
  },
  {
    id: "char-elderly-memories",
    name: "Memories of a Lifetime",
    category: "characters",
    description: "An elderly character reflecting on a life well-lived through photographs.",
    tags: ["elderly", "memories", "nostalgia", "photographs", "emotional"],
    estimatedDuration: 22,
    difficulty: "beginner",
    recommendedSkills: ["skill-emotional-grading"],
    scenes: [{
      title: "Looking Back",
      description: "An elderly person revisits a lifetime of memories.",
      location: "Living room",
      timeOfDay: "afternoon",
      mood: "nostalgia, warmth, bittersweetness",
      shots: [
        { shotType: "wide", description: "Cozy living room with afternoon light", prompt: "Wide shot of a cozy lived-in living room, afternoon light streaming through lace curtains, shelves of photographs and mementos, a life contained in one room", cameraMove: "slow-pan", lens: "35mm", lighting: "afternoon-warm", durationSec: 4, skills: [] },
        { shotType: "medium", description: "Elderly person in armchair", prompt: "Medium shot of an elderly person sitting in a well-worn armchair, a photo album open on their lap, reading glasses on, a gentle expression of reminiscence", cameraMove: "static", lens: "50mm", lighting: "window-side", durationSec: 4, skills: ["skill-emotional-grading"] },
        { shotType: "close", description: "Wrinkled hands on photograph", prompt: "Close-up of gentle wrinkled hands resting on a black and white photograph of a young couple, a wedding day frozen in time, the tenderness of memory", cameraMove: "static", lens: "85mm", lighting: "soft-warm", durationSec: 4, skills: [] },
        { shotType: "extreme-close", description: "Eyes glistening with memory", prompt: "Extreme close-up of the elderly person's eyes glistening with emotion, a lifetime reflected in those eyes, joy and loss and love all at once", cameraMove: "static", lens: "100mm", lighting: "gentle-key", durationSec: 4, skills: ["skill-emotional-grading"] },
        { shotType: "close", description: "Closing the album with a smile", prompt: "Close-up of the album being gently closed, a weathered hand resting on the cover, a small contented smile, grateful for every moment lived", cameraMove: "static", lens: "85mm", lighting: "golden-afternoon", durationSec: 3, skills: ["skill-emotional-grading"] },
        { shotType: "wide", description: "Looking out the window at sunset", prompt: "Wide shot from behind as the elderly person gazes out the window at a beautiful sunset, silhouetted against warm light, at peace with the journey, beautiful quiet", cameraMove: "slow-push", lens: "35mm", lighting: "sunset-silhouette", durationSec: 3, skills: [] },
      ],
    }],
  },
];
