import type { CinematicTemplate } from "../types.js";

export const characterExtendedTemplates: CinematicTemplate[] = [
  {
    id: "char-pirate-captain",
    name: "Pirate Captain",
    category: "characters",
    description: "Charismatic pirate captain commanding their crew before battle.",
    tags: ["pirate", "captain", "sea", "charisma", "adventure"],
    estimatedDuration: 20,
    difficulty: "intermediate",
    recommendedSkills: ["skill-character-framing"],
    scenes: [{ title: "All Hands", description: "A pirate captain rallies the crew.", location: "Pirate ship deck", timeOfDay: "dusk", mood: "adventure, command", shots: [
      { shotType: "establishing", description: "Pirate ship at golden dusk", prompt: "Establishing shot of a weathered pirate ship at golden dusk, sails billowing, the jolly roger flying, waves crashing against the hull, the romance of the sea", cameraMove: "slow-orbit", lens: "24mm", lighting: "dusk-maritime", durationSec: 5, skills: [] },
      { shotType: "medium", description: "Captain at the helm", prompt: "Medium shot of the pirate captain at the helm, hands gripping the wheel, long coat flowing, a scarred face with knowing eyes scanning the horizon", cameraMove: "slow-push", lens: "50mm", lighting: "sunset-backlit", durationSec: 4, skills: ["skill-character-framing"] },
      { shotType: "wide", description: "Rallying the crew", prompt: "Wide shot from below as the captain stands on the quarterdeck rallying the crew below, arms spread wide, voice carrying over the wind, born to command", cameraMove: "low-angle", lens: "24mm", lighting: "dusk-dramatic", durationSec: 4, skills: [] },
      { shotType: "close", description: "Drawing a cutlass", prompt: "Close-up of the captain drawing a gleaming cutlass, the blade catching the last rays of sun, a grin of anticipation, adventure and danger ahead", cameraMove: "static", lens: "85mm", lighting: "blade-sunset", durationSec: 3, skills: [] },
      { shotType: "wide", description: "Ship sailing toward the horizon", prompt: "Wide shot of the ship sailing toward a dramatic sunset, crew cheering, cannon ports opening, heading toward fortune or doom, the pirate's life", cameraMove: "slow-pull-back", lens: "35mm", lighting: "sunset-epic", durationSec: 4, skills: ["skill-character-framing"] },
    ]}],
  },
  {
    id: "char-mad-scientist",
    name: "Mad Scientist's Lab",
    category: "characters",
    description: "Eccentric scientist character in a chaotic laboratory breakthrough.",
    tags: ["scientist", "mad", "laboratory", "experiment", "breakthrough"],
    estimatedDuration: 20,
    difficulty: "intermediate",
    recommendedSkills: ["skill-dramatic-lighting"],
    scenes: [{ title: "Eureka", description: "A brilliant but unhinged scientist achieves a breakthrough.", location: "Chaotic laboratory", timeOfDay: "night", mood: "manic energy, genius", shots: [
      { shotType: "establishing", description: "Chaotic laboratory overview", prompt: "Establishing shot of a chaotic laboratory, every surface covered with bubbling experiments, electrical arcs between equipment, scrawled equations on every wall", cameraMove: "slow-pan", lens: "16mm", lighting: "electrical-arcs", durationSec: 5, skills: ["skill-dramatic-lighting"] },
      { shotType: "close", description: "Wild eyes behind goggles", prompt: "Close-up of wild brilliant eyes behind steamed-up safety goggles, pupils dilated with excitement, hair standing on end from static electricity, genius unbound", cameraMove: "static", lens: "85mm", lighting: "experiment-glow", durationSec: 3, skills: [] },
      { shotType: "medium", description: "Frantically mixing chemicals", prompt: "Medium shot of the scientist frantically mixing chemicals, pouring from multiple beakers simultaneously, muttering calculations, controlled chaos in motion", cameraMove: "handheld-energy", lens: "35mm", lighting: "chemical-glow", durationSec: 4, skills: [] },
      { shotType: "close", description: "Experiment begins to glow", prompt: "Close-up of the central experiment beginning to glow with an unearthly light, the scientist's face illuminated, the expression shifting from manic to awe", cameraMove: "slow-push", lens: "85mm", lighting: "breakthrough-glow", durationSec: 4, skills: ["skill-dramatic-lighting"] },
      { shotType: "wide", description: "Triumphant arms raised", prompt: "Wide shot of the scientist throwing arms up in triumph, the experiment erupting with light behind them, papers blowing everywhere, the moment of creation", cameraMove: "dramatic-pullback", lens: "24mm", lighting: "explosion-bright", durationSec: 4, skills: [] },
    ]}],
  },
  {
    id: "char-queen-coronation",
    name: "Royal Coronation",
    category: "characters",
    description: "Majestic coronation ceremony of a new queen or king.",
    tags: ["royal", "coronation", "queen", "ceremony", "crown"],
    estimatedDuration: 24,
    difficulty: "advanced",
    recommendedSkills: ["skill-cinematic-lighting", "skill-character-framing"],
    scenes: [{ title: "Crown and Throne", description: "A new monarch is crowned before the realm.", location: "Grand cathedral", timeOfDay: "morning", mood: "majesty, weight of duty", shots: [
      { shotType: "establishing", description: "Grand cathedral interior", prompt: "Establishing shot of a vast cathedral interior, soaring gothic arches, stained glass casting colored light, thousands of nobles filling every pew, a throne at the far end", cameraMove: "crane-forward", lens: "16mm", lighting: "stained-glass", durationSec: 5, skills: ["skill-cinematic-lighting"] },
      { shotType: "wide", description: "Procession up the aisle", prompt: "Wide shot of the new monarch walking slowly up the long aisle, regal robes trailing, every eye upon them, the weight of a kingdom in each step", cameraMove: "tracking-side", lens: "35mm", lighting: "cathedral-shafts", durationSec: 5, skills: [] },
      { shotType: "close", description: "Crown being lifted", prompt: "Close-up of ancient jeweled crown being lifted by the archbishop, precious gems catching stained glass light, centuries of history in gold and stone", cameraMove: "slow-push", lens: "85mm", lighting: "crown-sparkle", durationSec: 4, skills: [] },
      { shotType: "close", description: "Crown placed on head", prompt: "Close-up of the crown being placed upon the new monarch's head, their eyes closing briefly under the weight, then opening with resolve, born to rule", cameraMove: "static", lens: "85mm", lighting: "ceremony-warm", durationSec: 4, skills: ["skill-character-framing"] },
      { shotType: "wide", description: "Crowd bowing and cheering", prompt: "Wide shot as the entire cathedral erupts in cheers, thousands bowing, sunlight streaming through every window at once, the new ruler rising from the throne", cameraMove: "crane-up", lens: "16mm", lighting: "triumphant-golden", durationSec: 4, skills: ["skill-cinematic-lighting", "skill-character-framing"] },
    ]}],
  },
  {
    id: "char-street-artist",
    name: "Street Artist at Work",
    category: "characters",
    description: "A passionate street artist creating a massive mural.",
    tags: ["artist", "street-art", "mural", "creative", "urban"],
    estimatedDuration: 18,
    difficulty: "beginner",
    recommendedSkills: [],
    scenes: [{ title: "The Wall", description: "An artist transforms a blank wall into a masterpiece.", location: "Urban alley", timeOfDay: "day", mood: "creativity, passion, urban", shots: [
      { shotType: "wide", description: "Blank wall in urban setting", prompt: "Wide shot of a large blank concrete wall in an urban alley, spray cans laid out on the ground, the artist standing back visualizing the masterpiece to come", cameraMove: "static", lens: "24mm", lighting: "overcast-urban", durationSec: 4, skills: [] },
      { shotType: "close", description: "Spray can shaking and first line", prompt: "Close-up of a paint-stained hand shaking a spray can, the first confident line laid down on the wall, the hiss of paint, creation beginning", cameraMove: "tracking-hand", lens: "85mm", lighting: "natural-side", durationSec: 3, skills: [] },
      { shotType: "medium", description: "Artist working at scale", prompt: "Medium shot of the artist on a ladder working on the massive piece, arm sweeping in bold strokes, total absorption in the creative process, paint on every surface", cameraMove: "timelapse", lens: "35mm", lighting: "changing-day", durationSec: 4, skills: [] },
      { shotType: "close", description: "Detail work on faces", prompt: "Close-up of intricate detail work, fine lines forming a face within the mural, the precision contrasting with the scale, skill and vision merging", cameraMove: "slow-pan", lens: "85mm", lighting: "natural-detail", durationSec: 4, skills: [] },
      { shotType: "wide", description: "Stepping back at the finished mural", prompt: "Wide shot of the artist stepping back to view the completed mural, massive and vibrant, passersby stopping to stare, a wall transformed into a statement", cameraMove: "slow-pull-back", lens: "24mm", lighting: "golden-hour-urban", durationSec: 3, skills: [] },
    ]}],
  },
  {
    id: "char-astronaut-first-step",
    name: "Astronaut's First Step",
    category: "characters",
    description: "An astronaut taking their first steps on an alien world.",
    tags: ["astronaut", "space", "first-step", "exploration", "alien"],
    estimatedDuration: 24,
    difficulty: "advanced",
    recommendedSkills: ["skill-sci-fi-vfx", "skill-epic-scale"],
    scenes: [{ title: "New World", description: "Humanity's first steps on an alien planet.", location: "Alien planet surface", timeOfDay: "alien-dawn", mood: "awe, isolation, history", shots: [
      { shotType: "establishing", description: "Alien landscape from orbit", prompt: "Establishing shot of an alien planet from orbit, strange continents, purple oceans, two moons visible, a lander descending toward the surface trailing fire", cameraMove: "slow-push", lens: "16mm", lighting: "orbital-light", durationSec: 5, skills: ["skill-sci-fi-vfx", "skill-epic-scale"] },
      { shotType: "medium", description: "Astronaut in the hatch", prompt: "Medium shot of an astronaut standing in the lander's open hatch, looking out at an impossible alien landscape, the visor reflecting an alien sky", cameraMove: "over-shoulder", lens: "35mm", lighting: "alien-atmosphere", durationSec: 4, skills: [] },
      { shotType: "close", description: "Boot hovering above alien soil", prompt: "Close-up of a space boot hovering just above alien soil, the moment of hesitation before making history, strange textures and colors in the ground below", cameraMove: "static", lens: "85mm", lighting: "alien-surface", durationSec: 4, skills: [] },
      { shotType: "close", description: "Boot imprint in alien ground", prompt: "Close-up of the boot making contact and leaving the first human footprint in alien soil, a mark that will last millennia, the weight of the moment", cameraMove: "static", lens: "85mm", lighting: "ground-detail", durationSec: 4, skills: ["skill-sci-fi-vfx"] },
      { shotType: "wide", description: "Alone on an alien world", prompt: "Wide shot of the lone astronaut standing on the alien surface, impossibly beautiful and alien landscape stretching in every direction, twin suns on the horizon, tiny human against cosmic scale", cameraMove: "slow-pull-back", lens: "16mm", lighting: "twin-sun-dawn", durationSec: 5, skills: ["skill-epic-scale"] },
    ]}],
  },
];
