import type { CinematicTemplate } from "../types.js";

export const commercialTemplates: CinematicTemplate[] = [
  {
    id: "comm-luxury-car",
    name: "Luxury Car Reveal",
    category: "commercial",
    description: "Premium automotive commercial with dramatic car reveal and driving shots.",
    tags: ["automotive", "luxury", "reveal", "premium", "driving"],
    estimatedDuration: 30,
    difficulty: "advanced",
    recommendedSkills: ["skill-automotive-lighting", "skill-slow-motion"],
    scenes: [
      {
        title: "The Reveal",
        description: "A luxury car is revealed in dramatic fashion.",
        location: "Studio / Highway",
        timeOfDay: "night",
        mood: "prestige, power",
        shots: [
          { shotType: "establishing", description: "Dark studio with single spotlight", prompt: "Dark studio environment, single spotlight creating a pool of light on polished black floor, the outline of a premium car barely visible in shadow", cameraMove: "slow-dolly-forward", lens: "35mm", lighting: "single-spot", durationSec: 5, skills: ["skill-automotive-lighting"] },
          { shotType: "close", description: "Light sweeping across car body", prompt: "Close-up of light sweeping across the polished curves of a luxury car body, reflections dancing on the metallic paint, every panel line perfect", cameraMove: "tracking-side", lens: "85mm", lighting: "sweeping-light", durationSec: 4, skills: ["skill-automotive-lighting"] },
          { shotType: "extreme-close", description: "Chrome badge detail", prompt: "Extreme close-up of the chrome badge on the car grille, mirror-finish reflecting studio lights, precision engineering on display", cameraMove: "rack-focus", lens: "100mm", lighting: "accent-spot", durationSec: 3, skills: [] },
          { shotType: "wide", description: "Full car reveal in studio", prompt: "Wide shot as lights snap on revealing the full luxury car in studio, gleaming under perfect lighting, dramatic shadows on the ground, automotive elegance", cameraMove: "orbit", lens: "24mm", lighting: "full-studio", durationSec: 5, skills: ["skill-automotive-lighting"] },
          { shotType: "aerial", description: "Car driving on coastal highway", prompt: "Aerial tracking shot of the luxury car driving along a dramatic coastal highway at golden hour, ocean waves crashing below, winding road ahead", cameraMove: "tracking-aerial", lens: "35mm", lighting: "golden-hour", durationSec: 5, skills: [] },
          { shotType: "medium", description: "Driver's confident profile", prompt: "Medium shot through the window of a confident driver in profile, city lights reflecting on the glass, leather interior visible, composure and control", cameraMove: "tracking-side", lens: "50mm", lighting: "city-reflections", durationSec: 4, skills: [] },
          { shotType: "close", description: "Wheel spinning on wet road", prompt: "Close-up of a premium alloy wheel spinning on wet road surface, water spray catching light, tire gripping the asphalt, performance engineering", cameraMove: "low-tracking", lens: "50mm", lighting: "wet-road-reflections", durationSec: 4, skills: ["skill-slow-motion"] },
        ],
      },
    ],
  },
  {
    id: "comm-perfume-luxury",
    name: "Luxury Perfume Ad",
    category: "commercial",
    description: "Ethereal perfume commercial with slow-motion and golden light.",
    tags: ["perfume", "luxury", "beauty", "slow-motion", "ethereal"],
    estimatedDuration: 20,
    difficulty: "intermediate",
    recommendedSkills: ["skill-slow-motion", "skill-bokeh"],
    scenes: [
      {
        title: "Essence",
        description: "A model interacts with the perfume bottle in an ethereal setting.",
        location: "Abstract studio",
        timeOfDay: "timeless",
        mood: "sensual, elegant",
        shots: [
          { shotType: "extreme-close", description: "Perfume bottle in golden light", prompt: "Extreme close-up of an ornate perfume bottle catching golden light, liquid inside shimmering, faceted glass creating rainbow refractions on the background", cameraMove: "slow-orbit", lens: "100mm", lighting: "golden-accent", durationSec: 4, skills: ["skill-bokeh"] },
          { shotType: "medium", description: "Model in flowing fabric", prompt: "Medium shot of an elegant model surrounded by flowing silk fabric caught in wind, soft golden backlighting creating a halo effect, dreamlike movement", cameraMove: "slow-orbit", lens: "85mm", lighting: "backlit-golden", durationSec: 4, skills: ["skill-slow-motion"] },
          { shotType: "close", description: "Perfume mist in slow motion", prompt: "Close-up slow motion of perfume mist being sprayed, golden droplets suspended in air, light refracting through each tiny particle, abstract beauty", cameraMove: "static", lens: "100mm", lighting: "backlit-particles", durationSec: 4, skills: ["skill-slow-motion"] },
          { shotType: "close", description: "Model's neck and collarbone", prompt: "Close-up of the model's neck and collarbone, a droplet of perfume glistening on skin, warm golden lighting creating depth and warmth", cameraMove: "slow-tilt-up", lens: "85mm", lighting: "warm-beauty", durationSec: 4, skills: ["skill-bokeh"] },
          { shotType: "medium", description: "Product beauty shot", prompt: "Medium beauty shot of the perfume bottle on a reflective gold surface, soft bokeh lights in the background, the brand name elegantly visible, luxury product photography", cameraMove: "slow-push", lens: "85mm", lighting: "product-beauty", durationSec: 4, skills: [] },
        ],
      },
    ],
  },
  {
    id: "comm-food-burger",
    name: "Gourmet Burger Commercial",
    category: "commercial",
    description: "Mouth-watering food commercial with extreme close-ups and steam.",
    tags: ["food", "burger", "restaurant", "appetizing", "close-up"],
    estimatedDuration: 20,
    difficulty: "beginner",
    recommendedSkills: ["skill-food-styling", "skill-slow-motion"],
    scenes: [
      {
        title: "The Build",
        description: "A gourmet burger is assembled ingredient by ingredient.",
        location: "Restaurant kitchen",
        timeOfDay: "day",
        mood: "appetizing, craftsmanship",
        shots: [
          { shotType: "close", description: "Sizzling patty on grill", prompt: "Close-up of a thick gourmet burger patty sizzling on a hot grill, juices bubbling on the surface, flame licking the edges, smoke rising, food photography", cameraMove: "static", lens: "100mm", lighting: "grill-fire", durationSec: 4, skills: ["skill-food-styling"] },
          { shotType: "extreme-close", description: "Cheese melting on patty", prompt: "Extreme close-up slow motion of a slice of cheese being placed on the hot patty, slowly melting and draping over the edges, steam rising, gooey perfection", cameraMove: "static", lens: "100mm", lighting: "warm-overhead", durationSec: 4, skills: ["skill-slow-motion", "skill-food-styling"] },
          { shotType: "close", description: "Fresh vegetables sliced", prompt: "Close-up of crisp lettuce, ripe tomato slices, and red onion rings being placed on a toasted bun, droplets of water on the vegetables, freshness", cameraMove: "slow-tilt-down", lens: "85mm", lighting: "bright-natural", durationSec: 3, skills: ["skill-food-styling"] },
          { shotType: "medium", description: "Chef assembling the burger", prompt: "Medium shot of a chef's hands carefully assembling the gourmet burger, adding sauce with precision, steam rising, kitchen in soft focus behind", cameraMove: "static", lens: "50mm", lighting: "kitchen-warm", durationSec: 4, skills: [] },
          { shotType: "close", description: "Final burger beauty shot", prompt: "Close-up beauty shot of the completed gourmet burger on a wooden board, seeds glistening on the bun, layers visible, steam rising, a perfect toothpick through the top", cameraMove: "slow-orbit", lens: "85mm", lighting: "beauty-warm", durationSec: 5, skills: ["skill-food-styling"] },
        ],
      },
    ],
  },
  {
    id: "comm-tech-phone",
    name: "Smartphone Launch",
    category: "commercial",
    description: "Sleek tech product launch video with holographic elements.",
    tags: ["tech", "smartphone", "launch", "futuristic", "minimal"],
    estimatedDuration: 25,
    difficulty: "intermediate",
    recommendedSkills: ["skill-product-lighting", "skill-holographic"],
    scenes: [
      {
        title: "Introducing the Device",
        description: "A new smartphone is revealed with cinematic flair.",
        location: "Abstract tech environment",
        timeOfDay: "timeless",
        mood: "innovation, sleek",
        shots: [
          { shotType: "establishing", description: "Dark void with particle effects", prompt: "Dark void environment with floating light particles, a subtle grid floor fading into darkness, anticipation of something emerging, futuristic tech aesthetic", cameraMove: "slow-push", lens: "35mm", lighting: "ambient-particles", durationSec: 4, skills: ["skill-holographic"] },
          { shotType: "close", description: "Phone emerging from darkness", prompt: "Close-up of a sleek smartphone slowly emerging from shadow, edge lighting highlighting its thin profile, glass and metal surfaces catching light", cameraMove: "slow-orbit", lens: "85mm", lighting: "edge-lighting", durationSec: 5, skills: ["skill-product-lighting"] },
          { shotType: "extreme-close", description: "Camera module detail", prompt: "Extreme close-up of the smartphone camera module, lens glass reflecting rainbow light, precision engineering of each ring and element visible", cameraMove: "rack-focus", lens: "100mm", lighting: "macro-detail", durationSec: 3, skills: ["skill-product-lighting"] },
          { shotType: "medium", description: "Screen displaying interface", prompt: "Medium shot of the phone screen glowing with a vibrant interface, colors reflecting off the surrounding dark surface, UI elements crisp and clear", cameraMove: "slow-tilt", lens: "50mm", lighting: "screen-glow", durationSec: 4, skills: [] },
          { shotType: "wide", description: "Phone with holographic specs", prompt: "Wide shot of the phone floating in space surrounded by holographic text displaying specs and features, light beams emanating, tech showcase moment", cameraMove: "orbit", lens: "35mm", lighting: "holographic-blue", durationSec: 5, skills: ["skill-holographic"] },
          { shotType: "close", description: "Final product hero shot", prompt: "Close-up hero shot of the smartphone at a dramatic angle on a reflective surface, perfect lighting highlighting every curve, brand logo visible, premium tech product", cameraMove: "slow-dolly", lens: "85mm", lighting: "hero-product", durationSec: 4, skills: ["skill-product-lighting"] },
        ],
      },
    ],
  },
  {
    id: "comm-fashion-runway",
    name: "Fashion Runway Highlight",
    category: "commercial",
    description: "High fashion runway show highlight reel with dramatic lighting.",
    tags: ["fashion", "runway", "high-fashion", "glamour", "editorial"],
    estimatedDuration: 22,
    difficulty: "intermediate",
    recommendedSkills: ["skill-fashion-lighting", "skill-slow-motion"],
    scenes: [
      {
        title: "The Show",
        description: "Models walk a dramatically lit runway.",
        location: "Fashion runway",
        timeOfDay: "night",
        mood: "glamour, edge",
        shots: [
          { shotType: "establishing", description: "Runway in dramatic light", prompt: "Establishing shot of a high fashion runway, dramatic spotlights creating pools of light, audience in silhouette on both sides, fog machine haze", cameraMove: "slow-dolly-back", lens: "24mm", lighting: "runway-spots", durationSec: 4, skills: ["skill-fashion-lighting"] },
          { shotType: "wide", description: "Model emerging onto runway", prompt: "Wide shot of a model emerging from backstage curtains onto the runway, dramatic silhouette transforming as they step into the spotlight, haute couture ensemble", cameraMove: "static", lens: "35mm", lighting: "backlit-spot", durationSec: 4, skills: [] },
          { shotType: "medium", description: "Model walking with confidence", prompt: "Medium shot of a model walking the runway with fierce confidence, fabric flowing and catching the light, strong jawline, editorial makeup, power stride", cameraMove: "tracking-backward", lens: "50mm", lighting: "runway-follow", durationSec: 4, skills: ["skill-slow-motion"] },
          { shotType: "close", description: "Fabric detail in motion", prompt: "Close-up of haute couture fabric in motion, intricate embroidery catching light, sequins sparkling, the craftsmanship of the garment visible in each fold", cameraMove: "slow-tracking", lens: "85mm", lighting: "detail-spot", durationSec: 3, skills: ["skill-slow-motion"] },
          { shotType: "extreme-close", description: "Model's eyes at end of runway", prompt: "Extreme close-up of the model's eyes at the end of the runway, bold editorial eye makeup, fierce gaze, camera flashes reflecting in the pupils", cameraMove: "static", lens: "100mm", lighting: "flash-reflections", durationSec: 3, skills: [] },
          { shotType: "wide", description: "Finale with all models", prompt: "Wide shot of the runway finale, all models walking in formation, dramatic lighting creating silhouettes, applause implied, the designer emerging for a bow", cameraMove: "slow-crane-up", lens: "24mm", lighting: "finale-spectacular", durationSec: 4, skills: ["skill-fashion-lighting"] },
        ],
      },
    ],
  },
  {
    id: "comm-real-estate",
    name: "Luxury Real Estate Tour",
    category: "commercial",
    description: "Premium real estate property showcase with sweeping interior and aerial shots.",
    tags: ["real-estate", "luxury", "property", "interior", "aerial"],
    estimatedDuration: 28,
    difficulty: "beginner",
    recommendedSkills: ["skill-architectural-lighting"],
    scenes: [
      {
        title: "Property Showcase",
        description: "Tour of a luxury modern home.",
        location: "Luxury home",
        timeOfDay: "golden-hour",
        mood: "aspirational, serene",
        shots: [
          { shotType: "aerial", description: "Aerial approach to property", prompt: "Aerial drone shot approaching a modern luxury home nestled in hills, infinity pool visible, landscaped gardens, golden hour light bathing the architecture", cameraMove: "approach-descend", lens: "24mm", lighting: "golden-hour", durationSec: 5, skills: [] },
          { shotType: "establishing", description: "Grand entrance exterior", prompt: "Establishing shot of the grand entrance of a luxury modern home, tall glass doors, manicured hedges, warm light spilling from inside onto the stone pathway", cameraMove: "slow-push", lens: "24mm", lighting: "warm-interior-spill", durationSec: 4, skills: ["skill-architectural-lighting"] },
          { shotType: "wide", description: "Open plan living room", prompt: "Wide shot gliding into the open plan living room, double-height ceiling, floor-to-ceiling windows with panoramic views, designer furniture, warm ambient lighting", cameraMove: "gimbal-glide-forward", lens: "16mm", lighting: "ambient-warm", durationSec: 5, skills: [] },
          { shotType: "medium", description: "Gourmet kitchen", prompt: "Medium shot of a stunning gourmet kitchen with marble countertops, pendant lights, a chef's island, morning light streaming through skylights", cameraMove: "slow-pan", lens: "24mm", lighting: "skylight-natural", durationSec: 4, skills: [] },
          { shotType: "wide", description: "Infinity pool at sunset", prompt: "Wide shot of the infinity pool at sunset, water perfectly still reflecting the orange sky, the home glowing behind, mountains in the distance, ultimate luxury living", cameraMove: "slow-dolly-side", lens: "35mm", lighting: "sunset-warm", durationSec: 5, skills: [] },
          { shotType: "aerial", description: "Final aerial pullback", prompt: "Aerial drone shot pulling back from the property at golden hour, revealing the full estate, the pool, the landscape, the breathtaking location, aspirational lifestyle", cameraMove: "pullback-ascend", lens: "24mm", lighting: "golden-hour", durationSec: 5, skills: [] },
        ],
      },
    ],
  },
  {
    id: "comm-fitness-brand",
    name: "Athletic Performance Ad",
    category: "commercial",
    description: "High-energy athletic performance commercial with slow motion and dynamic angles.",
    tags: ["fitness", "athletic", "performance", "energy", "sports"],
    estimatedDuration: 22,
    difficulty: "intermediate",
    recommendedSkills: ["skill-slow-motion", "skill-action-camera"],
    scenes: [
      {
        title: "Push Beyond",
        description: "An athlete pushes through an intense workout.",
        location: "Training facility",
        timeOfDay: "dawn",
        mood: "determination, power",
        shots: [
          { shotType: "establishing", description: "Empty gym at dawn", prompt: "Establishing shot of a dark training facility at dawn, morning light just beginning to filter through industrial windows, equipment silhouetted, single figure visible", cameraMove: "slow-push", lens: "24mm", lighting: "dawn-industrial", durationSec: 4, skills: [] },
          { shotType: "close", description: "Hands chalking up", prompt: "Close-up of athletic hands clapping chalk powder, white dust exploding in slow motion, backlit by dawn light streaming through windows", cameraMove: "static", lens: "85mm", lighting: "backlit-chalk", durationSec: 3, skills: ["skill-slow-motion"] },
          { shotType: "medium", description: "Power clean lift", prompt: "Medium shot of an athlete performing a powerful clean and jerk, muscles engaged, explosive upward movement, barbell suspended at the peak, intensity in the expression", cameraMove: "slight-push", lens: "35mm", lighting: "dramatic-side", durationSec: 4, skills: ["skill-slow-motion", "skill-action-camera"] },
          { shotType: "extreme-close", description: "Sweat droplet falling", prompt: "Extreme close-up slow motion of a sweat droplet falling from the athlete's brow, catching the morning light like a prism, determination embodied", cameraMove: "static", lens: "100mm", lighting: "backlit-macro", durationSec: 3, skills: ["skill-slow-motion"] },
          { shotType: "wide", description: "Sprint in warehouse space", prompt: "Wide shot of the athlete sprinting through a warehouse training space, motion blur on the background, body in sharp focus, raw athletic power", cameraMove: "tracking-side", lens: "35mm", lighting: "industrial-dawn", durationSec: 4, skills: ["skill-action-camera"] },
          { shotType: "medium", description: "Victory moment", prompt: "Medium shot of the athlete standing victorious, chest heaving, looking up at the light streaming in, hands on hips, the embodiment of achievement", cameraMove: "slow-orbit", lens: "50mm", lighting: "golden-dawn", durationSec: 4, skills: [] },
        ],
      },
    ],
  },
  {
    id: "comm-watch-luxury",
    name: "Luxury Watch Showcase",
    category: "commercial",
    description: "Premium timepiece commercial with macro details and lifestyle shots.",
    tags: ["watch", "luxury", "timepiece", "macro", "precision"],
    estimatedDuration: 22,
    difficulty: "intermediate",
    recommendedSkills: ["skill-product-lighting", "skill-macro"],
    scenes: [
      {
        title: "Timeless Craft",
        description: "A luxury watch showcased through macro and lifestyle.",
        location: "Studio / Yacht",
        timeOfDay: "golden-hour",
        mood: "precision, luxury",
        shots: [
          { shotType: "extreme-close", description: "Watch mechanism close-up", prompt: "Extreme close-up of a luxury watch movement visible through the exhibition caseback, tiny gears turning with precision, jewel bearings gleaming, micro-engineering", cameraMove: "slow-orbit", lens: "100mm", lighting: "macro-spot", durationSec: 5, skills: ["skill-macro", "skill-product-lighting"] },
          { shotType: "close", description: "Watch face in perfect light", prompt: "Close-up of the watch face at a dramatic angle, applied indices catching light individually, hands frozen at 10:10, sapphire crystal creating subtle reflections", cameraMove: "slow-tilt", lens: "85mm", lighting: "precision-spot", durationSec: 4, skills: ["skill-product-lighting"] },
          { shotType: "medium", description: "Watch on wrist at yacht wheel", prompt: "Medium shot of the watch on a man's wrist at a yacht steering wheel, ocean visible in the background, golden hour light, lifestyle context, nautical elegance", cameraMove: "rack-focus", lens: "85mm", lighting: "golden-nautical", durationSec: 4, skills: [] },
          { shotType: "extreme-close", description: "Crown detail", prompt: "Extreme close-up of the watch crown with engraved logo, fingers about to adjust it, the precision of the knurling visible, tactile quality", cameraMove: "static", lens: "100mm", lighting: "detail-accent", durationSec: 3, skills: ["skill-macro"] },
          { shotType: "close", description: "Hero product shot", prompt: "Close-up hero shot of the luxury watch standing on a dark reflective surface, perfectly lit to showcase every facet, the brand at its finest, aspirational timepiece", cameraMove: "slow-orbit", lens: "85mm", lighting: "hero-product", durationSec: 4, skills: ["skill-product-lighting"] },
        ],
      },
    ],
  },
];
