import type { CinematicTemplate } from "../types.js";

export const commercialExtendedTemplates: CinematicTemplate[] = [
  {
    id: "comm-beer-craft",
    name: "Craft Beer Brewery",
    category: "commercial",
    description: "Artisanal craft beer commercial with brewing process and golden pours.",
    tags: ["beer", "craft", "brewery", "artisanal", "golden"],
    estimatedDuration: 18,
    difficulty: "beginner",
    recommendedSkills: ["skill-food-styling", "skill-product-lighting"],
    scenes: [{ title: "Brewed With Passion", description: "From grain to glass, the craft beer journey.", location: "Craft brewery", timeOfDay: "day", mood: "warmth, craftsmanship", shots: [
      { shotType: "wide", description: "Rustic brewery interior", prompt: "Wide shot of a rustic craft brewery interior, copper tanks gleaming, wooden barrels stacked, steam rising from the mash tun, artisanal atmosphere", cameraMove: "slow-pan", lens: "24mm", lighting: "warm-industrial", durationSec: 4, skills: [] },
      { shotType: "close", description: "Grain pouring through hands", prompt: "Close-up of golden barley grain pouring through a brewer's weathered hands, each kernel selected for quality, the foundation of great beer", cameraMove: "static", lens: "85mm", lighting: "grain-golden", durationSec: 3, skills: ["skill-food-styling"] },
      { shotType: "close", description: "Beer pouring into glass", prompt: "Close-up of amber beer being poured into a branded pint glass, perfect head forming, bubbles rising, golden liquid catching the light, thirst-inducing", cameraMove: "static", lens: "85mm", lighting: "beer-hero", durationSec: 4, skills: ["skill-product-lighting"] },
      { shotType: "medium", description: "Friends toasting at bar", prompt: "Medium shot of friends raising filled glasses at a wooden bar, genuine laughter, the clink of glass, the social joy of a shared craft beer", cameraMove: "static", lens: "50mm", lighting: "bar-warm", durationSec: 3, skills: [] },
      { shotType: "close", description: "Condensation on cold glass", prompt: "Close-up hero shot of the branded glass with perfect condensation droplets, the beer glowing amber, a soft bokeh background of the brewery, product perfection", cameraMove: "slow-orbit", lens: "85mm", lighting: "hero-product", durationSec: 4, skills: ["skill-product-lighting"] },
    ]}],
  },
  {
    id: "comm-airline-premium",
    name: "Premium Airline Experience",
    category: "commercial",
    description: "Luxury airline commercial showcasing first-class travel experience.",
    tags: ["airline", "luxury", "travel", "first-class", "premium"],
    estimatedDuration: 22,
    difficulty: "intermediate",
    recommendedSkills: ["skill-product-lighting"],
    scenes: [{ title: "Fly in Style", description: "The ultimate first-class flight experience.", location: "Airport / aircraft cabin", timeOfDay: "sunset", mood: "luxury, serenity", shots: [
      { shotType: "wide", description: "Aircraft at sunset gate", prompt: "Wide shot of a sleek modern aircraft at the gate during a golden sunset, ground crew preparing, the promise of an extraordinary journey", cameraMove: "slow-pan", lens: "35mm", lighting: "sunset-aviation", durationSec: 4, skills: [] },
      { shotType: "medium", description: "First-class cabin reveal", prompt: "Medium shot revealing the first-class cabin, private suites with sliding doors, warm ambient lighting, fresh orchids, the height of airborne luxury", cameraMove: "dolly-through", lens: "24mm", lighting: "cabin-ambient", durationSec: 4, skills: ["skill-product-lighting"] },
      { shotType: "close", description: "Champagne being poured", prompt: "Close-up of champagne being poured into a crystal flute by a white-gloved attendant, golden bubbles rising, 40000 feet of elegance", cameraMove: "static", lens: "85mm", lighting: "champagne-sparkle", durationSec: 3, skills: ["skill-product-lighting"] },
      { shotType: "medium", description: "Passenger reclining in suite", prompt: "Medium shot of a relaxed passenger in their private suite, cashmere blanket, noise-canceling headphones, gazing out at clouds turned pink by sunset", cameraMove: "slow-orbit", lens: "50mm", lighting: "window-golden", durationSec: 4, skills: [] },
      { shotType: "aerial", description: "Aircraft above clouds at sunset", prompt: "Aerial shot of the aircraft cruising serenely above a carpet of clouds, painted in sunset colors, contrails stretching behind, beautiful aviation", cameraMove: "tracking-alongside", lens: "35mm", lighting: "above-cloud-golden", durationSec: 4, skills: [] },
    ]}],
  },
  {
    id: "comm-sneaker-drop",
    name: "Sneaker Drop",
    category: "commercial",
    description: "Hype sneaker release with street culture aesthetics and energy.",
    tags: ["sneaker", "streetwear", "hype", "culture", "drop"],
    estimatedDuration: 16,
    difficulty: "beginner",
    recommendedSkills: ["skill-product-lighting"],
    scenes: [{ title: "The Drop", description: "A highly anticipated sneaker release.", location: "Urban streets / studio", timeOfDay: "night", mood: "hype, energy, culture", shots: [
      { shotType: "extreme-close", description: "Sneaker box opening", prompt: "Extreme close-up of a premium sneaker box being opened, tissue paper peeling back, the first glimpse of the shoe, the ritual of unboxing hype footwear", cameraMove: "static", lens: "100mm", lighting: "reveal-spotlight", durationSec: 3, skills: ["skill-product-lighting"] },
      { shotType: "close", description: "Sneaker rotating hero shot", prompt: "Close-up hero shot of the sneaker rotating on a platform, every detail visible, premium materials, unique colorway, design as art, product desire", cameraMove: "orbit", lens: "85mm", lighting: "studio-dramatic", durationSec: 4, skills: ["skill-product-lighting"] },
      { shotType: "medium", description: "Lacing up on the street", prompt: "Medium shot of someone lacing up the sneakers on a graffiti-covered urban street, street fashion outfit, confidence in every movement, cultural statement", cameraMove: "low-angle", lens: "35mm", lighting: "neon-street", durationSec: 3, skills: [] },
      { shotType: "close", description: "Walking shot of the shoes", prompt: "Close-up tracking shot at ground level of the sneakers in motion, walking on wet neon-lit pavement, reflections and puddles, the shoes commanding attention", cameraMove: "tracking-low", lens: "50mm", lighting: "neon-reflections", durationSec: 3, skills: [] },
      { shotType: "wide", description: "Line of fans waiting for drop", prompt: "Wide shot of a line of excited fans queuing outside a store at night, phones out, camping gear, the cultural phenomenon of a sneaker drop", cameraMove: "dolly-past", lens: "24mm", lighting: "store-neon", durationSec: 3, skills: [] },
    ]}],
  },
  {
    id: "comm-coffee-morning",
    name: "Coffee Morning Ritual",
    category: "commercial",
    description: "Warm coffee brand commercial celebrating the morning ritual.",
    tags: ["coffee", "morning", "ritual", "warmth", "lifestyle"],
    estimatedDuration: 16,
    difficulty: "beginner",
    recommendedSkills: ["skill-food-styling", "skill-product-lighting"],
    scenes: [{ title: "The Perfect Morning", description: "The ritual of a perfect morning coffee.", location: "Home kitchen", timeOfDay: "morning", mood: "warmth, comfort, ritual", shots: [
      { shotType: "close", description: "Coffee beans falling into grinder", prompt: "Close-up of whole coffee beans cascading into a grinder, rich brown tones, the sound of beans tumbling, the start of a morning ritual", cameraMove: "static", lens: "85mm", lighting: "morning-warm", durationSec: 3, skills: ["skill-food-styling"] },
      { shotType: "close", description: "Espresso extracting", prompt: "Close-up of espresso extracting from a machine, thick golden crema forming, the stream perfectly consistent, liquid perfection", cameraMove: "static", lens: "100mm", lighting: "espresso-glow", durationSec: 3, skills: ["skill-product-lighting"] },
      { shotType: "close", description: "Steam swirling from cup", prompt: "Close-up of steam swirling gracefully from a beautiful ceramic cup, morning light catching the vapor, the aroma almost visible, invitation to pause", cameraMove: "static", lens: "85mm", lighting: "steam-backlit", durationSec: 3, skills: [] },
      { shotType: "medium", description: "First sip by the window", prompt: "Medium shot of a person taking the first sip of coffee by a sunlit window, eyes closing with satisfaction, hands wrapped around the warm cup, morning peace", cameraMove: "static", lens: "50mm", lighting: "window-morning", durationSec: 4, skills: [] },
      { shotType: "close", description: "Product hero with branding", prompt: "Close-up of the coffee bag product next to the filled cup, morning light creating a warm glow, brand clearly visible, the source of the perfect morning", cameraMove: "slow-pull-back", lens: "85mm", lighting: "hero-warm", durationSec: 3, skills: ["skill-product-lighting"] },
    ]}],
  },
  {
    id: "comm-electric-vehicle",
    name: "Electric Vehicle Future",
    category: "commercial",
    description: "Sleek electric vehicle commercial emphasizing innovation and sustainability.",
    tags: ["electric", "vehicle", "future", "sustainable", "innovation"],
    estimatedDuration: 22,
    difficulty: "intermediate",
    recommendedSkills: ["skill-automotive-lighting"],
    scenes: [{ title: "Silent Power", description: "The future of driving is electric and exhilarating.", location: "City / highway / charging station", timeOfDay: "blue-hour", mood: "innovation, silence, power", shots: [
      { shotType: "wide", description: "EV gliding through city silently", prompt: "Wide shot of a sleek electric vehicle gliding silently through a modern city at blue hour, LED headlights cutting through the dusk, zero emissions, pure design", cameraMove: "tracking-side", lens: "35mm", lighting: "blue-hour-city", durationSec: 4, skills: ["skill-automotive-lighting"] },
      { shotType: "close", description: "Aerodynamic body details", prompt: "Close-up tracking shot along the vehicle's aerodynamic body, light playing across seamless panels, flush door handles, the design language of the future", cameraMove: "tracking-along", lens: "85mm", lighting: "reflective-sweep", durationSec: 4, skills: ["skill-automotive-lighting"] },
      { shotType: "medium", description: "Interior dashboard activating", prompt: "Medium shot from the driver's perspective as the minimal interior comes alive, screens illuminating, ambient lighting, the cockpit of tomorrow", cameraMove: "slow-pan", lens: "24mm", lighting: "ambient-interior", durationSec: 4, skills: [] },
      { shotType: "wide", description: "Highway acceleration", prompt: "Wide shot of the EV accelerating on an open highway, instant torque pressing the driver back, the landscape becoming a blur, silent power unleashed", cameraMove: "tracking-behind", lens: "35mm", lighting: "sunset-highway", durationSec: 4, skills: [] },
      { shotType: "medium", description: "Plugging in at home", prompt: "Medium shot of the owner plugging the vehicle in at home, the charging port pulsing with a gentle light, sustainable living made effortless, the future is here", cameraMove: "slow-push", lens: "50mm", lighting: "charge-glow", durationSec: 3, skills: [] },
    ]}],
  },
  {
    id: "comm-jewelry-elegant",
    name: "Fine Jewelry Showcase",
    category: "commercial",
    description: "Ultra-elegant jewelry commercial with sparkling gems and soft lighting.",
    tags: ["jewelry", "luxury", "diamonds", "elegant", "sparkle"],
    estimatedDuration: 16,
    difficulty: "intermediate",
    recommendedSkills: ["skill-product-lighting"],
    scenes: [{ title: "Eternal Brilliance", description: "Exquisite jewelry that captures light and desire.", location: "Studio / elegant setting", timeOfDay: "evening", mood: "luxury, desire, elegance", shots: [
      { shotType: "extreme-close", description: "Diamond catching light", prompt: "Extreme close-up of a brilliant-cut diamond rotating slowly, each facet catching and refracting light into prismatic fire, mesmerizing sparkle, the pinnacle of luxury", cameraMove: "slow-orbit", lens: "100mm", lighting: "diamond-fire", durationSec: 4, skills: ["skill-product-lighting"] },
      { shotType: "close", description: "Necklace draped on velvet", prompt: "Close-up of an exquisite diamond necklace draped across dark velvet, each stone perfectly set, the craftsmanship extraordinary, timeless elegance", cameraMove: "slow-track", lens: "85mm", lighting: "jewelry-sparkle", durationSec: 4, skills: ["skill-product-lighting"] },
      { shotType: "medium", description: "Clasp being fastened", prompt: "Medium shot of a woman's neck as the necklace clasp is gently fastened, the piece falling into place perfectly, an intimate moment of adornment", cameraMove: "slow-push", lens: "50mm", lighting: "soft-elegant", durationSec: 3, skills: [] },
      { shotType: "close", description: "Jewelry catching candlelight", prompt: "Close-up of the jewelry catching candlelight at an elegant dinner setting, sparkles dancing across the wearer's skin, the piece alive with light", cameraMove: "static", lens: "85mm", lighting: "candlelight-sparkle", durationSec: 4, skills: ["skill-product-lighting"] },
    ]}],
  },
  {
    id: "comm-sports-drink",
    name: "Sports Drink Energy",
    category: "commercial",
    description: "High-energy sports drink commercial with athletic performance.",
    tags: ["sports", "drink", "energy", "athletic", "performance"],
    estimatedDuration: 16,
    difficulty: "beginner",
    recommendedSkills: ["skill-slow-motion", "skill-product-lighting"],
    scenes: [{ title: "Fuel Your Fire", description: "The drink that powers peak athletic performance.", location: "Training facility / stadium", timeOfDay: "day", mood: "energy, power, hydration", shots: [
      { shotType: "medium", description: "Athlete training intensely", prompt: "Medium shot of an elite athlete in intense training, muscles straining, sweat flying, pushing to the absolute limit, the need for fuel evident", cameraMove: "tracking-side", lens: "35mm", lighting: "gym-dramatic", durationSec: 3, skills: [] },
      { shotType: "close", description: "Bottle splash reveal", prompt: "Close-up of the sports drink bottle being splashed with water, droplets flying in slow motion, the vibrant label revealed, refreshing energy in a bottle", cameraMove: "static", lens: "85mm", lighting: "splash-hero", durationSec: 3, skills: ["skill-slow-motion", "skill-product-lighting"] },
      { shotType: "close", description: "Drinking mid-workout", prompt: "Close-up of the athlete taking a powerful gulp of the drink mid-workout, sweat mixing with condensation on the bottle, instant refreshment visible", cameraMove: "static", lens: "85mm", lighting: "action-bright", durationSec: 3, skills: [] },
      { shotType: "medium", description: "Explosive performance burst", prompt: "Medium slow-motion shot of the athlete exploding into peak performance after drinking, a sprint start, a slam dunk, raw power fueled by the drink", cameraMove: "tracking-side", lens: "50mm", lighting: "stadium-bright", durationSec: 4, skills: ["skill-slow-motion"] },
      { shotType: "close", description: "Product hero with sweat drops", prompt: "Close-up hero shot of the bottle with condensation drops, vibrant color, positioned against a dynamic athletic background, the product that powers champions", cameraMove: "slow-orbit", lens: "85mm", lighting: "product-hero", durationSec: 3, skills: ["skill-product-lighting"] },
    ]}],
  },
];
