import type { CinematicTemplate } from "../types.js";

export const corporateExtendedTemplates: CinematicTemplate[] = [
  {
    id: "corp-training-intro",
    name: "Training Course Intro",
    category: "corporate",
    description: "Professional training course introduction with clear branding.",
    tags: ["training", "course", "education", "professional", "intro"],
    estimatedDuration: 14,
    difficulty: "beginner",
    recommendedSkills: [],
    scenes: [{ title: "Learn & Grow", description: "Opening sequence for a professional training course.", location: "Training room / office", timeOfDay: "day", mood: "professional, welcoming", shots: [
      { shotType: "establishing", description: "Modern training facility", prompt: "Establishing shot of a modern bright training facility, glass walls, comfortable chairs, large screen displays, a space designed for learning and growth", cameraMove: "dolly-through", lens: "24mm", lighting: "bright-professional", durationSec: 3, skills: [] },
      { shotType: "medium", description: "Instructor welcoming learners", prompt: "Medium shot of a confident instructor welcoming the camera with a warm smile, professional yet approachable, standing beside a branded presentation screen", cameraMove: "static", lens: "50mm", lighting: "soft-key", durationSec: 4, skills: [] },
      { shotType: "close", description: "Course title graphic reveal", prompt: "Close-up of the presentation screen as the course title animates on, clean typography, brand colors, professional design communicating quality content", cameraMove: "slow-push", lens: "50mm", lighting: "screen-bright", durationSec: 3, skills: [] },
      { shotType: "medium", description: "Engaged learners", prompt: "Medium shot of engaged learners taking notes, nodding in understanding, the value of professional development visible in their focus, diverse group", cameraMove: "slow-pan", lens: "35mm", lighting: "office-bright", durationSec: 4, skills: [] },
    ]}],
  },
  {
    id: "corp-warehouse-operations",
    name: "Operations Showcase",
    category: "corporate",
    description: "Impressive operations and logistics showcase with scale and precision.",
    tags: ["operations", "logistics", "warehouse", "scale", "precision"],
    estimatedDuration: 20,
    difficulty: "intermediate",
    recommendedSkills: [],
    scenes: [{ title: "The Machine", description: "Showcasing operational excellence at scale.", location: "Warehouse / fulfillment center", timeOfDay: "day", mood: "precision, scale, efficiency", shots: [
      { shotType: "aerial", description: "Massive warehouse from above", prompt: "Aerial shot descending over a massive fulfillment center, rows of organized inventory stretching into the distance, forklifts moving in choreographed paths", cameraMove: "slow-descend", lens: "16mm", lighting: "warehouse-bright", durationSec: 4, skills: [] },
      { shotType: "wide", description: "Automated conveyor systems", prompt: "Wide shot of automated conveyor belt systems in action, packages moving at speed along multiple paths, sorting with precision, technology driving efficiency", cameraMove: "dolly-alongside", lens: "24mm", lighting: "industrial-bright", durationSec: 4, skills: [] },
      { shotType: "close", description: "Robot arm picking and placing", prompt: "Close-up of a robotic arm precisely picking and placing items, smooth mechanical motion, sensor lights blinking, the future of logistics in action", cameraMove: "static", lens: "85mm", lighting: "tech-clean", durationSec: 4, skills: [] },
      { shotType: "medium", description: "Quality control inspection", prompt: "Medium shot of a quality control specialist inspecting products with care and precision, tablet in hand, ensuring every item meets standards before shipping", cameraMove: "slow-orbit", lens: "50mm", lighting: "inspection-bright", durationSec: 4, skills: [] },
      { shotType: "wide", description: "Trucks departing at dawn", prompt: "Wide shot of a fleet of branded delivery trucks departing the facility at dawn, fan formation, heading out to serve customers everywhere, the final mile", cameraMove: "slow-pan", lens: "35mm", lighting: "dawn-departure", durationSec: 4, skills: [] },
    ]}],
  },
  {
    id: "corp-ceo-vision",
    name: "CEO Vision Statement",
    category: "corporate",
    description: "Cinematic CEO thought leadership piece with compelling vision narrative.",
    tags: ["ceo", "vision", "leadership", "thought-leadership", "narrative"],
    estimatedDuration: 22,
    difficulty: "intermediate",
    recommendedSkills: ["skill-interview-lighting"],
    scenes: [{ title: "The Vision", description: "A CEO shares their bold vision for the future.", location: "Executive office / various", timeOfDay: "day", mood: "inspiration, authority", shots: [
      { shotType: "medium", description: "CEO at desk with city view", prompt: "Medium shot of the CEO seated at a clean executive desk, floor-to-ceiling windows showing the city skyline behind, composed and thoughtful, ready to share their vision", cameraMove: "static", lens: "50mm", lighting: "natural-executive", durationSec: 5, skills: ["skill-interview-lighting"] },
      { shotType: "close", description: "Speaking with conviction", prompt: "Close-up of the CEO speaking with genuine conviction, eyes bright with purpose, gesturing to emphasize key points, leadership presence undeniable", cameraMove: "static", lens: "85mm", lighting: "warm-key", durationSec: 4, skills: ["skill-interview-lighting"] },
      { shotType: "wide", description: "Walking through R&D facility", prompt: "Wide shot of the CEO walking through a cutting-edge R&D facility, stopping to examine innovations, the visionary among the builders, strategy meets execution", cameraMove: "tracking-behind", lens: "24mm", lighting: "lab-bright", durationSec: 4, skills: [] },
      { shotType: "medium", description: "Engaging with team members", prompt: "Medium shot of the CEO engaging warmly with frontline team members, genuine interest, listening intently, a leader who knows every role matters", cameraMove: "handheld-natural", lens: "35mm", lighting: "office-natural", durationSec: 4, skills: [] },
      { shotType: "wide", description: "Looking toward the future", prompt: "Wide shot of the CEO standing at the window looking out at the horizon, silhouetted against golden light, contemplating the future they are building", cameraMove: "slow-push", lens: "35mm", lighting: "sunset-silhouette", durationSec: 5, skills: [] },
    ]}],
  },
  {
    id: "corp-safety-first",
    name: "Workplace Safety",
    category: "corporate",
    description: "Professional workplace safety video emphasizing care and compliance.",
    tags: ["safety", "workplace", "compliance", "care", "protocol"],
    estimatedDuration: 18,
    difficulty: "beginner",
    recommendedSkills: [],
    scenes: [{ title: "Safety Matters", description: "Demonstrating commitment to workplace safety.", location: "Industrial / office workplace", timeOfDay: "day", mood: "responsibility, care", shots: [
      { shotType: "wide", description: "Safe modern workplace", prompt: "Wide shot of a well-maintained workplace with clear safety signage, clean walkways, emergency exits marked, PPE stations visible, safety as a priority", cameraMove: "dolly-through", lens: "24mm", lighting: "bright-clean", durationSec: 4, skills: [] },
      { shotType: "medium", description: "Worker donning PPE", prompt: "Medium shot of a worker carefully donning personal protective equipment, each piece checked methodically, hard hat, goggles, gloves, safety vest, professionalism", cameraMove: "static", lens: "50mm", lighting: "workplace-bright", durationSec: 4, skills: [] },
      { shotType: "close", description: "Safety inspection checklist", prompt: "Close-up of a safety inspector checking items on a digital checklist, each green checkmark representing a life protected, thoroughness saving lives", cameraMove: "static", lens: "85mm", lighting: "detail-bright", durationSec: 3, skills: [] },
      { shotType: "medium", description: "Team safety briefing", prompt: "Medium shot of a team gathered for a morning safety briefing, attentive faces, supervisor pointing at safety board, every day starts with safety first", cameraMove: "slow-pan", lens: "35mm", lighting: "morning-workplace", durationSec: 4, skills: [] },
      { shotType: "medium", description: "Workers going home safely", prompt: "Medium shot of workers leaving at end of shift, smiling, everyone going home safe, high fives and goodbyes, the real goal of safety culture achieved", cameraMove: "static", lens: "50mm", lighting: "end-of-day-warm", durationSec: 3, skills: [] },
    ]}],
  },
];
