import type { CinematicTemplate } from "../types.js";

export const corporateTemplates: CinematicTemplate[] = [
  {
    id: "corp-startup-launch",
    name: "Startup Launch Video",
    category: "corporate",
    description: "High-energy startup product launch video with modern aesthetics.",
    tags: ["startup", "launch", "product", "modern", "tech"],
    estimatedDuration: 20,
    difficulty: "beginner",
    recommendedSkills: ["skill-product-lighting"],
    scenes: [{
      title: "The Future is Here",
      description: "Unveiling a groundbreaking product to the world.",
      location: "Modern office / stage",
      timeOfDay: "day",
      mood: "excitement, innovation",
      shots: [
        { shotType: "establishing", description: "Sleek modern office exterior", prompt: "Establishing shot of a sleek modern tech company building, glass and steel architecture, the company logo subtly visible, innovation headquarters", cameraMove: "slow-tilt-up", lens: "24mm", lighting: "bright-modern", durationSec: 4, skills: [] },
        { shotType: "medium", description: "Team collaborating energetically", prompt: "Medium shot of a diverse team in a bright open office, energetically collaborating around a whiteboard full of ideas, the creative process in action", cameraMove: "dolly-through", lens: "35mm", lighting: "office-bright", durationSec: 4, skills: [] },
        { shotType: "close", description: "Product prototype reveal", prompt: "Close-up of hands carefully revealing a sleek product prototype, clean design, premium materials, the result of months of iteration, pride of creation", cameraMove: "slow-push", lens: "85mm", lighting: "product-hero", durationSec: 4, skills: ["skill-product-lighting"] },
        { shotType: "medium", description: "CEO on stage presenting", prompt: "Medium shot of a confident CEO on a minimal stage, large screen behind showing the product, passionate hand gestures, the audience captivated", cameraMove: "slow-orbit", lens: "50mm", lighting: "stage-spotlight", durationSec: 4, skills: [] },
        { shotType: "wide", description: "Audience reaction and applause", prompt: "Wide shot of the audience erupting in applause, phones raised recording the moment, genuine excitement in the room, a product that changes things", cameraMove: "slow-pan", lens: "24mm", lighting: "event-ambient", durationSec: 4, skills: [] },
      ],
    }],
  },
  {
    id: "corp-brand-story",
    name: "Brand Story Documentary",
    category: "corporate",
    description: "Authentic brand story with founder journey and company values.",
    tags: ["brand", "story", "founder", "documentary", "values"],
    estimatedDuration: 30,
    difficulty: "intermediate",
    recommendedSkills: ["skill-documentary-style", "skill-interview-lighting"],
    scenes: [{
      title: "How It Started",
      description: "The founder tells the origin story of the brand.",
      location: "Original workspace / current HQ",
      timeOfDay: "day",
      mood: "authentic, inspiring",
      shots: [
        { shotType: "medium", description: "Founder in interview setting", prompt: "Medium shot of a company founder in an interview setting, natural backdrop of their workspace, warm but professional lighting, genuine and approachable", cameraMove: "static", lens: "50mm", lighting: "interview-soft", durationSec: 5, skills: ["skill-interview-lighting"] },
        { shotType: "wide", description: "Original garage workspace", prompt: "Wide shot of the original humble workspace where the company started, a garage or small room, early prototypes on shelves, the beginning of something big", cameraMove: "slow-pan", lens: "24mm", lighting: "nostalgic-warm", durationSec: 4, skills: ["skill-documentary-style"] },
        { shotType: "close", description: "Hands working on early product", prompt: "Close-up of hands working on an early version of the product, rough but passionate craftsmanship, the seed of what would become a brand", cameraMove: "static", lens: "85mm", lighting: "workshop-warm", durationSec: 4, skills: [] },
        { shotType: "medium", description: "Team growth montage", prompt: "Medium shot montage-style of the growing team through the years, more faces joining, the space getting bigger, milestones on the wall, organic growth", cameraMove: "dolly-forward", lens: "35mm", lighting: "office-natural", durationSec: 4, skills: ["skill-documentary-style"] },
        { shotType: "wide", description: "Modern HQ bustling with activity", prompt: "Wide shot of the modern company headquarters bustling with purposeful activity, the contrast with the humble beginnings, a vision realized", cameraMove: "crane-up", lens: "24mm", lighting: "bright-corporate", durationSec: 4, skills: [] },
        { shotType: "close", description: "Founder smiling reflecting on journey", prompt: "Close-up of the founder with a genuine smile, eyes reflecting on the journey, not just pride but gratitude, the human behind the brand", cameraMove: "static", lens: "85mm", lighting: "warm-key", durationSec: 4, skills: ["skill-interview-lighting"] },
      ],
    }],
  },
  {
    id: "corp-recruitment",
    name: "Recruitment Culture Video",
    category: "corporate",
    description: "Engaging recruitment video showcasing company culture and team.",
    tags: ["recruitment", "culture", "team", "workplace", "hiring"],
    estimatedDuration: 22,
    difficulty: "beginner",
    recommendedSkills: [],
    scenes: [{
      title: "Join Our Team",
      description: "Showcasing what makes this company a great place to work.",
      location: "Office campus",
      timeOfDay: "day",
      mood: "welcoming, energetic, authentic",
      shots: [
        { shotType: "aerial", description: "Beautiful office campus from above", prompt: "Aerial shot of a modern office campus surrounded by greenery, outdoor spaces, people walking between buildings, an inviting place to build a career", cameraMove: "slow-descend", lens: "24mm", lighting: "bright-day", durationSec: 4, skills: [] },
        { shotType: "medium", description: "Diverse team in animated discussion", prompt: "Medium shot of a diverse group of colleagues in an animated brainstorming session, laughter and ideas flowing, collaborative energy, real chemistry", cameraMove: "handheld-natural", lens: "35mm", lighting: "office-natural", durationSec: 4, skills: [] },
        { shotType: "wide", description: "Creative workspace and amenities", prompt: "Wide shot touring through creative workspaces, standing desks, cozy meeting nooks, a coffee bar, plants everywhere, a space designed for great work", cameraMove: "dolly-through", lens: "24mm", lighting: "bright-airy", durationSec: 4, skills: [] },
        { shotType: "close", description: "Employee speaking to camera", prompt: "Close-up of a real employee speaking directly to camera with genuine enthusiasm about their work, authentic testimonial, relatable and honest", cameraMove: "static", lens: "50mm", lighting: "soft-interview", durationSec: 5, skills: [] },
        { shotType: "medium", description: "Team celebration moment", prompt: "Medium shot of the team celebrating a milestone, high fives and cheers, a cake or champagne, genuine moments of shared success and camaraderie", cameraMove: "handheld-natural", lens: "35mm", lighting: "office-festive", durationSec: 3, skills: [] },
        { shotType: "wide", description: "Sunset from office rooftop", prompt: "Wide shot from the office rooftop at golden hour, a few colleagues relaxing after work with drinks, the city skyline behind, work-life balance in frame", cameraMove: "slow-pan", lens: "24mm", lighting: "golden-hour", durationSec: 3, skills: [] },
      ],
    }],
  },
  {
    id: "corp-annual-report",
    name: "Annual Report Highlights",
    category: "corporate",
    description: "Polished annual report video with data visualization and executive summary.",
    tags: ["annual-report", "data", "executive", "financial", "achievements"],
    estimatedDuration: 24,
    difficulty: "intermediate",
    recommendedSkills: ["skill-data-visualization"],
    scenes: [{
      title: "Year in Review",
      description: "Highlighting the company's achievements over the past year.",
      location: "Corporate office / data graphics",
      timeOfDay: "day",
      mood: "professional, accomplished",
      shots: [
        { shotType: "establishing", description: "Company building time-lapse", prompt: "Establishing timelapse shot of the company headquarters from dawn to full day, activity increasing, lights turning on floor by floor, a living organization", cameraMove: "static", lens: "35mm", lighting: "dawn-to-day", durationSec: 4, skills: [] },
        { shotType: "medium", description: "CEO delivering message", prompt: "Medium shot of the CEO at a polished desk, delivering the annual message to stakeholders, confident and transparent, charts visible on a screen behind", cameraMove: "static", lens: "50mm", lighting: "executive-warm", durationSec: 5, skills: [] },
        { shotType: "close", description: "Data visualization rising", prompt: "Close-up of animated data visualization, revenue graphs climbing, market share expanding, key metrics highlighted with smooth animation, growth made visual", cameraMove: "static", lens: "50mm", lighting: "screen-glow", durationSec: 4, skills: ["skill-data-visualization"] },
        { shotType: "medium", description: "Team at work in various departments", prompt: "Medium shot montage of different departments at work, engineering, marketing, customer support, showing the breadth of talent driving results", cameraMove: "dolly-through", lens: "35mm", lighting: "office-bright", durationSec: 4, skills: [] },
        { shotType: "wide", description: "Global presence map", prompt: "Wide shot of a large screen displaying an animated global presence map, offices lighting up across continents, expansion visualized, worldwide impact", cameraMove: "slow-push", lens: "35mm", lighting: "map-glow", durationSec: 4, skills: ["skill-data-visualization"] },
        { shotType: "medium", description: "Forward-looking close", prompt: "Medium shot of the executive team standing together looking out large windows at the horizon, optimism and vision for the future, strong leadership", cameraMove: "slow-pull-back", lens: "35mm", lighting: "window-bright", durationSec: 3, skills: [] },
      ],
    }],
  },
  {
    id: "corp-event-highlight",
    name: "Corporate Event Highlight",
    category: "corporate",
    description: "Dynamic highlight reel from a corporate conference or event.",
    tags: ["event", "conference", "highlight", "networking", "keynote"],
    estimatedDuration: 18,
    difficulty: "beginner",
    recommendedSkills: [],
    scenes: [{
      title: "The Summit",
      description: "Highlights from an exciting corporate event.",
      location: "Convention center",
      timeOfDay: "day",
      mood: "energy, connection",
      shots: [
        { shotType: "wide", description: "Convention center entrance buzz", prompt: "Wide shot of attendees streaming into a large convention center, banners and branding everywhere, the buzz of anticipation, a major industry event", cameraMove: "static", lens: "24mm", lighting: "bright-event", durationSec: 3, skills: [] },
        { shotType: "medium", description: "Keynote speaker on stage", prompt: "Medium shot of a compelling keynote speaker on a large stage, massive screens behind displaying bold visuals, audience captivated, thought leadership", cameraMove: "slow-push", lens: "50mm", lighting: "stage-dramatic", durationSec: 4, skills: [] },
        { shotType: "close", description: "Audience engaged and taking notes", prompt: "Close-up of an attendee in the audience, eyes bright with interest, taking notes on a tablet, genuinely learning and engaged, the value of the event", cameraMove: "rack-focus", lens: "85mm", lighting: "audience-ambient", durationSec: 3, skills: [] },
        { shotType: "medium", description: "Networking and handshakes", prompt: "Medium shot of professionals networking in a bright exhibition space, handshakes, business card exchanges, animated conversations, connections being forged", cameraMove: "dolly-through", lens: "35mm", lighting: "exhibition-bright", durationSec: 4, skills: [] },
        { shotType: "wide", description: "Evening gala celebration", prompt: "Wide shot of an elegant evening gala, beautifully lit venue, people in formal attire, a live band playing, the social highlight of the event", cameraMove: "slow-pan", lens: "24mm", lighting: "gala-elegant", durationSec: 4, skills: [] },
      ],
    }],
  },
  {
    id: "corp-sustainability",
    name: "Sustainability Report",
    category: "corporate",
    description: "Corporate sustainability and environmental commitment showcase.",
    tags: ["sustainability", "green", "environment", "csr", "impact"],
    estimatedDuration: 22,
    difficulty: "intermediate",
    recommendedSkills: ["skill-landscape-grading", "skill-documentary-style"],
    scenes: [{
      title: "Our Commitment",
      description: "Showcasing environmental and social responsibility initiatives.",
      location: "Various sustainability projects",
      timeOfDay: "day",
      mood: "hope, responsibility",
      shots: [
        { shotType: "aerial", description: "Solar farm powering operations", prompt: "Aerial shot of a vast solar farm, rows of panels stretching to the horizon, powering company operations with clean energy, commitment to sustainability", cameraMove: "sweeping-forward", lens: "24mm", lighting: "bright-clean", durationSec: 4, skills: ["skill-landscape-grading"] },
        { shotType: "medium", description: "Employees planting trees", prompt: "Medium shot of company employees planting trees in a reforestation project, smiling, dirt on hands, genuine participation in environmental restoration", cameraMove: "handheld-natural", lens: "35mm", lighting: "outdoor-bright", durationSec: 4, skills: ["skill-documentary-style"] },
        { shotType: "close", description: "Recycled materials in production", prompt: "Close-up of recycled materials being used in the production process, visible texture of reclaimed materials transformed into new products, circular economy", cameraMove: "slow-track", lens: "85mm", lighting: "factory-natural", durationSec: 3, skills: [] },
        { shotType: "wide", description: "Green building and campus", prompt: "Wide shot of a LEED-certified green building with living walls, rainwater collection, EV charging stations, architecture that reflects environmental values", cameraMove: "slow-pan", lens: "24mm", lighting: "bright-day", durationSec: 4, skills: ["skill-landscape-grading"] },
        { shotType: "medium", description: "Community impact stories", prompt: "Medium shot of community members benefiting from the company's social programs, genuine smiles, real impact, the human side of corporate responsibility", cameraMove: "static", lens: "50mm", lighting: "natural-warm", durationSec: 4, skills: ["skill-documentary-style"] },
        { shotType: "wide", description: "Nature thriving near facilities", prompt: "Wide shot of wildlife and natural vegetation thriving near company facilities, a deer grazing, birds nesting, proof that industry and nature can coexist", cameraMove: "static", lens: "35mm", lighting: "golden-natural", durationSec: 3, skills: [] },
      ],
    }],
  },
  {
    id: "corp-product-demo",
    name: "Product Demo Walkthrough",
    category: "corporate",
    description: "Clean product demonstration video showing features and benefits.",
    tags: ["product", "demo", "features", "walkthrough", "saas"],
    estimatedDuration: 20,
    difficulty: "beginner",
    recommendedSkills: ["skill-product-lighting"],
    scenes: [{
      title: "See It in Action",
      description: "Walking through key product features and user experience.",
      location: "Clean studio / screen capture",
      timeOfDay: "day",
      mood: "clarity, confidence",
      shots: [
        { shotType: "close", description: "Product hero shot", prompt: "Close-up hero shot of the product against a clean minimal background, perfect lighting showing every detail, premium feel, the object of desire", cameraMove: "slow-orbit", lens: "85mm", lighting: "studio-hero", durationSec: 4, skills: ["skill-product-lighting"] },
        { shotType: "medium", description: "Person using the product naturally", prompt: "Medium shot of a real person using the product in a natural setting, intuitive interaction, ease of use evident, the product fitting seamlessly into life", cameraMove: "static", lens: "50mm", lighting: "lifestyle-natural", durationSec: 4, skills: [] },
        { shotType: "close", description: "Key feature close-up", prompt: "Close-up of the product's key differentiating feature in action, clear detail showing how it works, the innovation that sets it apart from competitors", cameraMove: "slow-push", lens: "85mm", lighting: "feature-highlight", durationSec: 4, skills: ["skill-product-lighting"] },
        { shotType: "over-shoulder", description: "Screen interface walkthrough", prompt: "Over-shoulder shot of a user navigating the product interface on screen, smooth scrolling, intuitive design visible, features being explored naturally", cameraMove: "static", lens: "50mm", lighting: "screen-ambient", durationSec: 4, skills: [] },
        { shotType: "medium", description: "Satisfied user reaction", prompt: "Medium shot of the user leaning back with satisfaction, a genuine nod of approval, the product delivering on its promise, trust earned", cameraMove: "static", lens: "50mm", lighting: "warm-natural", durationSec: 4, skills: [] },
      ],
    }],
  },
  {
    id: "corp-testimonial",
    name: "Customer Testimonial",
    category: "corporate",
    description: "Authentic customer testimonial with emotional storytelling.",
    tags: ["testimonial", "customer", "story", "authentic", "trust"],
    estimatedDuration: 22,
    difficulty: "beginner",
    recommendedSkills: ["skill-interview-lighting", "skill-documentary-style"],
    scenes: [{
      title: "Real Stories",
      description: "A real customer shares their experience and transformation.",
      location: "Customer's environment",
      timeOfDay: "day",
      mood: "authentic, trust, gratitude",
      shots: [
        { shotType: "wide", description: "Customer in their environment", prompt: "Wide shot establishing the customer in their natural environment, their home or business, real and authentic, this is where the product makes a difference", cameraMove: "slow-pan", lens: "24mm", lighting: "natural-ambient", durationSec: 4, skills: [] },
        { shotType: "medium", description: "Customer speaking to camera", prompt: "Medium shot of the customer speaking naturally to camera, relaxed and genuine, sharing their experience in their own words, relatable and trustworthy", cameraMove: "static", lens: "50mm", lighting: "soft-interview", durationSec: 5, skills: ["skill-interview-lighting"] },
        { shotType: "close", description: "Emotional moment of impact", prompt: "Close-up of the customer's face during an emotional moment, perhaps describing how the product solved a real problem, genuine gratitude visible", cameraMove: "static", lens: "85mm", lighting: "warm-key", durationSec: 4, skills: ["skill-documentary-style"] },
        { shotType: "medium", description: "Customer using the product", prompt: "Medium shot of the customer actually using the product in their daily life, natural and unscripted, proving the testimonial with real usage", cameraMove: "handheld-natural", lens: "35mm", lighting: "natural-environment", durationSec: 4, skills: [] },
        { shotType: "close", description: "Genuine smile of recommendation", prompt: "Close-up of the customer finishing their testimonial with a genuine smile, looking directly at camera, a personal recommendation that feels real", cameraMove: "static", lens: "85mm", lighting: "warm-natural", durationSec: 3, skills: ["skill-interview-lighting"] },
      ],
    }],
  },
];
