import type { CinematicTemplate } from "../types.js";

export const environmentExtendedTemplates: CinematicTemplate[] = [
  {
    id: "env-frozen-lake",
    name: "Frozen Lake Dawn",
    category: "environment",
    description: "Ethereal frozen lake landscape at dawn with ice crystals and mist.",
    tags: ["frozen", "lake", "ice", "dawn", "winter"],
    estimatedDuration: 18,
    difficulty: "beginner",
    recommendedSkills: ["skill-landscape-grading"],
    scenes: [{ title: "Frozen Silence", description: "A frozen lake at the first light of dawn.", location: "Frozen lake", timeOfDay: "dawn", mood: "stillness, purity", shots: [
      { shotType: "wide", description: "Frozen lake stretching to mountains", prompt: "Wide shot of a vast frozen lake stretching to distant snow-capped mountains, the surface a mirror of ice, first pink light touching the peaks, perfect stillness", cameraMove: "slow-pan", lens: "24mm", lighting: "dawn-pink", durationSec: 5, skills: ["skill-landscape-grading"] },
      { shotType: "close", description: "Ice crystals in macro detail", prompt: "Close-up of intricate ice crystals on the lake surface, each one a unique geometric masterpiece, catching the dawn light like tiny diamonds", cameraMove: "static", lens: "100mm", lighting: "crystal-sparkle", durationSec: 4, skills: [] },
      { shotType: "medium", description: "Mist rising from ice edge", prompt: "Medium shot of delicate mist rising from where ice meets unfrozen water, ethereal wisps catching golden light, the boundary between states of matter", cameraMove: "static", lens: "50mm", lighting: "mist-golden", durationSec: 4, skills: ["skill-landscape-grading"] },
      { shotType: "aerial", description: "Cracks and patterns from above", prompt: "Aerial shot looking straight down at the frozen lake, revealing incredible patterns of cracks, bubbles trapped in ice, and varying transparency, nature's abstract art", cameraMove: "slow-drift", lens: "35mm", lighting: "overhead-dawn", durationSec: 5, skills: [] },
    ]}],
  },
  {
    id: "env-rainforest-canopy",
    name: "Tropical Rainforest Canopy",
    category: "environment",
    description: "Lush tropical rainforest from floor to canopy with rich biodiversity.",
    tags: ["rainforest", "tropical", "canopy", "biodiversity", "lush"],
    estimatedDuration: 22,
    difficulty: "intermediate",
    recommendedSkills: ["skill-landscape-grading"],
    scenes: [{ title: "Living Cathedral", description: "Ascending through the layers of a tropical rainforest.", location: "Tropical rainforest", timeOfDay: "morning", mood: "life, wonder, richness", shots: [
      { shotType: "wide", description: "Forest floor with massive roots", prompt: "Wide shot of the rainforest floor, massive buttress roots of ancient trees, ferns and mosses covering every surface, shafts of light piercing through far above", cameraMove: "slow-pan", lens: "16mm", lighting: "forest-floor-dim", durationSec: 5, skills: [] },
      { shotType: "close", description: "Colorful frog on a leaf", prompt: "Close-up of a brilliant poison dart frog sitting on a glistening wet leaf, vivid blue and orange against deep green, nature's warning colors, tiny perfection", cameraMove: "static", lens: "100mm", lighting: "diffused-forest", durationSec: 4, skills: [] },
      { shotType: "medium", description: "Waterfall through the trees", prompt: "Medium shot of a hidden waterfall cascading through the trees, mist creating rainbows in the light beams, the constant soundtrack of flowing water", cameraMove: "slow-tilt-up", lens: "35mm", lighting: "waterfall-mist", durationSec: 4, skills: ["skill-landscape-grading"] },
      { shotType: "aerial", description: "Breaking through the canopy", prompt: "Aerial shot ascending through the canopy layer, bursting from green shadow into brilliant sunlight, the vast unbroken canopy stretching to the horizon like a green ocean", cameraMove: "ascending-through", lens: "16mm", lighting: "canopy-breakthrough", durationSec: 5, skills: ["skill-landscape-grading"] },
      { shotType: "close", description: "Toucan perched on a branch", prompt: "Close-up of a colorful toucan perched on a high branch, enormous beak catching sunlight, feathers ruffling in the breeze, a jewel of the canopy", cameraMove: "static", lens: "85mm", lighting: "canopy-bright", durationSec: 4, skills: [] },
    ]}],
  },
  {
    id: "env-sand-dunes",
    name: "Saharan Sand Dunes",
    category: "environment",
    description: "Mesmerizing sand dune landscape with wind-sculpted patterns.",
    tags: ["sahara", "sand", "dunes", "wind", "desert"],
    estimatedDuration: 18,
    difficulty: "beginner",
    recommendedSkills: ["skill-landscape-grading"],
    scenes: [{ title: "Sea of Sand", description: "Wind and light sculpt the desert dunes.", location: "Desert dunes", timeOfDay: "golden-hour", mood: "solitude, timelessness", shots: [
      { shotType: "aerial", description: "Endless dune field from above", prompt: "Aerial shot of an endless field of sand dunes stretching to the horizon, golden hour light creating deep shadows and bright ridges, mesmerizing repetition", cameraMove: "slow-forward", lens: "35mm", lighting: "golden-hour-desert", durationSec: 5, skills: ["skill-landscape-grading"] },
      { shotType: "wide", description: "Single dune ridge at sunset", prompt: "Wide shot of a single perfect dune ridge, the crisp line between light and shadow, wind carrying a veil of sand off the top, sculpted by nature", cameraMove: "static", lens: "35mm", lighting: "sunset-side", durationSec: 4, skills: ["skill-landscape-grading"] },
      { shotType: "close", description: "Wind patterns in sand", prompt: "Close-up of intricate ripple patterns in the sand created by wind, each grain casting its own tiny shadow, natural geometry at the smallest scale", cameraMove: "slow-track", lens: "85mm", lighting: "low-angle-golden", durationSec: 4, skills: [] },
      { shotType: "wide", description: "Camel caravan silhouette", prompt: "Wide shot of a distant camel caravan silhouetted against the setting sun, small figures crossing the vast landscape, timeless travel, human scale against nature", cameraMove: "static", lens: "24mm", lighting: "sunset-silhouette", durationSec: 5, skills: [] },
    ]}],
  },
  {
    id: "env-thunderstorm-plains",
    name: "Prairie Thunderstorm",
    category: "environment",
    description: "Dramatic supercell thunderstorm rolling across open prairie.",
    tags: ["thunderstorm", "prairie", "supercell", "lightning", "dramatic"],
    estimatedDuration: 20,
    difficulty: "intermediate",
    recommendedSkills: ["skill-weather-effects", "skill-landscape-grading"],
    scenes: [{ title: "The Wall Cloud", description: "A massive supercell descends on the open plains.", location: "Open prairie", timeOfDay: "afternoon", mood: "power, awe, danger", shots: [
      { shotType: "wide", description: "Supercell approaching over plains", prompt: "Wide shot of a massive supercell thunderstorm approaching over flat prairie, the wall cloud rotating ominously, dark against a still-lit horizon, raw atmospheric power", cameraMove: "static", lens: "16mm", lighting: "storm-contrast", durationSec: 5, skills: ["skill-weather-effects"] },
      { shotType: "establishing", description: "Lightning branching across sky", prompt: "Establishing shot of spectacular lightning branching across the entire sky, illuminating the supercell structure, multiple bolts in a single frame, nature's electricity", cameraMove: "static", lens: "24mm", lighting: "lightning-strobe", durationSec: 4, skills: ["skill-weather-effects"] },
      { shotType: "medium", description: "Rain curtain approaching", prompt: "Medium shot of a visible rain curtain sweeping across the prairie toward the camera, the boundary between dry and deluge, wind picking up dramatically", cameraMove: "static", lens: "50mm", lighting: "storm-green", durationSec: 4, skills: ["skill-landscape-grading"] },
      { shotType: "close", description: "Tall grass bending in wind", prompt: "Close-up of prairie grass bending violently in the storm wind, seeds and particles flying horizontally, the force of the storm made tangible", cameraMove: "static", lens: "85mm", lighting: "storm-dim", durationSec: 3, skills: [] },
      { shotType: "wide", description: "Rainbow emerging after storm", prompt: "Wide shot as the storm passes, a brilliant double rainbow emerging against the retreating dark clouds, golden sunlight returning, the calm after chaos", cameraMove: "slow-pan", lens: "24mm", lighting: "post-storm-golden", durationSec: 4, skills: ["skill-landscape-grading"] },
    ]}],
  },
  {
    id: "env-bioluminescent-bay",
    name: "Bioluminescent Bay",
    category: "environment",
    description: "Magical bioluminescent bay with glowing water and starry sky.",
    tags: ["bioluminescent", "bay", "glow", "night", "magical"],
    estimatedDuration: 18,
    difficulty: "intermediate",
    recommendedSkills: ["skill-astrophotography"],
    scenes: [{ title: "Living Light", description: "A bay that glows with bioluminescent organisms.", location: "Tropical bay", timeOfDay: "night", mood: "magic, otherworldly", shots: [
      { shotType: "wide", description: "Bay under the Milky Way", prompt: "Wide shot of a dark tropical bay under a brilliant Milky Way, the water beginning to show faint blue-green bioluminescent glow, stars reflected in still water", cameraMove: "static", lens: "16mm", lighting: "starlight-bio", durationSec: 5, skills: ["skill-astrophotography"] },
      { shotType: "medium", description: "Hand disturbing glowing water", prompt: "Medium shot of a hand gently disturbing the water surface, brilliant blue-green bioluminescence erupting around the fingers, liquid light, otherworldly beauty", cameraMove: "static", lens: "50mm", lighting: "bioluminescent-blue", durationSec: 4, skills: [] },
      { shotType: "close", description: "Glowing wave breaking on shore", prompt: "Close-up of a small wave breaking on the dark shore, the wave edge lighting up with intense bioluminescence, electric blue foam, magic made real", cameraMove: "static", lens: "85mm", lighting: "bio-wave", durationSec: 4, skills: [] },
      { shotType: "wide", description: "Kayak trail of light", prompt: "Wide shot of a kayak moving across the bay, leaving a brilliant trail of glowing blue-green light in its wake, the paddle creating bursts of light with each stroke", cameraMove: "tracking-above", lens: "24mm", lighting: "bio-trail", durationSec: 5, skills: ["skill-astrophotography"] },
    ]}],
  },
  {
    id: "env-cherry-blossom",
    name: "Cherry Blossom Season",
    category: "environment",
    description: "Dreamy cherry blossom season in a Japanese garden setting.",
    tags: ["cherry-blossom", "sakura", "japan", "spring", "petals"],
    estimatedDuration: 18,
    difficulty: "beginner",
    recommendedSkills: ["skill-landscape-grading"],
    scenes: [{ title: "Sakura", description: "Peak cherry blossom bloom in a serene garden.", location: "Japanese garden", timeOfDay: "afternoon", mood: "tranquility, beauty, ephemeral", shots: [
      { shotType: "wide", description: "Garden path under cherry blossoms", prompt: "Wide shot of a traditional Japanese garden path lined with cherry trees in full bloom, a canopy of soft pink, petals drifting down like snow, timeless beauty", cameraMove: "dolly-forward", lens: "35mm", lighting: "filtered-pink", durationSec: 5, skills: ["skill-landscape-grading"] },
      { shotType: "close", description: "Single blossom branch in detail", prompt: "Close-up of a single cherry blossom branch in exquisite detail, delicate pink petals, yellow stamens, soft bokeh of more blossoms behind, ephemeral perfection", cameraMove: "static", lens: "100mm", lighting: "backlit-soft", durationSec: 4, skills: [] },
      { shotType: "medium", description: "Petals falling on still pond", prompt: "Medium shot of cherry blossom petals falling onto a still pond surface, each creating tiny ripples, the reflection of pink trees in the water, dreamlike", cameraMove: "static", lens: "50mm", lighting: "reflected-pink", durationSec: 4, skills: ["skill-landscape-grading"] },
      { shotType: "wide", description: "Wind carrying petals away", prompt: "Wide shot as a gentle breeze lifts thousands of petals from the trees, creating a pink blizzard, sunlight catching each petal, the beautiful impermanence of sakura", cameraMove: "slow-pan", lens: "35mm", lighting: "golden-petal-shower", durationSec: 5, skills: [] },
    ]}],
  },
];
