import type { CinematicTemplate } from "../types.js";

export const environmentTemplates: CinematicTemplate[] = [
  {
    id: "env-mountain-sunrise",
    name: "Mountain Sunrise Timelapse",
    category: "environment",
    description: "Majestic mountain sunrise with rolling fog and golden light.",
    tags: ["mountain", "sunrise", "timelapse", "nature", "epic"],
    estimatedDuration: 20,
    difficulty: "beginner",
    recommendedSkills: ["skill-landscape-grading"],
    scenes: [{ title: "Dawn Breaks", description: "Sunrise over mountain peaks.", location: "Mountain range", timeOfDay: "dawn", mood: "majesty, peace", shots: [
      { shotType: "establishing", description: "Pre-dawn mountain silhouettes", prompt: "Establishing shot of mountain silhouettes against a deep blue pre-dawn sky, stars still visible, the first hint of orange on the eastern horizon", cameraMove: "static", lens: "24mm", lighting: "pre-dawn-blue", durationSec: 5, skills: [] },
      { shotType: "wide", description: "Fog rolling through valleys", prompt: "Wide shot of thick fog rolling through mountain valleys like rivers of cloud, first golden rays of sun touching the peaks above, ethereal and timeless", cameraMove: "timelapse", lens: "35mm", lighting: "first-light", durationSec: 5, skills: ["skill-landscape-grading"] },
      { shotType: "close", description: "Dewdrops on alpine flowers", prompt: "Close-up of dewdrops on delicate alpine wildflowers, each drop catching the golden dawn light like tiny prisms, nature's jewels", cameraMove: "rack-focus", lens: "100mm", lighting: "golden-macro", durationSec: 4, skills: [] },
      { shotType: "aerial", description: "Above the cloud layer", prompt: "Aerial shot above the cloud layer, mountain peaks piercing through like islands, the sun fully risen casting long golden rays, breathtaking scale", cameraMove: "slow-forward", lens: "24mm", lighting: "above-clouds-golden", durationSec: 6, skills: [] },
    ]}],
  },
  {
    id: "env-ocean-storm",
    name: "Ocean Storm Drama",
    category: "environment",
    description: "Powerful ocean storm with massive waves crashing against cliffs.",
    tags: ["ocean", "storm", "waves", "power", "dramatic"],
    estimatedDuration: 22,
    difficulty: "intermediate",
    recommendedSkills: ["skill-slow-motion", "skill-weather-effects"],
    scenes: [{ title: "Tempest", description: "A fierce storm batters the coastline.", location: "Rocky coastline", timeOfDay: "overcast", mood: "power, raw nature", shots: [
      { shotType: "wide", description: "Massive waves approaching coast", prompt: "Wide shot of massive dark waves rolling toward a rocky coastline under heavy storm clouds, the sea churning white, raw oceanic power", cameraMove: "static", lens: "24mm", lighting: "storm-overcast", durationSec: 5, skills: ["skill-weather-effects"] },
      { shotType: "medium", description: "Wave exploding against cliff", prompt: "Medium shot of a enormous wave slamming into sea cliffs, water exploding upward in a massive spray, foam cascading down, the force of nature", cameraMove: "static", lens: "50mm", lighting: "storm-dramatic", durationSec: 4, skills: ["skill-slow-motion"] },
      { shotType: "close", description: "Water rushing over rocks", prompt: "Close-up of turbulent water rushing over dark volcanic rocks, white foam patterns swirling, the texture and violence of storm surge, mesmerizing chaos", cameraMove: "static", lens: "85mm", lighting: "overcast-moody", durationSec: 4, skills: [] },
      { shotType: "aerial", description: "Storm waves from above", prompt: "Aerial shot looking down at storm waves creating massive white patterns against dark ocean water, the coast visible at the edge, nature's abstract art", cameraMove: "slow-drift", lens: "35mm", lighting: "storm-above", durationSec: 5, skills: [] },
      { shotType: "wide", description: "Lightning over the ocean", prompt: "Wide shot of lightning striking the ocean surface in the distance, illuminating towering storm clouds, the sea momentarily lit up in brilliant white", cameraMove: "static", lens: "24mm", lighting: "lightning-flash", durationSec: 4, skills: ["skill-weather-effects"] },
    ]}],
  },
  {
    id: "env-autumn-forest",
    name: "Autumn Forest Journey",
    category: "environment",
    description: "Serene walk through a vibrant autumn forest with golden canopy.",
    tags: ["autumn", "forest", "golden", "leaves", "serene"],
    estimatedDuration: 20,
    difficulty: "beginner",
    recommendedSkills: ["skill-landscape-grading"],
    scenes: [{ title: "Golden Path", description: "Walking through peak autumn colors.", location: "Deciduous forest", timeOfDay: "afternoon", mood: "serenity, nostalgia", shots: [
      { shotType: "establishing", description: "Canopy of golden leaves", prompt: "Establishing shot looking up through a canopy of brilliant golden and red autumn leaves, sunlight filtering through creating god rays, leaves gently falling", cameraMove: "slow-tilt-up", lens: "16mm", lighting: "filtered-golden", durationSec: 5, skills: ["skill-landscape-grading"] },
      { shotType: "wide", description: "Path through autumn forest", prompt: "Wide shot of a winding path through a forest at peak autumn, leaves carpeting the ground in gold and crimson, dappled sunlight, peaceful solitude", cameraMove: "dolly-forward", lens: "35mm", lighting: "dappled-autumn", durationSec: 5, skills: [] },
      { shotType: "close", description: "Single leaf falling", prompt: "Close-up of a single golden maple leaf slowly falling through the air, spinning gently, backlit by the sun, autumn's gentle release", cameraMove: "tracking-down", lens: "85mm", lighting: "backlit-golden", durationSec: 4, skills: [] },
      { shotType: "medium", description: "Stream with fallen leaves", prompt: "Medium shot of a clear forest stream with golden leaves floating on the surface, smooth rocks underneath, reflections of autumn trees, tranquil nature", cameraMove: "slow-pan", lens: "50mm", lighting: "reflected-autumn", durationSec: 3, skills: [] },
      { shotType: "wide", description: "Sunset through autumn trees", prompt: "Wide shot of the warm autumn sun setting through the trees, creating long golden rays, the entire forest glowing amber, a perfect autumn evening", cameraMove: "static", lens: "35mm", lighting: "golden-hour-autumn", durationSec: 3, skills: ["skill-landscape-grading"] },
    ]}],
  },
  {
    id: "env-desert-starscape",
    name: "Desert Night Sky",
    category: "environment",
    description: "Astounding night sky timelapse over a desert landscape.",
    tags: ["desert", "stars", "milky-way", "night", "timelapse"],
    estimatedDuration: 18,
    difficulty: "intermediate",
    recommendedSkills: ["skill-astrophotography"],
    scenes: [{ title: "Celestial Desert", description: "The Milky Way over desert formations.", location: "Desert", timeOfDay: "night", mood: "wonder, infinity", shots: [
      { shotType: "wide", description: "Desert sunset transition to night", prompt: "Wide timelapse shot of desert sunset rapidly transitioning to night, stars appearing one by one, the Milky Way emerging across the sky, desert formations silhouetted", cameraMove: "timelapse", lens: "16mm", lighting: "sunset-to-stars", durationSec: 5, skills: ["skill-astrophotography"] },
      { shotType: "establishing", description: "Full Milky Way arc", prompt: "Establishing shot of the full Milky Way arc stretching across the sky over dramatic desert rock formations, millions of stars, cosmic scale, humbling beauty", cameraMove: "slow-pan", lens: "16mm", lighting: "starlight", durationSec: 5, skills: ["skill-astrophotography"] },
      { shotType: "medium", description: "Star trails over arch formation", prompt: "Medium shot of star trails circling over a natural stone arch formation in the desert, long exposure painting light circles, timeless movement", cameraMove: "timelapse-rotation", lens: "24mm", lighting: "star-trails", durationSec: 4, skills: ["skill-astrophotography"] },
      { shotType: "close", description: "Desert plants under starlight", prompt: "Close-up of desert plants and cacti silhouetted against the star-filled sky, subtle starlight illumination on the spines, the Milky Way behind", cameraMove: "static", lens: "35mm", lighting: "ambient-starlight", durationSec: 4, skills: [] },
    ]}],
  },
  {
    id: "env-underwater-reef",
    name: "Coral Reef Exploration",
    category: "environment",
    description: "Vibrant underwater coral reef teeming with marine life.",
    tags: ["underwater", "coral", "reef", "marine", "tropical"],
    estimatedDuration: 22,
    difficulty: "intermediate",
    recommendedSkills: ["skill-underwater-vfx"],
    scenes: [{ title: "Reef World", description: "Diving through a vibrant coral reef.", location: "Tropical reef", timeOfDay: "day", mood: "wonder, vibrance", shots: [
      { shotType: "wide", description: "Sunlit reef from above", prompt: "Wide shot looking down at a vibrant coral reef from above, sunbeams penetrating the clear water, schools of fish creating silver clouds, colors everywhere", cameraMove: "slow-descend", lens: "16mm", lighting: "sunlit-underwater", durationSec: 5, skills: ["skill-underwater-vfx"] },
      { shotType: "medium", description: "Swimming through coral archway", prompt: "Medium shot swimming through a natural coral archway, fish parting to let us pass, anemones waving, the architecture of the reef surrounding us", cameraMove: "dolly-through", lens: "24mm", lighting: "ambient-underwater", durationSec: 5, skills: ["skill-underwater-vfx"] },
      { shotType: "close", description: "Clownfish in anemone", prompt: "Close-up of a colorful clownfish nestled in a bright purple anemone, tentacles swaying gently in the current, a tiny perfect world, vivid colors", cameraMove: "static", lens: "100mm", lighting: "natural-underwater", durationSec: 4, skills: [] },
      { shotType: "wide", description: "Sea turtle gliding past", prompt: "Wide shot of a graceful sea turtle gliding through the frame over the reef, ancient and serene, sunlight dappling its shell, a moment of marine majesty", cameraMove: "tracking-side", lens: "35mm", lighting: "dappled-underwater", durationSec: 4, skills: [] },
      { shotType: "establishing", description: "Reef wall dropping into abyss", prompt: "Establishing shot of the reef wall dropping away into the deep blue abyss below, the contrast between vibrant shallow reef and the mysterious deep, vertigo-inducing", cameraMove: "tilt-down", lens: "16mm", lighting: "gradient-blue", durationSec: 4, skills: ["skill-underwater-vfx"] },
    ]}],
  },
  {
    id: "env-city-timelapse",
    name: "City Day-to-Night",
    category: "environment",
    description: "Dynamic city timelapse from bustling day to glittering night.",
    tags: ["city", "timelapse", "urban", "skyline", "lights"],
    estimatedDuration: 18,
    difficulty: "beginner",
    recommendedSkills: [],
    scenes: [{ title: "Urban Pulse", description: "A city transforms from day to night.", location: "City skyline", timeOfDay: "day-to-night", mood: "energy, transformation", shots: [
      { shotType: "wide", description: "Busy intersection timelapse", prompt: "Wide timelapse shot of a busy city intersection from above, cars and people moving in fast streams of light and motion, the pulse of urban life", cameraMove: "static-overhead", lens: "24mm", lighting: "bright-day", durationSec: 4, skills: [] },
      { shotType: "establishing", description: "Skyline sunset transition", prompt: "Establishing timelapse shot of a city skyline transitioning from golden sunset to blue hour to night, lights switching on building by building, magical transformation", cameraMove: "static", lens: "35mm", lighting: "sunset-to-night", durationSec: 5, skills: [] },
      { shotType: "medium", description: "Office building floors lighting up", prompt: "Medium timelapse shot of a glass office building, floor after floor lighting up as night falls, workers visible as tiny silhouettes, the machine of commerce", cameraMove: "slow-tilt-up", lens: "50mm", lighting: "interior-glow", durationSec: 4, skills: [] },
      { shotType: "aerial", description: "Full city at night", prompt: "Aerial shot of the full city at night, a tapestry of light stretching to the horizon, highways as rivers of red and white light, the city that never sleeps", cameraMove: "slow-orbit", lens: "24mm", lighting: "city-night", durationSec: 5, skills: [] },
    ]}],
  },
  {
    id: "env-northern-lights",
    name: "Aurora Borealis",
    category: "environment",
    description: "Mesmerizing aurora borealis dancing over a snowy landscape.",
    tags: ["aurora", "northern-lights", "arctic", "snow", "celestial"],
    estimatedDuration: 20,
    difficulty: "intermediate",
    recommendedSkills: ["skill-astrophotography", "skill-landscape-grading"],
    scenes: [{ title: "Northern Dance", description: "The aurora dances over the Arctic.", location: "Arctic landscape", timeOfDay: "night", mood: "wonder, ethereal", shots: [
      { shotType: "wide", description: "First green glow on horizon", prompt: "Wide shot of a snowy Arctic landscape, the first faint green glow of the aurora appearing on the northern horizon, stars crystal clear above, pristine silence", cameraMove: "static", lens: "16mm", lighting: "aurora-first-glow", durationSec: 5, skills: ["skill-astrophotography"] },
      { shotType: "establishing", description: "Full aurora display", prompt: "Establishing shot of a full aurora borealis display, green and purple curtains of light dancing across the entire sky, reflecting off a frozen lake below, spectacular", cameraMove: "timelapse", lens: "16mm", lighting: "aurora-full", durationSec: 6, skills: ["skill-astrophotography", "skill-landscape-grading"] },
      { shotType: "medium", description: "Aurora reflected in ice", prompt: "Medium shot of the aurora's green and purple light reflected in a sheet of dark ice, creating a mirror world effect, the dance of light doubled", cameraMove: "slow-pan", lens: "24mm", lighting: "aurora-reflection", durationSec: 5, skills: ["skill-landscape-grading"] },
      { shotType: "close", description: "Snow crystals in aurora light", prompt: "Close-up of snow crystals on a surface catching the green aurora light, each crystal a tiny prism, the aurora visible as a soft glow behind, miniature wonder", cameraMove: "static", lens: "100mm", lighting: "aurora-ambient", durationSec: 4, skills: [] },
    ]}],
  },
  {
    id: "env-volcanic-eruption",
    name: "Volcanic Eruption",
    category: "environment",
    description: "Dramatic volcanic eruption with lava flows and ash plumes.",
    tags: ["volcano", "eruption", "lava", "fire", "dramatic"],
    estimatedDuration: 22,
    difficulty: "advanced",
    recommendedSkills: ["skill-vfx-fire", "skill-landscape-grading"],
    scenes: [{ title: "Fire Mountain", description: "An active volcano erupts spectacularly.", location: "Volcanic landscape", timeOfDay: "night", mood: "power, primal", shots: [
      { shotType: "establishing", description: "Volcano with lava fountain", prompt: "Establishing shot of an active volcano at night, a massive fountain of lava erupting from the crater, orange and red against the dark sky, primal power on display", cameraMove: "static", lens: "35mm", lighting: "lava-glow", durationSec: 5, skills: ["skill-vfx-fire"] },
      { shotType: "close", description: "Lava flowing and cooling", prompt: "Close-up of glowing lava flowing like a river, the surface cooling to dark rock while bright orange liquid seeps through cracks, mesmerizing destruction and creation", cameraMove: "slow-tracking", lens: "85mm", lighting: "lava-close", durationSec: 5, skills: ["skill-vfx-fire"] },
      { shotType: "wide", description: "Lava meeting the ocean", prompt: "Wide shot of lava flowing into the ocean, massive steam clouds erupting on contact, the battle between fire and water, new land being born", cameraMove: "slow-pan", lens: "35mm", lighting: "lava-steam", durationSec: 4, skills: ["skill-landscape-grading"] },
      { shotType: "aerial", description: "Ash plume from above", prompt: "Aerial shot of the volcanic ash plume rising miles into the sky, lightning flashing within the cloud, the scale of geological force made visible", cameraMove: "orbit", lens: "24mm", lighting: "volcanic-lightning", durationSec: 4, skills: [] },
      { shotType: "medium", description: "Lava rocks exploding upward", prompt: "Medium shot of volcanic bombs being hurled from the crater, molten rocks arcing through the air trailing sparks, explosive energy, nature's fireworks", cameraMove: "tracking-up", lens: "50mm", lighting: "explosive-lava", durationSec: 4, skills: ["skill-vfx-fire", "skill-landscape-grading"] },
    ]}],
  },
];
