import type { CinematicTemplate } from "../types.js";

export const filmTemplates: CinematicTemplate[] = [
  {
    id: "film-noir-detective",
    name: "Noir Detective Opening",
    category: "film",
    description: "Classic film noir detective introduction with rain-soaked streets and dramatic shadows.",
    tags: ["noir", "detective", "rain", "night", "moody"],
    estimatedDuration: 28,
    difficulty: "intermediate",
    recommendedSkills: ["skill-cinematic-lighting", "skill-rain-effects"],
    scenes: [
      {
        title: "Rain-Soaked City",
        description: "A detective walks through rain-soaked streets at night.",
        location: "City street",
        timeOfDay: "night",
        mood: "mysterious",
        shots: [
          { shotType: "establishing", description: "Neon signs reflect off wet asphalt in an empty city street", prompt: "Wide establishing shot of a rain-soaked 1940s city street at night, neon signs reflecting off wet asphalt, fog rolling through, film noir aesthetic, high contrast black and white with neon color accents", cameraMove: "slow-dolly-forward", lens: "35mm", lighting: "neon-noir", durationSec: 6, skills: ["skill-cinematic-lighting"] },
          { shotType: "medium", description: "A trenchcoated figure emerges from shadow", prompt: "Medium shot of a detective in a trenchcoat and fedora emerging from shadow into neon light, rain falling, cigarette smoke curling upward, film noir lighting", cameraMove: "static", lens: "50mm", lighting: "high-contrast-side", durationSec: 5, skills: [] },
          { shotType: "close", description: "Detective's face lit by match flame", prompt: "Close-up of a weathered detective's face illuminated by a match flame, rain dripping from fedora brim, eyes narrowed with determination, dramatic chiaroscuro lighting", cameraMove: "slow-push", lens: "85mm", lighting: "match-light", durationSec: 4, skills: [] },
          { shotType: "pov", description: "Detective's view of a dimly lit doorway", prompt: "POV shot looking at a dimly lit doorway at the end of a rain-soaked alley, a single bare bulb swinging above, mysterious figure silhouetted inside", cameraMove: "handheld-walk", lens: "35mm", lighting: "practical-bulb", durationSec: 5, skills: [] },
          { shotType: "wide", description: "Detective walks toward the doorway", prompt: "Wide shot from behind as the detective walks down the wet alley toward the glowing doorway, rain creating halos around streetlights, long shadow stretching ahead", cameraMove: "follow", lens: "24mm", lighting: "backlit-rain", durationSec: 4, skills: ["skill-rain-effects"] },
          { shotType: "close", description: "Hand reaches for door handle", prompt: "Close-up of a gloved hand reaching for a tarnished brass door handle, rain droplets on leather, tension in the grip", cameraMove: "static", lens: "100mm", lighting: "dramatic-side", durationSec: 4, skills: [] },
        ],
      },
    ],
  },
  {
    id: "film-horror-cabin",
    name: "Horror Cabin Arrival",
    category: "film",
    description: "Group arrives at an isolated cabin in the woods. Classic horror setup.",
    tags: ["horror", "cabin", "woods", "isolation", "dread"],
    estimatedDuration: 32,
    difficulty: "intermediate",
    recommendedSkills: ["skill-atmospheric-fog", "skill-horror-grading"],
    scenes: [
      {
        title: "Approach Through the Woods",
        description: "A car drives through dense dark woods toward a remote cabin.",
        location: "Forest road",
        timeOfDay: "dusk",
        mood: "dread",
        shots: [
          { shotType: "aerial", description: "Aerial view of car on isolated forest road", prompt: "Aerial drone shot looking down at a lone car driving on a narrow dirt road through dense dark forest at dusk, fog weaving between trees, isolation and dread", cameraMove: "tracking-overhead", lens: "24mm", lighting: "fading-daylight", durationSec: 6, skills: ["skill-atmospheric-fog"] },
          { shotType: "medium", description: "Passengers inside the car looking uneasy", prompt: "Medium shot inside a car of young people looking through foggy windows at the dark forest around them, dashboard light on their faces, unease in their expressions", cameraMove: "handheld-subtle", lens: "35mm", lighting: "dashboard-glow", durationSec: 5, skills: [] },
          { shotType: "wide", description: "Car headlights illuminate the cabin", prompt: "Wide shot as car headlights sweep across a decrepit wooden cabin at the edge of a clearing, dead trees surrounding it, one window faintly glowing", cameraMove: "static", lens: "35mm", lighting: "headlights-only", durationSec: 5, skills: ["skill-horror-grading"] },
          { shotType: "close", description: "Car engine turns off, silence", prompt: "Close-up of hand turning car key, engine dying, sudden silence except for wind through trees, the cabin visible through windshield", cameraMove: "static", lens: "85mm", lighting: "dim-interior", durationSec: 4, skills: [] },
          { shotType: "establishing", description: "The cabin stands alone in the clearing", prompt: "Low angle establishing shot of the cabin against a dark purple sky, bare branches reaching like fingers, a single dim light in the window, fog creeping along the ground", cameraMove: "slow-tilt-up", lens: "24mm", lighting: "twilight-horror", durationSec: 6, skills: ["skill-atmospheric-fog"] },
          { shotType: "pov", description: "Looking at the cabin door from the car", prompt: "POV shot from car window looking at the cabin's weathered front door, paint peeling, rusted hinges, the doorknob catches a glint of fading light", cameraMove: "static", lens: "50mm", lighting: "natural-dusk", durationSec: 3, skills: [] },
          { shotType: "medium", description: "First person steps out of car", prompt: "Medium shot of a person stepping out of the car, breath visible in cold air, looking up at the cabin with a flashlight, beam cutting through gathering fog", cameraMove: "slight-pan", lens: "35mm", lighting: "flashlight-beam", durationSec: 3, skills: [] },
        ],
      },
    ],
  },
  {
    id: "film-scifi-discovery",
    name: "Sci-Fi Discovery Scene",
    category: "film",
    description: "Astronaut discovers an alien artifact on a distant planet.",
    tags: ["sci-fi", "space", "discovery", "alien", "wonder"],
    estimatedDuration: 30,
    difficulty: "advanced",
    recommendedSkills: ["skill-sci-fi-vfx", "skill-cinematic-lighting"],
    scenes: [
      {
        title: "The Artifact",
        description: "An astronaut finds a mysterious alien structure on a barren planet.",
        location: "Alien planet surface",
        timeOfDay: "perpetual-twilight",
        mood: "awe",
        shots: [
          { shotType: "establishing", description: "Vast alien landscape with distant mountains", prompt: "Sweeping establishing shot of an alien planet surface, ochre-colored terrain stretching to jagged crystal mountains on the horizon, two moons visible in a purple sky, atmospheric haze", cameraMove: "slow-pan-right", lens: "16mm", lighting: "alien-twilight", durationSec: 6, skills: ["skill-sci-fi-vfx"] },
          { shotType: "wide", description: "Lone astronaut walking across the terrain", prompt: "Wide shot of a lone astronaut in a white spacesuit walking across barren alien terrain, footprints in alien dust, small figure against the vast landscape", cameraMove: "tracking-side", lens: "35mm", lighting: "double-moon-light", durationSec: 5, skills: [] },
          { shotType: "medium", description: "Astronaut notices something on the horizon", prompt: "Medium shot of astronaut stopping, helmet turning toward something off-screen, visor reflecting a strange glow, body language showing curiosity", cameraMove: "static", lens: "50mm", lighting: "reflected-glow", durationSec: 4, skills: [] },
          { shotType: "over-shoulder", description: "Astronaut's view of the glowing artifact", prompt: "Over-shoulder shot past the astronaut's helmet revealing a massive geometric alien artifact hovering above the ground, emitting soft pulsing light, geometric patterns etched into its surface", cameraMove: "slow-push", lens: "35mm", lighting: "artifact-glow", durationSec: 5, skills: ["skill-sci-fi-vfx"] },
          { shotType: "extreme-close", description: "Gloved hand reaching toward the artifact", prompt: "Extreme close-up of a spacesuit gloved hand slowly reaching toward the alien artifact, energy tendrils reaching back toward the fingertips, light dancing between them", cameraMove: "static", lens: "100mm", lighting: "energy-glow", durationSec: 5, skills: ["skill-sci-fi-vfx"] },
          { shotType: "wide", description: "The artifact activates", prompt: "Wide shot as the artifact suddenly activates, geometric panels unfolding, beams of light shooting upward, the astronaut stumbling back, the entire landscape bathed in otherworldly glow", cameraMove: "quick-zoom-out", lens: "24mm", lighting: "activation-burst", durationSec: 5, skills: ["skill-sci-fi-vfx", "skill-cinematic-lighting"] },
        ],
      },
    ],
  },
  {
    id: "film-romance-reunion",
    name: "Romantic Reunion",
    category: "film",
    description: "Two lovers reunite at a train station after a long separation.",
    tags: ["romance", "reunion", "train-station", "emotional", "golden-hour"],
    estimatedDuration: 26,
    difficulty: "intermediate",
    recommendedSkills: ["skill-cinematic-lighting", "skill-bokeh"],
    scenes: [
      {
        title: "The Reunion",
        description: "A woman waits at a train station. The train arrives. They find each other.",
        location: "Train station",
        timeOfDay: "golden-hour",
        mood: "longing, joy",
        shots: [
          { shotType: "establishing", description: "Grand train station in golden light", prompt: "Establishing shot of a beautiful vintage train station bathed in golden hour light, steam drifting across the platform, warm amber tones, cinematic anamorphic flare", cameraMove: "slow-dolly-forward", lens: "35mm", lighting: "golden-hour", durationSec: 5, skills: ["skill-cinematic-lighting"] },
          { shotType: "medium", description: "Woman waiting on the platform", prompt: "Medium shot of a woman standing alone on a train platform, clutching a scarf, eyes searching the distance, golden light wrapping around her, shallow depth of field", cameraMove: "static", lens: "85mm", lighting: "golden-backlit", durationSec: 5, skills: ["skill-bokeh"] },
          { shotType: "wide", description: "Train arriving at the station", prompt: "Wide shot of a vintage train pulling into the station, steam billowing, passengers beginning to emerge, the woman's silhouette against the golden light", cameraMove: "slight-pan", lens: "50mm", lighting: "golden-hour", durationSec: 4, skills: [] },
          { shotType: "close", description: "Her eyes light up with recognition", prompt: "Close-up of the woman's face as her eyes light up with recognition, tears forming, a smile breaking through, golden light catching the moisture in her eyes", cameraMove: "static", lens: "85mm", lighting: "soft-golden", durationSec: 4, skills: ["skill-bokeh"] },
          { shotType: "medium", description: "Running toward each other", prompt: "Medium tracking shot as two people run toward each other through the steam on the platform, other passengers parting, golden light filtering through, slow motion feel", cameraMove: "tracking-forward", lens: "50mm", lighting: "golden-backlit", durationSec: 4, skills: [] },
          { shotType: "close", description: "The embrace", prompt: "Close-up of two people embracing tightly on the train platform, foreheads touching, eyes closed, steam swirling around them, golden light creating a halo effect", cameraMove: "slow-orbit", lens: "85mm", lighting: "golden-rim", durationSec: 4, skills: ["skill-cinematic-lighting", "skill-bokeh"] },
        ],
      },
    ],
  },
  {
    id: "film-western-standoff",
    name: "Western Standoff",
    category: "film",
    description: "Classic western standoff in a dusty frontier town.",
    tags: ["western", "standoff", "desert", "tension", "noon"],
    estimatedDuration: 28,
    difficulty: "intermediate",
    recommendedSkills: ["skill-cinematic-lighting"],
    scenes: [
      {
        title: "High Noon",
        description: "Two gunslingers face off in an empty frontier street.",
        location: "Frontier town",
        timeOfDay: "noon",
        mood: "tension",
        shots: [
          { shotType: "establishing", description: "Empty frontier town street", prompt: "Wide establishing shot of an empty dusty frontier town street at high noon, saloon doors swaying, tumbleweeds rolling, heat shimmer rising from the dirt road", cameraMove: "slow-push", lens: "24mm", lighting: "harsh-noon-sun", durationSec: 5, skills: [] },
          { shotType: "extreme-close", description: "Eyes squinting against the sun", prompt: "Extreme close-up of a gunslinger's eyes squinting against the harsh noon sun, dust on weathered skin, sweat beading, intense determination", cameraMove: "static", lens: "100mm", lighting: "harsh-overhead", durationSec: 4, skills: [] },
          { shotType: "close", description: "Hand hovering over holster", prompt: "Close-up of a hand hovering over a worn leather holster, fingers twitching slightly, dust motes floating in a beam of sunlight", cameraMove: "static", lens: "85mm", lighting: "harsh-noon", durationSec: 4, skills: [] },
          { shotType: "wide", description: "Both gunslingers from the side", prompt: "Wide shot from the side showing both gunslingers facing each other across the dusty street, long shadows despite the noon sun, buildings framing the scene", cameraMove: "static", lens: "35mm", lighting: "noon-western", durationSec: 5, skills: ["skill-cinematic-lighting"] },
          { shotType: "extreme-close", description: "Boot shifts in the dust", prompt: "Extreme close-up of a boot shifting in the dust, spurs glinting in the sun, tension in the movement, dust particles rising", cameraMove: "static", lens: "100mm", lighting: "ground-level-sun", durationSec: 3, skills: [] },
          { shotType: "medium", description: "Quick draw moment", prompt: "Medium shot fast zoom capturing the draw, hand a blur reaching for the revolver, coat flaring outward, dust kicked up by sudden movement", cameraMove: "quick-zoom", lens: "50mm", lighting: "harsh-noon", durationSec: 3, skills: [] },
          { shotType: "wide", description: "Aftermath in the dusty street", prompt: "Wide shot of the aftermath, one figure standing, smoke curling from a revolver barrel, the empty street settling back to silence, dust slowly falling", cameraMove: "static", lens: "35mm", lighting: "noon-settling", durationSec: 4, skills: [] },
        ],
      },
    ],
  },
  {
    id: "film-heist-planning",
    name: "Heist Planning Montage",
    category: "film",
    description: "A crew plans a daring heist. Maps, blueprints, and tense discussion.",
    tags: ["heist", "planning", "thriller", "team", "montage"],
    estimatedDuration: 24,
    difficulty: "intermediate",
    recommendedSkills: ["skill-cinematic-lighting"],
    scenes: [
      {
        title: "The Plan",
        description: "The heist crew gathers to plan the operation.",
        location: "Warehouse hideout",
        timeOfDay: "night",
        mood: "tension, focus",
        shots: [
          { shotType: "establishing", description: "Dark warehouse with single overhead light", prompt: "Establishing shot of a dark warehouse interior, single industrial light hanging over a large table covered in blueprints, figures gathered in shadow", cameraMove: "slow-descend", lens: "24mm", lighting: "single-overhead", durationSec: 5, skills: ["skill-cinematic-lighting"] },
          { shotType: "close", description: "Finger tracing a route on a blueprint", prompt: "Close-up of a finger tracing a route on an architectural blueprint, red ink marking entry points, coffee stain on the corner, dramatic side lighting", cameraMove: "slow-pan", lens: "50mm", lighting: "practical-lamp", durationSec: 4, skills: [] },
          { shotType: "medium", description: "Team leader explaining the plan", prompt: "Medium shot of a confident team leader standing at the head of the table, gesturing at the blueprints, crew members in silhouette listening intently", cameraMove: "static", lens: "50mm", lighting: "overhead-dramatic", durationSec: 4, skills: [] },
          { shotType: "close", description: "Skeptical face in shadow", prompt: "Close-up of a crew member's skeptical face half in shadow, doubt in their eyes, cigarette smoke drifting, considering the risks", cameraMove: "static", lens: "85mm", lighting: "half-shadow", durationSec: 3, skills: [] },
          { shotType: "extreme-close", description: "Timer being set", prompt: "Extreme close-up of hands setting a precision timer, digital numbers glowing red, reflecting off the operator's glasses, meticulous focus", cameraMove: "static", lens: "100mm", lighting: "timer-glow", durationSec: 4, skills: [] },
          { shotType: "wide", description: "Crew all puts hands in", prompt: "Wide shot from above as the crew places their hands together over the blueprint, commitment to the plan, faces lit by the overhead lamp, a moment of unity", cameraMove: "overhead", lens: "24mm", lighting: "overhead-warm", durationSec: 4, skills: [] },
        ],
      },
    ],
  },
  {
    id: "film-war-letter",
    name: "Soldier's Letter Home",
    category: "film",
    description: "A soldier writes a letter home by candlelight in a WW2 bunker.",
    tags: ["war", "letter", "emotional", "bunker", "candlelight"],
    estimatedDuration: 22,
    difficulty: "intermediate",
    recommendedSkills: ["skill-cinematic-lighting", "skill-period-grading"],
    scenes: [
      {
        title: "The Letter",
        description: "A soldier writes by candlelight in a bunker.",
        location: "WW2 bunker",
        timeOfDay: "night",
        mood: "melancholy, hope",
        shots: [
          { shotType: "establishing", description: "Bunker interior lit by candle", prompt: "Establishing shot of a WW2 bunker interior, sandbag walls, a single candle flickering on a makeshift desk, a soldier hunched over writing, warm candlelight against cold concrete", cameraMove: "slow-push", lens: "35mm", lighting: "candlelight", durationSec: 5, skills: ["skill-cinematic-lighting"] },
          { shotType: "extreme-close", description: "Pen scratching on paper", prompt: "Extreme close-up of a pen scratching across yellowed paper, handwritten words in cursive, ink glistening in candlelight, slight tremor in the hand", cameraMove: "static", lens: "100mm", lighting: "warm-candle", durationSec: 4, skills: [] },
          { shotType: "close", description: "Soldier's face in candlelight", prompt: "Close-up of the soldier's young face illuminated by warm candlelight, eyes glistening with emotion, a faint hopeful smile, dirt and exhaustion visible", cameraMove: "static", lens: "85mm", lighting: "candlelight-portrait", durationSec: 4, skills: ["skill-period-grading"] },
          { shotType: "close", description: "Photograph of loved ones", prompt: "Close-up of a worn photograph of a woman and child held in the soldier's other hand, edges frayed, candlelight dancing across the image, thumb gently touching it", cameraMove: "static", lens: "85mm", lighting: "candle-warm", durationSec: 4, skills: [] },
          { shotType: "medium", description: "Soldier folds the letter", prompt: "Medium shot of the soldier carefully folding the letter, placing it in an envelope, sealing it with a kiss, candle flame reflecting in tearful eyes", cameraMove: "static", lens: "50mm", lighting: "candlelight", durationSec: 5, skills: [] },
        ],
      },
    ],
  },
  {
    id: "film-chase-rooftops",
    name: "Rooftop Chase",
    category: "film",
    description: "Intense parkour chase across city rooftops at dawn.",
    tags: ["action", "chase", "rooftops", "parkour", "dawn"],
    estimatedDuration: 24,
    difficulty: "advanced",
    recommendedSkills: ["skill-action-camera", "skill-slow-motion"],
    scenes: [
      {
        title: "Rooftop Pursuit",
        description: "A protagonist is chased across rooftops at dawn.",
        location: "City rooftops",
        timeOfDay: "dawn",
        mood: "urgency, adrenaline",
        shots: [
          { shotType: "aerial", description: "Dawn over city rooftops", prompt: "Aerial shot at dawn showing city rooftops stretching to the horizon, golden light just cresting buildings, a figure running across a rooftop far below", cameraMove: "tracking-overhead", lens: "24mm", lighting: "dawn-golden", durationSec: 4, skills: [] },
          { shotType: "medium", description: "Runner leaping between buildings", prompt: "Medium tracking shot of a runner leaping across a gap between buildings, silhouetted against the dawn sky, body fully extended mid-air, city lights below", cameraMove: "tracking-side", lens: "35mm", lighting: "dawn-silhouette", durationSec: 4, skills: ["skill-action-camera"] },
          { shotType: "close", description: "Feet landing on rooftop", prompt: "Close-up of feet landing hard on gravel rooftop, impact sending debris flying, immediately breaking into a sprint, dawn light catching the dust", cameraMove: "ground-level-track", lens: "35mm", lighting: "low-dawn", durationSec: 3, skills: ["skill-slow-motion"] },
          { shotType: "pov", description: "Runner's POV approaching edge", prompt: "POV shot running toward the edge of a building, city stretching out below, the next rooftop approaching fast, wind rushing, vertiginous height", cameraMove: "handheld-run", lens: "16mm", lighting: "dawn-dramatic", durationSec: 4, skills: ["skill-action-camera"] },
          { shotType: "wide", description: "Pursuer gaining ground", prompt: "Wide shot showing both runner and pursuer on different rooftops, the gap between them closing, dawn creating long dramatic shadows across the rooftops", cameraMove: "pan-follow", lens: "50mm", lighting: "dawn-shadows", durationSec: 4, skills: [] },
          { shotType: "medium", description: "Sliding under pipes", prompt: "Medium shot as the runner slides under industrial pipes on a rooftop, sparks from a metal surface, immediately rolling back to feet and continuing, parkour grace", cameraMove: "tracking-low", lens: "35mm", lighting: "dawn-industrial", durationSec: 5, skills: ["skill-action-camera", "skill-slow-motion"] },
        ],
      },
    ],
  },
  {
    id: "film-courtroom-verdict",
    name: "Courtroom Verdict",
    category: "film",
    description: "Tense courtroom scene as the verdict is delivered.",
    tags: ["drama", "courtroom", "verdict", "tension", "legal"],
    estimatedDuration: 20,
    difficulty: "beginner",
    recommendedSkills: ["skill-cinematic-lighting"],
    scenes: [
      {
        title: "The Verdict",
        description: "The jury foreman reads the verdict in a packed courtroom.",
        location: "Courtroom",
        timeOfDay: "day",
        mood: "tension, gravity",
        shots: [
          { shotType: "establishing", description: "Grand courtroom interior", prompt: "Establishing shot of a grand wood-paneled courtroom, tall windows casting long light beams through dust, packed gallery, the judge at the bench", cameraMove: "slow-dolly-forward", lens: "24mm", lighting: "window-beams", durationSec: 5, skills: ["skill-cinematic-lighting"] },
          { shotType: "medium", description: "Jury foreman standing", prompt: "Medium shot of the jury foreman standing nervously, holding a folded piece of paper, the other jurors watching, courtroom silent", cameraMove: "static", lens: "50mm", lighting: "courtroom-overhead", durationSec: 4, skills: [] },
          { shotType: "close", description: "Defendant waiting", prompt: "Close-up of the defendant's face as they wait for the verdict, jaw clenched, eyes forward, sweat visible on the brow, knuckles white on the table", cameraMove: "slow-push", lens: "85mm", lighting: "side-window", durationSec: 4, skills: [] },
          { shotType: "close", description: "The paper unfolds", prompt: "Close-up of hands unfolding the verdict paper, the courtroom holding its collective breath, the words barely visible", cameraMove: "static", lens: "100mm", lighting: "overhead-practical", durationSec: 3, skills: [] },
          { shotType: "medium", description: "Reaction shot", prompt: "Medium shot capturing the defendant's reaction as the verdict is read, defense attorney placing a hand on their shoulder, emotion breaking through", cameraMove: "static", lens: "50mm", lighting: "courtroom-natural", durationSec: 4, skills: [] },
        ],
      },
    ],
  },
  {
    id: "film-underwater-dream",
    name: "Underwater Dream Sequence",
    category: "film",
    description: "Surreal underwater dream sequence with floating objects and distorted reality.",
    tags: ["dream", "underwater", "surreal", "ethereal", "subconscious"],
    estimatedDuration: 24,
    difficulty: "advanced",
    recommendedSkills: ["skill-underwater-vfx", "skill-dream-grading"],
    scenes: [
      {
        title: "The Submerged Dream",
        description: "A dreamer sinks into a surreal underwater world.",
        location: "Underwater dreamscape",
        timeOfDay: "timeless",
        mood: "ethereal, disorienting",
        shots: [
          { shotType: "wide", description: "Figure sinking through blue water", prompt: "Wide shot of a person in flowing clothes slowly sinking through deep blue water, hair floating upward, light filtering from above in god rays, peaceful descent", cameraMove: "slow-descend", lens: "35mm", lighting: "underwater-godrays", durationSec: 5, skills: ["skill-underwater-vfx"] },
          { shotType: "medium", description: "Furniture floating in water", prompt: "Medium shot of living room furniture suspended in deep blue water, a chair slowly rotating, photographs drifting past, surreal underwater domestic scene", cameraMove: "slow-orbit", lens: "35mm", lighting: "diffused-blue", durationSec: 5, skills: ["skill-dream-grading"] },
          { shotType: "close", description: "Dreamer's serene face underwater", prompt: "Close-up of the dreamer's face underwater, eyes open but peaceful, bubbles slowly rising from slightly parted lips, hair creating a halo, bioluminescent particles floating past", cameraMove: "static", lens: "85mm", lighting: "bioluminescent", durationSec: 4, skills: ["skill-underwater-vfx"] },
          { shotType: "extreme-close", description: "Hand reaching for floating object", prompt: "Extreme close-up of a hand reaching for a floating pocket watch suspended in water, the watch ticking backwards, reflections dancing on the glass face", cameraMove: "slow-push", lens: "100mm", lighting: "diffused-aqua", durationSec: 5, skills: ["skill-dream-grading"] },
          { shotType: "wide", description: "Light breaking through the surface", prompt: "Wide shot looking up from below as the dreamer floats upward toward the surface, light breaking through in brilliant rays, transformation from blue to golden warmth", cameraMove: "tilt-up", lens: "16mm", lighting: "ascending-light", durationSec: 5, skills: ["skill-underwater-vfx", "skill-dream-grading"] },
        ],
      },
    ],
  },
];
