import type { CinematicTemplate } from "../types.js";

export const filmExtendedTemplates: CinematicTemplate[] = [
  {
    id: "film-time-travel",
    name: "Time Travel Paradox",
    category: "film",
    description: "Mind-bending time travel sequence with temporal distortion effects.",
    tags: ["sci-fi", "time-travel", "paradox", "distortion", "cerebral"],
    estimatedDuration: 26,
    difficulty: "advanced",
    recommendedSkills: ["skill-vfx-temporal", "skill-dream-grading"],
    scenes: [{ title: "The Jump", description: "A traveler jumps through time.", location: "Laboratory / multiple eras", timeOfDay: "various", mood: "disorientation, wonder", shots: [
      { shotType: "medium", description: "Activating the time device", prompt: "Medium shot of a scientist activating a makeshift time device, sparks flying, dials spinning, desperation in their eyes as the machine hums to life", cameraMove: "handheld-tense", lens: "35mm", lighting: "sparking-device", durationSec: 4, skills: [] },
      { shotType: "close", description: "Reality begins to fracture", prompt: "Close-up of the air itself seeming to fracture like glass, cracks of brilliant light appearing, the fabric of time tearing open before the traveler's face", cameraMove: "static", lens: "85mm", lighting: "temporal-fracture", durationSec: 4, skills: ["skill-vfx-temporal"] },
      { shotType: "wide", description: "Falling through time vortex", prompt: "Wide shot of the traveler falling through a spiraling vortex of time, glimpses of different eras flashing past, ancient civilizations and far futures, overwhelming", cameraMove: "spinning-descent", lens: "16mm", lighting: "vortex-multicolor", durationSec: 5, skills: ["skill-vfx-temporal", "skill-dream-grading"] },
      { shotType: "medium", description: "Landing in a different era", prompt: "Medium shot of the traveler crashing onto the ground in a completely different era, disoriented, looking around at a world they don't recognize", cameraMove: "handheld-disoriented", lens: "35mm", lighting: "era-specific", durationSec: 4, skills: [] },
      { shotType: "close", description: "Seeing themselves in the past", prompt: "Close-up reaction shot as the traveler sees a younger version of themselves across the street, the horror and wonder of temporal paradox, frozen in place", cameraMove: "slow-push", lens: "85mm", lighting: "paradox-glow", durationSec: 4, skills: ["skill-dream-grading"] },
      { shotType: "wide", description: "Two timelines colliding", prompt: "Wide shot as two versions of reality begin to overlap, ghostly images of both timelines visible simultaneously, buildings from two eras occupying the same space", cameraMove: "slow-orbit", lens: "24mm", lighting: "dual-timeline", durationSec: 5, skills: ["skill-vfx-temporal"] },
    ]}],
  },
  {
    id: "film-prison-escape",
    name: "Prison Escape",
    category: "film",
    description: "Tense prison break sequence with claustrophobic tunnel crawl.",
    tags: ["prison", "escape", "tension", "claustrophobia", "thriller"],
    estimatedDuration: 24,
    difficulty: "intermediate",
    recommendedSkills: ["skill-cinematic-lighting"],
    scenes: [{ title: "The Tunnel", description: "Inmates make their desperate escape through a narrow tunnel.", location: "Prison / underground tunnel", timeOfDay: "night", mood: "claustrophobia, desperation", shots: [
      { shotType: "close", description: "Hands scraping at concrete", prompt: "Close-up of bloodied hands scraping the last layer of concrete from a hidden tunnel entrance in a prison cell, decades of patient work about to pay off", cameraMove: "static", lens: "85mm", lighting: "cell-dim", durationSec: 4, skills: [] },
      { shotType: "pov", description: "Crawling through tight tunnel", prompt: "POV shot crawling through an impossibly tight tunnel, rough earth walls inches from the face, a small flashlight barely cutting the darkness, suffocating", cameraMove: "handheld-crawl", lens: "16mm", lighting: "flashlight-tunnel", durationSec: 5, skills: ["skill-cinematic-lighting"] },
      { shotType: "close", description: "Fear in the inmate's eyes", prompt: "Close-up of an inmate's terrified face in the tunnel, dirt smeared, sweat dripping, the sound of distant alarms beginning to wail, time running out", cameraMove: "static", lens: "85mm", lighting: "flashlight-face", durationSec: 3, skills: [] },
      { shotType: "medium", description: "Tunnel partially collapses", prompt: "Medium shot inside the tunnel as dirt and rocks begin falling, the tunnel partially collapsing, the inmate pushing forward in panic through falling debris", cameraMove: "shaky-forward", lens: "24mm", lighting: "dust-flashlight", durationSec: 4, skills: [] },
      { shotType: "wide", description: "Breaking through to the surface", prompt: "Wide shot from outside as hands break through earth into open air, an inmate pulling themselves out under a starlit sky, the first breath of freedom", cameraMove: "static", lens: "35mm", lighting: "moonlight-freedom", durationSec: 4, skills: ["skill-cinematic-lighting"] },
      { shotType: "wide", description: "Running through the forest", prompt: "Wide shot of the escapee sprinting through a dark forest, searchlights from the prison sweeping through trees behind them, dogs barking in the distance", cameraMove: "tracking-behind", lens: "24mm", lighting: "searchlight-sweep", durationSec: 4, skills: [] },
    ]}],
  },
  {
    id: "film-dance-sequence",
    name: "Ballroom Dance Sequence",
    category: "film",
    description: "Elegant ballroom dance scene with flowing gowns and orchestral music.",
    tags: ["dance", "ballroom", "elegant", "romance", "period"],
    estimatedDuration: 22,
    difficulty: "intermediate",
    recommendedSkills: ["skill-cinematic-lighting", "skill-slow-motion"],
    scenes: [{ title: "The Waltz", description: "Two lovers share a mesmerizing dance.", location: "Grand ballroom", timeOfDay: "evening", mood: "romance, elegance", shots: [
      { shotType: "establishing", description: "Grand ballroom in full splendor", prompt: "Establishing shot of a grand ballroom with crystal chandeliers, gilded columns, couples dancing in formal attire, a string orchestra playing, old-world elegance", cameraMove: "crane-down", lens: "16mm", lighting: "chandelier-warm", durationSec: 5, skills: ["skill-cinematic-lighting"] },
      { shotType: "wide", description: "Couple beginning to dance", prompt: "Wide shot as two people find each other across the crowded ballroom, the crowd parting, hands meeting, the first steps of a waltz, magnetic connection", cameraMove: "slow-push", lens: "35mm", lighting: "ballroom-golden", durationSec: 4, skills: [] },
      { shotType: "medium", description: "Spinning in perfect sync", prompt: "Medium shot of the couple spinning in perfect synchronization, her gown flowing like water, his hand guiding with confidence, lost in each other", cameraMove: "orbit-with", lens: "50mm", lighting: "romantic-warm", durationSec: 5, skills: [] },
      { shotType: "close", description: "Eyes locked together", prompt: "Close-up alternating between their faces, eyes locked, small smiles, the rest of the room blurring away, only they exist in this moment", cameraMove: "slow-drift", lens: "85mm", lighting: "soft-key-warm", durationSec: 4, skills: [] },
      { shotType: "wide", description: "Other dancers stop to watch", prompt: "Wide shot as other dancers gradually stop to watch the couple, forming a circle around them, captivated by the chemistry, the dance becoming performance", cameraMove: "slow-pull-back", lens: "24mm", lighting: "spotlight-couple", durationSec: 4, skills: ["skill-cinematic-lighting"] },
    ]}],
  },
  {
    id: "film-apocalypse-survivor",
    name: "Post-Apocalyptic Survivor",
    category: "film",
    description: "Lone survivor navigating a devastated world after civilization's fall.",
    tags: ["apocalypse", "survivor", "desolation", "lone", "gritty"],
    estimatedDuration: 24,
    difficulty: "intermediate",
    recommendedSkills: ["skill-landscape-grading"],
    scenes: [{ title: "After the End", description: "A survivor moves through the ruins of civilization.", location: "Destroyed city", timeOfDay: "overcast", mood: "desolation, resilience", shots: [
      { shotType: "aerial", description: "Devastated cityscape", prompt: "Aerial shot of a devastated cityscape, crumbling skyscrapers, overgrown roads, abandoned vehicles rusting, nature reclaiming what humans built, eerie silence", cameraMove: "slow-forward", lens: "24mm", lighting: "overcast-grey", durationSec: 5, skills: ["skill-landscape-grading"] },
      { shotType: "wide", description: "Lone figure walking through ruins", prompt: "Wide shot of a lone figure walking down the center of a destroyed highway, makeshift pack on back, weapon at the ready, small against the destruction", cameraMove: "static", lens: "35mm", lighting: "overcast-muted", durationSec: 4, skills: [] },
      { shotType: "medium", description: "Scavenging in abandoned store", prompt: "Medium shot of the survivor carefully searching through an abandoned store, checking shelves for food, flashlight beam cutting through dusty air", cameraMove: "handheld-follow", lens: "35mm", lighting: "flashlight-interior", durationSec: 4, skills: [] },
      { shotType: "close", description: "Finding a precious resource", prompt: "Close-up of the survivor's hands finding a sealed water bottle among debris, the relief visible in their grip, a small victory in a harsh world", cameraMove: "static", lens: "85mm", lighting: "dim-interior", durationSec: 3, skills: [] },
      { shotType: "wide", description: "Campfire in a ruined building", prompt: "Wide shot of the survivor huddled by a small campfire in the shell of a ruined building, stars visible through the collapsed roof, alone but enduring", cameraMove: "slow-pull-back", lens: "24mm", lighting: "firelight-stars", durationSec: 4, skills: ["skill-landscape-grading"] },
      { shotType: "close", description: "Eyes staring at a faded photo", prompt: "Close-up of the survivor staring at a creased faded photograph by firelight, a family from before, the reason to keep going, moisture in their eyes", cameraMove: "static", lens: "85mm", lighting: "fire-intimate", durationSec: 4, skills: [] },
    ]}],
  },
  {
    id: "film-spy-thriller",
    name: "Spy Infiltration",
    category: "film",
    description: "Tense spy infiltration sequence with disguise and high-tech gadgets.",
    tags: ["spy", "infiltration", "thriller", "tech", "stealth"],
    estimatedDuration: 26,
    difficulty: "advanced",
    recommendedSkills: ["skill-cinematic-lighting", "skill-action-camera"],
    scenes: [{ title: "The Infiltration", description: "An agent infiltrates a high-security facility.", location: "High-security complex", timeOfDay: "night", mood: "tension, precision", shots: [
      { shotType: "establishing", description: "High-security building at night", prompt: "Establishing shot of a heavily guarded modern building at night, searchlights sweeping, security cameras visible, a fortress of secrets", cameraMove: "slow-push", lens: "24mm", lighting: "security-cold", durationSec: 4, skills: ["skill-cinematic-lighting"] },
      { shotType: "close", description: "Agent adjusting disguise", prompt: "Close-up of the agent adjusting a disguise in a car mirror, contact lenses changing eye color, subtle prosthetics, becoming someone else entirely", cameraMove: "static", lens: "85mm", lighting: "dashboard-dim", durationSec: 3, skills: [] },
      { shotType: "medium", description: "Walking past security checkpoint", prompt: "Medium shot of the agent walking calmly through a security checkpoint, fake ID scanned, heart rate steady despite the danger, acting the part perfectly", cameraMove: "tracking-side", lens: "50mm", lighting: "fluorescent-cold", durationSec: 4, skills: [] },
      { shotType: "close", description: "Hacking a security panel", prompt: "Close-up of gloved fingers rapidly working a security panel, code scrolling, bypassing layer after layer of encryption, each second critical", cameraMove: "static", lens: "85mm", lighting: "screen-glow", durationSec: 4, skills: ["skill-action-camera"] },
      { shotType: "medium", description: "Navigating laser grid", prompt: "Medium shot of the agent carefully navigating through a laser security grid, body contorting with gymnastic precision, red beams inches from skin", cameraMove: "slow-pan", lens: "35mm", lighting: "laser-red", durationSec: 5, skills: ["skill-cinematic-lighting"] },
      { shotType: "close", description: "Extracting the data", prompt: "Close-up of a device downloading classified data, progress bar filling, footsteps approaching in the corridor outside, the tension unbearable", cameraMove: "static", lens: "85mm", lighting: "screen-blue", durationSec: 4, skills: ["skill-action-camera"] },
      { shotType: "medium", description: "Narrow escape through window", prompt: "Medium shot of the agent making a narrow escape through a window as alarms trigger, rappelling down the building exterior, mission accomplished", cameraMove: "tracking-down", lens: "35mm", lighting: "alarm-red", durationSec: 3, skills: [] },
    ]}],
  },
  {
    id: "film-samurai-duel",
    name: "Samurai Showdown",
    category: "film",
    description: "Stylized samurai duel in a rain-soaked bamboo forest.",
    tags: ["samurai", "duel", "martial-arts", "rain", "honor"],
    estimatedDuration: 22,
    difficulty: "advanced",
    recommendedSkills: ["skill-slow-motion", "skill-cinematic-lighting"],
    scenes: [{ title: "The Final Cut", description: "Two samurai face each other in a decisive duel.", location: "Bamboo forest", timeOfDay: "dusk", mood: "honor, tension, beauty", shots: [
      { shotType: "wide", description: "Rain-soaked bamboo forest", prompt: "Wide shot of a rain-soaked bamboo forest at dusk, mist hanging between the stalks, rain falling in sheets, a path cleared between two figures standing apart", cameraMove: "slow-push", lens: "35mm", lighting: "dusk-rain", durationSec: 5, skills: ["skill-cinematic-lighting"] },
      { shotType: "medium", description: "First samurai in stance", prompt: "Medium shot of the first samurai in a low ready stance, katana angled downward, rain streaming off the blade, eyes calm and focused, perfect stillness", cameraMove: "static", lens: "50mm", lighting: "rain-backlit", durationSec: 4, skills: [] },
      { shotType: "close", description: "Hands tightening on sword grip", prompt: "Close-up of a hand tightening on the wrapped grip of a katana, knuckles whitening, rain running down the blade, the moment before violence", cameraMove: "static", lens: "85mm", lighting: "detail-rain", durationSec: 3, skills: [] },
      { shotType: "wide", description: "The explosive clash", prompt: "Wide slow-motion shot of both samurai exploding into motion simultaneously, blades meeting in a shower of sparks and rain, bamboo stalks sliced around them", cameraMove: "static", lens: "24mm", lighting: "spark-flash", durationSec: 4, skills: ["skill-slow-motion"] },
      { shotType: "close", description: "Blade cutting through rain", prompt: "Close-up slow motion of a katana cutting through raindrops, water splitting around the edge, each drop bisected in incredible detail, lethal beauty", cameraMove: "tracking-blade", lens: "100mm", lighting: "rain-macro", durationSec: 4, skills: ["skill-slow-motion"] },
      { shotType: "medium", description: "One warrior falls", prompt: "Medium shot as one samurai falls to their knees, the other sheathing their sword in a single fluid motion, rain intensifying, honor satisfied", cameraMove: "static", lens: "50mm", lighting: "dusk-somber", durationSec: 4, skills: ["skill-cinematic-lighting"] },
    ]}],
  },
  {
    id: "film-train-heist",
    name: "Train Heist",
    category: "film",
    description: "High-stakes heist aboard a moving luxury train.",
    tags: ["heist", "train", "action", "luxury", "caper"],
    estimatedDuration: 24,
    difficulty: "intermediate",
    recommendedSkills: ["skill-action-camera"],
    scenes: [{ title: "On the Rails", description: "Thieves execute a daring heist on a luxury express.", location: "Luxury train", timeOfDay: "night", mood: "excitement, style", shots: [
      { shotType: "aerial", description: "Luxury train cutting through landscape", prompt: "Aerial shot of a luxury express train cutting through moonlit countryside, carriages glowing warmly from within, speed and elegance on the rails", cameraMove: "tracking-above", lens: "35mm", lighting: "moonlit-train", durationSec: 4, skills: [] },
      { shotType: "medium", description: "Thief dropping onto train roof", prompt: "Medium shot of a figure in black dropping from a bridge onto the speeding train's roof, rolling to absorb the impact, wind whipping at their clothes", cameraMove: "tracking-side", lens: "35mm", lighting: "moonlight-action", durationSec: 4, skills: ["skill-action-camera"] },
      { shotType: "pov", description: "Crawling along train roof", prompt: "POV shot crawling along the rain-slicked train roof at speed, the ground blurring far below, wind deafening, each handhold critical", cameraMove: "handheld-crawl", lens: "16mm", lighting: "wind-streak", durationSec: 4, skills: ["skill-action-camera"] },
      { shotType: "medium", description: "Dropping into luxury car", prompt: "Medium shot of the thief dropping through a hatch into a luxurious private car, landing silently, opulent surroundings contrasting with the cat-burglar intrusion", cameraMove: "static", lens: "35mm", lighting: "warm-luxury", durationSec: 3, skills: [] },
      { shotType: "close", description: "Cracking the safe", prompt: "Close-up of gloved fingers delicately working a combination safe, ear pressed close, listening for the clicks, a bead of sweat despite the cool demeanor", cameraMove: "static", lens: "85mm", lighting: "safe-light", durationSec: 4, skills: [] },
      { shotType: "medium", description: "Guard discovers the theft", prompt: "Medium shot as a guard opens the door and freezes, eyes meeting the thief's across the car, a beat of shocked silence before chaos erupts", cameraMove: "whip-pan", lens: "35mm", lighting: "corridor-harsh", durationSec: 3, skills: [] },
    ]}],
  },
  {
    id: "film-submarine-depth",
    name: "Submarine at Depth",
    category: "film",
    description: "Claustrophobic submarine thriller at crushing depths.",
    tags: ["submarine", "deep-sea", "thriller", "claustrophobia", "pressure"],
    estimatedDuration: 22,
    difficulty: "intermediate",
    recommendedSkills: ["skill-cinematic-lighting"],
    scenes: [{ title: "Crush Depth", description: "A submarine descends beyond safe limits.", location: "Submarine interior", timeOfDay: "timeless", mood: "claustrophobia, dread", shots: [
      { shotType: "establishing", description: "Submarine exterior in the abyss", prompt: "Establishing shot of a submarine descending into the black abyss of the deep ocean, its lights cutting tiny cones through the darkness, incomprehensible depth", cameraMove: "slow-descent", lens: "24mm", lighting: "sub-lights-only", durationSec: 5, skills: [] },
      { shotType: "medium", description: "Crew at battle stations", prompt: "Medium shot of the cramped submarine bridge, crew at their stations, instruments glowing, the captain staring at the depth gauge as it climbs past safe limits", cameraMove: "handheld-tight", lens: "24mm", lighting: "instrument-red", durationSec: 4, skills: ["skill-cinematic-lighting"] },
      { shotType: "close", description: "Hull groaning under pressure", prompt: "Close-up of the submarine hull, rivets straining, a thin stream of water beginning to spray through a seal, the metal groaning under unimaginable pressure", cameraMove: "static", lens: "85mm", lighting: "emergency-dim", durationSec: 4, skills: [] },
      { shotType: "close", description: "Captain's resolve", prompt: "Close-up of the captain's face, sweat beading, jaw set with determination, making the impossible decision to go deeper, the weight of every life aboard", cameraMove: "static", lens: "85mm", lighting: "bridge-glow", durationSec: 4, skills: [] },
      { shotType: "medium", description: "Crew bracing for impact", prompt: "Medium shot of crew members bracing against pipes and walls as the submarine shudders violently, loose objects flying, controlled panic", cameraMove: "shaky", lens: "24mm", lighting: "flickering-emergency", durationSec: 3, skills: [] },
    ]}],
  },
];
