import type { CinematicTemplate } from "../types.js";

export const gamingExtendedTemplates: CinematicTemplate[] = [
  {
    id: "game-cyberpunk-city",
    name: "Cyberpunk City Intro",
    category: "gaming",
    description: "Neon-drenched cyberpunk city introduction with rain and holograms.",
    tags: ["cyberpunk", "neon", "city", "rain", "futuristic"],
    estimatedDuration: 26,
    difficulty: "advanced",
    recommendedSkills: ["skill-sci-fi-vfx", "skill-noir-lighting"],
    scenes: [{ title: "Neon District", description: "Introduction to a sprawling cyberpunk metropolis.", location: "Cyberpunk megacity", timeOfDay: "night", mood: "gritty futurism, neon", shots: [
      { shotType: "aerial", description: "Megacity skyline with holograms", prompt: "Aerial shot descending through a massive cyberpunk skyline, holographic advertisements flickering between skyscrapers, flying vehicles streaming, rain catching neon light", cameraMove: "descending-through", lens: "16mm", lighting: "neon-rain", durationSec: 5, skills: ["skill-sci-fi-vfx"] },
      { shotType: "wide", description: "Neon-soaked street level", prompt: "Wide shot at street level of a crowded cyberpunk district, neon signs in multiple languages, steam rising from grates, augmented humans and androids mixing", cameraMove: "dolly-through", lens: "24mm", lighting: "neon-multicolor", durationSec: 5, skills: ["skill-noir-lighting"] },
      { shotType: "medium", description: "Hooded figure in the crowd", prompt: "Medium shot tracking a hooded figure moving through the crowd, cybernetic eye glowing beneath the hood, augmented arm visible, a player entering this world", cameraMove: "tracking-behind", lens: "50mm", lighting: "neon-contrast", durationSec: 4, skills: [] },
      { shotType: "close", description: "Cybernetic eye scanning", prompt: "Close-up of the character's cybernetic eye scanning the environment, HUD overlay appearing, data streaming, threat assessment, the augmented perspective", cameraMove: "static", lens: "85mm", lighting: "hud-glow", durationSec: 4, skills: ["skill-sci-fi-vfx"] },
      { shotType: "wide", description: "Rain-soaked alley confrontation", prompt: "Wide shot of a tense confrontation in a rain-soaked alley, neon reflecting in puddles, silhouettes facing off, the danger of the cyberpunk underworld", cameraMove: "slow-push", lens: "35mm", lighting: "alley-neon", durationSec: 4, skills: ["skill-noir-lighting"] },
      { shotType: "establishing", description: "City towers and lightning", prompt: "Establishing shot of the full megacity from distance, towers piercing clouds, lightning illuminating the scale, a world of darkness and light, title card moment", cameraMove: "static-wide", lens: "16mm", lighting: "lightning-city", durationSec: 4, skills: ["skill-sci-fi-vfx"] },
    ]}],
  },
  {
    id: "game-sports-arena",
    name: "Sports Arena Opening",
    category: "gaming",
    description: "Electric sports game opening with packed stadium and team entrances.",
    tags: ["sports", "arena", "stadium", "team", "competition"],
    estimatedDuration: 20,
    difficulty: "beginner",
    recommendedSkills: [],
    scenes: [{ title: "Game Day", description: "The electric atmosphere of a major sporting event.", location: "Stadium", timeOfDay: "evening", mood: "excitement, rivalry", shots: [
      { shotType: "aerial", description: "Stadium filling with fans", prompt: "Aerial shot of a massive stadium filling with fans, timelapse of seats turning to team colors, banners unfurling, the anticipation building", cameraMove: "slow-descend", lens: "16mm", lighting: "stadium-sunset", durationSec: 4, skills: [] },
      { shotType: "wide", description: "Tunnel entrance dramatic walk", prompt: "Wide shot from inside the player tunnel, team walking toward the bright rectangle of the pitch entrance, cleats clicking, roar of the crowd growing", cameraMove: "tracking-behind", lens: "24mm", lighting: "tunnel-to-bright", durationSec: 4, skills: [] },
      { shotType: "close", description: "Star player's focused face", prompt: "Close-up of the star player's face, focused eyes, a deep breath, headphones removed, game face activated, ready for battle on the field", cameraMove: "slow-push", lens: "85mm", lighting: "tunnel-edge", durationSec: 3, skills: [] },
      { shotType: "wide", description: "Team emerging onto field", prompt: "Wide shot of the team emerging onto the field, crowd erupting, fireworks launching, confetti falling, the spectacle of professional sport at its peak", cameraMove: "crane-up", lens: "16mm", lighting: "fireworks-stadium", durationSec: 5, skills: [] },
      { shotType: "medium", description: "Coin toss and handshake", prompt: "Medium shot of the team captains meeting for the coin toss, firm handshake, competitive respect, the referee between them, the game about to begin", cameraMove: "slow-orbit", lens: "50mm", lighting: "spotlight-center", durationSec: 4, skills: [] },
    ]}],
  },
  {
    id: "game-stealth-mission",
    name: "Stealth Mission Briefing",
    category: "gaming",
    description: "Tactical stealth game intro with mission briefing and infiltration.",
    tags: ["stealth", "tactical", "mission", "covert", "ops"],
    estimatedDuration: 22,
    difficulty: "intermediate",
    recommendedSkills: ["skill-atmospheric-fog", "skill-horror-grading"],
    scenes: [{ title: "Shadow Protocol", description: "A covert operative receives and executes a stealth mission.", location: "Command center / enemy compound", timeOfDay: "night", mood: "tension, precision", shots: [
      { shotType: "close", description: "Mission briefing on screen", prompt: "Close-up of a tactical screen displaying mission parameters, satellite imagery, target location highlighted, data scrolling, classified markings", cameraMove: "slow-push", lens: "85mm", lighting: "screen-blue", durationSec: 4, skills: [] },
      { shotType: "medium", description: "Operative gearing up", prompt: "Medium shot of an operative gearing up in a dark armory, silenced pistol checked, night vision goggles tested, each piece of kit precision placed", cameraMove: "dolly-past", lens: "50mm", lighting: "armory-dim", durationSec: 4, skills: [] },
      { shotType: "wide", description: "Approaching compound under darkness", prompt: "Wide shot of the operative approaching an enemy compound under cover of darkness, prone movement through tall grass, guard lights sweeping ahead", cameraMove: "static", lens: "35mm", lighting: "moonlight-stealth", durationSec: 4, skills: ["skill-atmospheric-fog"] },
      { shotType: "pov", description: "Night vision view of guards", prompt: "POV shot through night vision goggles, green-tinted view of patrolling guards, thermal signatures visible, calculating the perfect moment to move", cameraMove: "handheld-steady", lens: "35mm", lighting: "night-vision-green", durationSec: 4, skills: ["skill-horror-grading"] },
      { shotType: "medium", description: "Silent takedown", prompt: "Medium shot of the operative executing a silent takedown in shadow, fluid motion, the guard lowered gently to the ground, professional and precise", cameraMove: "static", lens: "50mm", lighting: "shadow-action", durationSec: 3, skills: [] },
      { shotType: "wide", description: "Slipping through a door", prompt: "Wide shot of the operative slipping through a barely-open door into the compound interior, shadow merging with shadow, a ghost in the machine", cameraMove: "static", lens: "35mm", lighting: "interior-minimal", durationSec: 3, skills: ["skill-atmospheric-fog"] },
    ]}],
  },
  {
    id: "game-mecha-battle",
    name: "Mecha Battle Sequence",
    category: "gaming",
    description: "Giant mecha robots clashing in an urban battlefield.",
    tags: ["mecha", "robot", "battle", "urban", "destruction"],
    estimatedDuration: 24,
    difficulty: "advanced",
    recommendedSkills: ["skill-sci-fi-vfx", "skill-vfx-explosions", "skill-epic-scale"],
    scenes: [{ title: "Titans Clash", description: "Massive combat mechs battle in a city.", location: "Urban warzone", timeOfDay: "dusk", mood: "epic, destruction", shots: [
      { shotType: "establishing", description: "Mecha standing over cityscape", prompt: "Establishing shot from ground level looking up at a towering combat mecha standing over the city skyline, 80 meters tall, weapons bristling, lights activating", cameraMove: "tilt-up", lens: "16mm", lighting: "dusk-silhouette", durationSec: 5, skills: ["skill-epic-scale"] },
      { shotType: "wide", description: "Two mechas charging at each other", prompt: "Wide shot of two enormous mechas charging toward each other across a city district, each footstep cratering the street, buildings shaking, unstoppable force", cameraMove: "static-wide", lens: "24mm", lighting: "dusk-destruction", durationSec: 4, skills: ["skill-sci-fi-vfx", "skill-epic-scale"] },
      { shotType: "medium", description: "Cockpit interior during combat", prompt: "Medium shot inside the mecha cockpit, pilot strapped in surrounded by holographic displays, G-forces pulling, alarms blaring, frantic control inputs", cameraMove: "handheld-cockpit", lens: "16mm", lighting: "cockpit-red", durationSec: 4, skills: [] },
      { shotType: "close", description: "Metal fist impact", prompt: "Close-up slow motion of a massive metal fist connecting with another mecha's armor, sparks erupting, metal crumpling, the shockwave shattering nearby windows", cameraMove: "static", lens: "85mm", lighting: "impact-spark", durationSec: 4, skills: ["skill-sci-fi-vfx"] },
      { shotType: "aerial", description: "Battlefield destruction from above", prompt: "Aerial shot of the urban battlefield from above, craters, toppled buildings, the two mechas locked in combat at the center, the scale of destruction immense", cameraMove: "orbit-above", lens: "24mm", lighting: "fires-dusk", durationSec: 4, skills: ["skill-vfx-explosions"] },
      { shotType: "wide", description: "Final beam weapon strike", prompt: "Wide shot of one mecha firing a devastating beam weapon, the energy cutting across the cityscape, the opposing mech raising a shield that barely holds, blinding light", cameraMove: "static", lens: "24mm", lighting: "beam-overexpose", durationSec: 3, skills: ["skill-sci-fi-vfx", "skill-vfx-explosions"] },
    ]}],
  },
  {
    id: "game-puzzle-world",
    name: "Puzzle World Introduction",
    category: "gaming",
    description: "Whimsical puzzle game world with impossible architecture and playful physics.",
    tags: ["puzzle", "whimsical", "impossible", "architecture", "colorful"],
    estimatedDuration: 20,
    difficulty: "beginner",
    recommendedSkills: [],
    scenes: [{ title: "Impossible Spaces", description: "Introduction to a world where physics are a suggestion.", location: "Impossible geometry world", timeOfDay: "eternal-day", mood: "wonder, playfulness", shots: [
      { shotType: "establishing", description: "Impossible architecture overview", prompt: "Establishing shot of a world of impossible architecture, Escher-like stairways going in every direction, waterfalls flowing upward, colorful and inviting", cameraMove: "slow-orbit", lens: "16mm", lighting: "bright-whimsical", durationSec: 5, skills: [] },
      { shotType: "medium", description: "Character walking on ceiling", prompt: "Medium shot of a small character casually walking on the ceiling, gravity a local concept, shifting perspective as they transition between planes seamlessly", cameraMove: "rotating-with", lens: "35mm", lighting: "soft-colorful", durationSec: 4, skills: [] },
      { shotType: "wide", description: "Blocks rearranging themselves", prompt: "Wide shot of massive colored blocks rearranging themselves to form a path, floating into position with satisfying clicks, the world responding to the player", cameraMove: "static", lens: "24mm", lighting: "block-glow", durationSec: 4, skills: [] },
      { shotType: "close", description: "Glowing orb collected", prompt: "Close-up of a glowing puzzle orb being collected, satisfying particle burst on contact, musical chime, the reward for solving the spatial riddle", cameraMove: "static", lens: "85mm", lighting: "orb-radiance", durationSec: 3, skills: [] },
      { shotType: "wide", description: "New impossible vista revealed", prompt: "Wide shot as solving the puzzle reveals a stunning new vista, the world unfolding like origami, revealing layers of wonder beneath wonder, infinite possibility", cameraMove: "crane-reveal", lens: "16mm", lighting: "revelation-bright", durationSec: 4, skills: [] },
    ]}],
  },
];
