import type { CinematicTemplate } from "../types.js";

export const gamingTemplates: CinematicTemplate[] = [
  {
    id: "game-fantasy-intro",
    name: "Fantasy RPG Intro",
    category: "gaming",
    description: "Epic fantasy game opening cinematic with sweeping landscapes and hero reveal.",
    tags: ["fantasy", "rpg", "epic", "hero", "landscape"],
    estimatedDuration: 30,
    difficulty: "advanced",
    recommendedSkills: ["skill-fantasy-vfx", "skill-epic-scale"],
    scenes: [
      {
        title: "The World Awakens",
        description: "Sweeping intro to a fantasy world.",
        location: "Fantasy kingdom",
        timeOfDay: "dawn",
        mood: "epic, wonder",
        shots: [
          { shotType: "aerial", description: "Vast fantasy landscape at dawn", prompt: "Aerial shot sweeping over a vast fantasy landscape at dawn, rolling green hills giving way to towering crystal mountains, a golden castle visible in the distance, volumetric god rays", cameraMove: "sweeping-forward", lens: "16mm", lighting: "dawn-epic", durationSec: 6, skills: ["skill-epic-scale"] },
          { shotType: "wide", description: "Ancient forest with glowing runes", prompt: "Wide shot passing through an ancient forest, massive trees with glowing runes carved into bark, magical particles drifting through shafts of light, mystical atmosphere", cameraMove: "dolly-through", lens: "24mm", lighting: "forest-magical", durationSec: 5, skills: ["skill-fantasy-vfx"] },
          { shotType: "establishing", description: "Grand castle on a cliff", prompt: "Establishing shot of a grand fantasy castle perched on a cliff edge, banners flying, waterfalls cascading from floating islands nearby, epic scale and grandeur", cameraMove: "slow-crane-up", lens: "24mm", lighting: "golden-dawn", durationSec: 5, skills: ["skill-epic-scale"] },
          { shotType: "medium", description: "Hooded figure on a cliff edge", prompt: "Medium shot of a hooded warrior standing on a cliff edge overlooking the kingdom below, cape billowing in the wind, sword strapped to back, destiny awaiting", cameraMove: "slow-orbit", lens: "50mm", lighting: "backlit-dawn", durationSec: 5, skills: [] },
          { shotType: "close", description: "Hood pulled back revealing the hero", prompt: "Close-up as the hero pulls back their hood, revealing a determined face scarred by battle, eyes glowing faintly with magical power, wind whipping hair", cameraMove: "slow-push", lens: "85mm", lighting: "hero-dawn", durationSec: 4, skills: ["skill-fantasy-vfx"] },
          { shotType: "wide", description: "Hero draws glowing sword", prompt: "Wide shot as the hero draws a sword that erupts with magical energy, light blazing across the landscape, silhouetted against the rising sun, title card moment", cameraMove: "dramatic-pullback", lens: "35mm", lighting: "magical-burst", durationSec: 5, skills: ["skill-fantasy-vfx", "skill-epic-scale"] },
        ],
      },
    ],
  },
  {
    id: "game-fps-combat",
    name: "FPS Combat Trailer",
    category: "gaming",
    description: "Intense first-person shooter combat montage with explosions and tactics.",
    tags: ["fps", "combat", "military", "action", "tactical"],
    estimatedDuration: 24,
    difficulty: "advanced",
    recommendedSkills: ["skill-action-camera", "skill-vfx-explosions"],
    scenes: [
      {
        title: "Into the Fray",
        description: "Soldiers engage in intense urban combat.",
        location: "Urban combat zone",
        timeOfDay: "dusk",
        mood: "intensity, chaos",
        shots: [
          { shotType: "pov", description: "FPS running through ruins", prompt: "First-person perspective running through urban ruins at dusk, weapon visible at bottom of frame, debris falling, explosions in the distance, HUD overlay elements", cameraMove: "handheld-sprint", lens: "16mm", lighting: "dusk-fire", durationSec: 4, skills: ["skill-action-camera"] },
          { shotType: "wide", description: "Explosions across city block", prompt: "Wide shot of explosions rippling across a damaged city block, soldiers taking cover behind vehicles, tracer rounds streaking through the air, dust and smoke everywhere", cameraMove: "shaky-wide", lens: "24mm", lighting: "explosion-light", durationSec: 4, skills: ["skill-vfx-explosions"] },
          { shotType: "medium", description: "Soldier breaching a doorway", prompt: "Medium shot of a tactical soldier breaching a doorway, muzzle flash illuminating the dark interior, dynamic entry pose, dust and debris flying", cameraMove: "follow-through", lens: "35mm", lighting: "muzzle-flash", durationSec: 3, skills: ["skill-action-camera"] },
          { shotType: "close", description: "Shell casings ejecting in slow-mo", prompt: "Close-up slow motion of brass shell casings ejecting from a rifle, spinning through the air, catching firelight, the mechanical beauty of weapons", cameraMove: "static", lens: "100mm", lighting: "fire-backlit", durationSec: 3, skills: ["skill-action-camera"] },
          { shotType: "aerial", description: "Helicopter providing support", prompt: "Aerial shot of a military helicopter banking over the combat zone, searchlight sweeping the streets below, rocket pods visible, urban warfare from above", cameraMove: "tracking-follow", lens: "35mm", lighting: "helicopter-spotlight", durationSec: 4, skills: ["skill-vfx-explosions"] },
          { shotType: "medium", description: "Victory stance on rubble", prompt: "Medium shot of a soldier standing atop rubble pile, weapon at ready, smoke clearing behind them, team rallying around, the tide has turned", cameraMove: "slow-crane-up", lens: "35mm", lighting: "dusk-victory", durationSec: 3, skills: [] },
        ],
      },
    ],
  },
  {
    id: "game-racing-intro",
    name: "Racing Game Intro",
    category: "gaming",
    description: "High-octane racing game intro with exotic cars and dramatic tracks.",
    tags: ["racing", "cars", "speed", "competition", "tracks"],
    estimatedDuration: 24,
    difficulty: "intermediate",
    recommendedSkills: ["skill-automotive-lighting", "skill-slow-motion"],
    scenes: [
      {
        title: "Start Your Engines",
        description: "Exotic cars line up for an epic race.",
        location: "Racing circuit",
        timeOfDay: "sunset",
        mood: "adrenaline, competition",
        shots: [
          { shotType: "aerial", description: "Track carved through mountains", prompt: "Aerial shot revealing a spectacular racing circuit carved through mountain terrain, hairpin turns, long straights, the sun setting behind peaks, exotic cars lined up at the start", cameraMove: "sweeping-reveal", lens: "24mm", lighting: "sunset-dramatic", durationSec: 5, skills: [] },
          { shotType: "close", description: "Engine revving, exhaust flames", prompt: "Close-up of an exotic car's exhaust pipes, engine revving hard, blue flames shooting from the tips, heat shimmer visible, raw power", cameraMove: "static", lens: "85mm", lighting: "exhaust-fire", durationSec: 3, skills: ["skill-automotive-lighting"] },
          { shotType: "extreme-close", description: "Traffic light countdown", prompt: "Extreme close-up of a starting traffic light, red lights glowing, the reflection visible in a car's paintwork, tension mounting for green", cameraMove: "static", lens: "100mm", lighting: "traffic-light-red", durationSec: 3, skills: [] },
          { shotType: "wide", description: "Grid launch with tire smoke", prompt: "Wide shot of the entire starting grid launching, tire smoke billowing from every car, jostling for position into turn one, organized chaos at incredible speed", cameraMove: "tracking-side", lens: "24mm", lighting: "sunset-race", durationSec: 4, skills: ["skill-slow-motion"] },
          { shotType: "medium", description: "Car drifting through hairpin", prompt: "Medium shot of a car drifting through a hairpin turn at impossible speed, tires screaming, rear end sliding out, driver's hands working the wheel through the window", cameraMove: "tracking-outside", lens: "35mm", lighting: "golden-hour-track", durationSec: 4, skills: ["skill-automotive-lighting"] },
          { shotType: "pov", description: "Cockpit view at top speed", prompt: "POV from cockpit view at top speed down a long straight, speed blur on the edges, RPM gauge climbing, other cars being overtaken, the thrill of racing", cameraMove: "static-cockpit", lens: "16mm", lighting: "dashboard-glow", durationSec: 5, skills: [] },
        ],
      },
    ],
  },
  {
    id: "game-horror-survival",
    name: "Survival Horror Opening",
    category: "gaming",
    description: "Atmospheric survival horror game intro in an abandoned facility.",
    tags: ["horror", "survival", "abandoned", "dark", "creature"],
    estimatedDuration: 28,
    difficulty: "intermediate",
    recommendedSkills: ["skill-horror-grading", "skill-atmospheric-fog"],
    scenes: [
      {
        title: "The Facility",
        description: "Player discovers an abandoned research facility.",
        location: "Underground research facility",
        timeOfDay: "night",
        mood: "dread, isolation",
        shots: [
          { shotType: "establishing", description: "Facility entrance in storm", prompt: "Establishing shot of an abandoned research facility entrance during a lightning storm, chain-link fences, warning signs, broken security booth, ominous and foreboding", cameraMove: "slow-push", lens: "24mm", lighting: "lightning-flash", durationSec: 5, skills: ["skill-horror-grading"] },
          { shotType: "pov", description: "Flashlight beam in dark corridor", prompt: "POV shot of a flashlight beam cutting through darkness in a long corridor, flickering overhead lights, overturned furniture, claw marks on the walls", cameraMove: "handheld-cautious", lens: "24mm", lighting: "flashlight-only", durationSec: 5, skills: ["skill-atmospheric-fog"] },
          { shotType: "close", description: "Something dripping from ceiling", prompt: "Close-up of an unknown viscous liquid dripping from the ceiling, catching the flashlight beam, pooling on the floor with an organic quality, unsettling", cameraMove: "static", lens: "85mm", lighting: "flashlight-accent", durationSec: 3, skills: ["skill-horror-grading"] },
          { shotType: "wide", description: "Destroyed lab with overturned tanks", prompt: "Wide shot of a destroyed laboratory, containment tanks shattered, liquid spilled everywhere, papers scattered, emergency lights casting red pulses", cameraMove: "slow-pan", lens: "24mm", lighting: "emergency-red", durationSec: 5, skills: [] },
          { shotType: "medium", description: "Shadow moves in the background", prompt: "Medium shot looking down a corridor, everything still and quiet, then a tall misshapen shadow moves across the far wall, barely visible, gone in an instant", cameraMove: "static", lens: "35mm", lighting: "dim-flicker", durationSec: 4, skills: ["skill-horror-grading"] },
          { shotType: "extreme-close", description: "Radio crackling to life", prompt: "Extreme close-up of an old radio crackling to life, static resolving into a distorted voice saying something unintelligible, the dial moving on its own", cameraMove: "slow-push", lens: "100mm", lighting: "radio-glow", durationSec: 3, skills: [] },
          { shotType: "pov", description: "Creature glimpse and run", prompt: "POV shot as a creature is briefly glimpsed at the end of a hallway, monstrous and wrong, before the perspective turns and sprints in the opposite direction, pure terror", cameraMove: "handheld-sprint", lens: "16mm", lighting: "flash-glimpse", durationSec: 3, skills: ["skill-horror-grading", "skill-atmospheric-fog"] },
        ],
      },
    ],
  },
  {
    id: "game-space-opera",
    name: "Space Opera Cinematic",
    category: "gaming",
    description: "Epic space battle cinematic with capital ships and fighter squadrons.",
    tags: ["space", "opera", "battle", "ships", "epic"],
    estimatedDuration: 30,
    difficulty: "advanced",
    recommendedSkills: ["skill-sci-fi-vfx", "skill-epic-scale"],
    scenes: [
      {
        title: "Battle of the Nebula",
        description: "A massive space fleet engages the enemy in a nebula.",
        location: "Nebula battlefield",
        timeOfDay: "space",
        mood: "epic, desperate",
        shots: [
          { shotType: "establishing", description: "Fleet emerging from jump", prompt: "Establishing shot of a massive fleet of warships emerging from hyperspace jump, ripples of energy dissipating, a colorful nebula as backdrop, hundreds of ships taking formation", cameraMove: "sweeping-pull-back", lens: "16mm", lighting: "nebula-glow", durationSec: 6, skills: ["skill-sci-fi-vfx", "skill-epic-scale"] },
          { shotType: "wide", description: "Capital ships exchanging fire", prompt: "Wide shot of enormous capital ships exchanging broadsides, energy beams and projectiles streaking between them, explosions blossoming across hulls, scale of destruction immense", cameraMove: "tracking-through", lens: "24mm", lighting: "weapons-fire", durationSec: 5, skills: ["skill-sci-fi-vfx"] },
          { shotType: "medium", description: "Fighter cockpit during dogfight", prompt: "Medium shot inside a fighter cockpit during an intense dogfight, pilot pulling hard turns, stars and nebula spinning, enemy fighters visible through the canopy", cameraMove: "handheld-cockpit", lens: "16mm", lighting: "cockpit-instruments", durationSec: 4, skills: [] },
          { shotType: "close", description: "Pilot's determined face", prompt: "Close-up of a pilot's face behind the visor, sweat and determination, HUD reflections on the glass, the colors of explosions reflecting in their eyes", cameraMove: "static", lens: "85mm", lighting: "visor-reflections", durationSec: 3, skills: [] },
          { shotType: "aerial", description: "Fighters weaving through debris", prompt: "Dynamic shot following fighters weaving through debris of a destroyed ship, dodging spinning wreckage, firing at enemies, the chaos of space combat", cameraMove: "chase-cam", lens: "24mm", lighting: "explosion-debris", durationSec: 5, skills: ["skill-sci-fi-vfx"] },
          { shotType: "wide", description: "Flagship charges forward", prompt: "Wide shot of the massive flagship charging forward through the battle, smaller ships escorting, all weapons blazing, a rallying moment as it heads for the enemy command ship", cameraMove: "tracking-alongside", lens: "35mm", lighting: "full-battle", durationSec: 4, skills: ["skill-epic-scale", "skill-sci-fi-vfx"] },
          { shotType: "establishing", description: "Explosion lights up the nebula", prompt: "Establishing shot as a capital ship detonates in a massive explosion, the shockwave rippling outward, lighting up the entire nebula in brilliant white before fading", cameraMove: "static-wide", lens: "16mm", lighting: "explosion-supernova", durationSec: 3, skills: ["skill-sci-fi-vfx"] },
        ],
      },
    ],
  },
];
