import type { CinematicTemplate } from "../types.js";

export const miscExtendedTemplates: CinematicTemplate[] = [
  {
    id: "game-open-world-explore",
    name: "Open World Exploration",
    category: "gaming",
    description: "Serene open-world exploration montage with diverse biomes.",
    tags: ["open-world", "exploration", "biomes", "discovery", "peaceful"],
    estimatedDuration: 24,
    difficulty: "beginner",
    recommendedSkills: ["skill-landscape-grading"],
    scenes: [{ title: "Endless Horizons", description: "Exploring a vast open world.", location: "Multiple biomes", timeOfDay: "various", mood: "freedom, discovery", shots: [
      { shotType: "aerial", description: "Vast open world panorama", prompt: "Aerial shot revealing a vast open world, different biomes visible in every direction, snow-capped mountains, lush forests, desert plains, an ocean, infinite possibility", cameraMove: "slow-pan", lens: "16mm", lighting: "golden-hour-panorama", durationSec: 5, skills: ["skill-landscape-grading"] },
      { shotType: "medium", description: "Character on horseback through meadow", prompt: "Medium shot of a character riding a horse through a wildflower meadow, petals kicked up by hooves, mountains in the distance, the joy of exploration", cameraMove: "tracking-side", lens: "50mm", lighting: "meadow-golden", durationSec: 4, skills: [] },
      { shotType: "wide", description: "Discovering a hidden waterfall", prompt: "Wide shot of the explorer pushing through vegetation to discover a hidden waterfall and grotto, the reward for going off the beaten path, natural wonder", cameraMove: "dolly-through", lens: "24mm", lighting: "grotto-filtered", durationSec: 4, skills: ["skill-landscape-grading"] },
      { shotType: "establishing", description: "Campfire under the stars", prompt: "Establishing shot of the character sitting by a campfire under brilliant stars, the open world sprawling below a hilltop camp, the peace of virtual nature", cameraMove: "slow-pull-back", lens: "16mm", lighting: "campfire-stars", durationSec: 5, skills: [] },
      { shotType: "wide", description: "Sunrise over new territory", prompt: "Wide shot of a spectacular sunrise illuminating unexplored territory ahead, the map boundary pushed further, new adventures awaiting, the horizon calls", cameraMove: "static", lens: "35mm", lighting: "sunrise-discovery", durationSec: 4, skills: [] },
    ]}],
  },
  {
    id: "social-asmr-study",
    name: "Study With Me ASMR",
    category: "social",
    description: "Aesthetic study-with-me video with ASMR elements and cozy atmosphere.",
    tags: ["study", "asmr", "aesthetic", "cozy", "productivity"],
    estimatedDuration: 16,
    difficulty: "beginner",
    recommendedSkills: [],
    scenes: [{ title: "Focus Time", description: "A cozy aesthetic study session.", location: "Home desk", timeOfDay: "evening", mood: "focus, cozy, calm", shots: [
      { shotType: "wide", description: "Cozy desk setup with warm lighting", prompt: "Wide shot of a beautifully organized desk setup, warm lamp light, books stacked neatly, a steaming cup of tea, rain visible on the window, the perfect study environment", cameraMove: "slow-push", lens: "24mm", lighting: "warm-lamp", durationSec: 4, skills: [] },
      { shotType: "close", description: "Pen writing on paper", prompt: "Close-up of a pen writing neatly on lined paper, satisfying handwriting, the scratch of pen on paper almost audible, ASMR study aesthetics", cameraMove: "static", lens: "85mm", lighting: "desk-warm", durationSec: 4, skills: [] },
      { shotType: "close", description: "Pages turning in a book", prompt: "Close-up of pages turning in a beautiful hardcover book, the paper texture visible, a highlight being drawn across an important passage, the joy of learning", cameraMove: "static", lens: "85mm", lighting: "reading-warm", durationSec: 3, skills: [] },
      { shotType: "medium", description: "Typing with rain sounds", prompt: "Medium shot of hands typing on a laptop keyboard, rain pattering on the window behind, a candle flickering, productive energy in a cozy atmosphere", cameraMove: "static", lens: "50mm", lighting: "screen-ambient", durationSec: 3, skills: [] },
      { shotType: "close", description: "Tea being sipped", prompt: "Close-up of hands lifting a warm ceramic mug, steam rising, a satisfying sip, then placed back down on a coaster, the small rewards of a study session", cameraMove: "static", lens: "85mm", lighting: "warm-cozy", durationSec: 3, skills: [] },
    ]}],
  },
  {
    id: "comm-hotel-luxury",
    name: "Luxury Hotel Experience",
    category: "commercial",
    description: "Five-star hotel commercial showcasing opulent rooms and amenities.",
    tags: ["hotel", "luxury", "five-star", "hospitality", "resort"],
    estimatedDuration: 22,
    difficulty: "intermediate",
    recommendedSkills: ["skill-product-lighting"],
    scenes: [{ title: "Welcome to Paradise", description: "The ultimate luxury hotel experience.", location: "Luxury resort hotel", timeOfDay: "day", mood: "luxury, serenity, indulgence", shots: [
      { shotType: "aerial", description: "Resort from above", prompt: "Aerial shot of a stunning luxury resort, infinity pool merging with the ocean horizon, palm trees, pristine gardens, architecture designed for paradise", cameraMove: "slow-descend", lens: "24mm", lighting: "tropical-bright", durationSec: 4, skills: [] },
      { shotType: "medium", description: "Suite door opening", prompt: "Medium shot as grand double doors open to reveal a breathtaking suite, ocean-view floor-to-ceiling windows, king bed with pristine white linens, fresh flowers", cameraMove: "dolly-through", lens: "24mm", lighting: "suite-bright", durationSec: 4, skills: ["skill-product-lighting"] },
      { shotType: "close", description: "Champagne being poured poolside", prompt: "Close-up of champagne being poured into a crystal flute by the infinity pool, golden bubbles rising, the turquoise ocean behind, the essence of luxury living", cameraMove: "static", lens: "85mm", lighting: "poolside-golden", durationSec: 3, skills: ["skill-product-lighting"] },
      { shotType: "medium", description: "Spa treatment in progress", prompt: "Medium shot of a guest receiving a spa treatment in a serene open-air pavilion, gentle hands, tropical flowers, the sound of water features, total relaxation", cameraMove: "slow-orbit", lens: "50mm", lighting: "spa-soft", durationSec: 4, skills: [] },
      { shotType: "wide", description: "Candlelit dinner on the beach", prompt: "Wide shot of a private candlelit dinner on the beach at sunset, table set for two, waves lapping nearby, a personal chef serving, unforgettable romance", cameraMove: "slow-push", lens: "35mm", lighting: "sunset-candle", durationSec: 4, skills: [] },
      { shotType: "wide", description: "Guest relaxing at sunset", prompt: "Wide shot of a guest reclining on a daybed watching the sunset, a cocktail in hand, the resort glowing behind, the promise of paradise delivered", cameraMove: "static", lens: "35mm", lighting: "golden-hour-resort", durationSec: 3, skills: [] },
    ]}],
  },
  {
    id: "film-ghost-story",
    name: "Ghost Story",
    category: "film",
    description: "Atmospheric ghost story in a Victorian mansion with subtle scares.",
    tags: ["ghost", "horror", "victorian", "atmospheric", "subtle"],
    estimatedDuration: 24,
    difficulty: "intermediate",
    recommendedSkills: ["skill-horror-grading", "skill-cinematic-lighting"],
    scenes: [{ title: "The Haunting", description: "Strange occurrences in a Victorian mansion.", location: "Victorian mansion", timeOfDay: "night", mood: "unease, dread, melancholy", shots: [
      { shotType: "establishing", description: "Victorian mansion in moonlight", prompt: "Establishing shot of a grand Victorian mansion at night, moonlight casting long shadows, a single window lit on the top floor, fog creeping across the grounds", cameraMove: "slow-push", lens: "24mm", lighting: "moonlight-fog", durationSec: 5, skills: ["skill-horror-grading"] },
      { shotType: "medium", description: "Walking down a dark hallway", prompt: "Medium shot following a character walking down a long dark hallway, their candle the only light, portraits on the walls seeming to watch, floorboards creaking", cameraMove: "tracking-behind", lens: "35mm", lighting: "candle-only", durationSec: 4, skills: ["skill-cinematic-lighting"] },
      { shotType: "close", description: "Candle flame flickering violently", prompt: "Close-up of the candle flame suddenly flickering violently in still air, wax dripping, the character's breath visible in suddenly cold air, something is present", cameraMove: "static", lens: "85mm", lighting: "candle-flicker", durationSec: 3, skills: ["skill-horror-grading"] },
      { shotType: "wide", description: "Ghostly figure in a mirror", prompt: "Wide shot of the character passing a large ornate mirror, and in the reflection a ghostly translucent figure stands behind them, but when they turn nothing is there", cameraMove: "slow-pan", lens: "35mm", lighting: "mirror-ghost", durationSec: 4, skills: ["skill-horror-grading"] },
      { shotType: "close", description: "Piano playing by itself", prompt: "Close-up of piano keys depressing by themselves, playing a melancholy melody, dust rising from each key press, a ghostly performance from beyond", cameraMove: "slow-track", lens: "85mm", lighting: "moonbeam-piano", durationSec: 4, skills: [] },
      { shotType: "medium", description: "Character faces the apparition", prompt: "Medium shot as the character turns to face a full ghostly apparition at the end of the hall, translucent and sad, not malevolent but lost, reaching out", cameraMove: "static", lens: "50mm", lighting: "ghost-glow", durationSec: 4, skills: ["skill-horror-grading", "skill-cinematic-lighting"] },
    ]}],
  },
  {
    id: "env-waterfall-cave",
    name: "Hidden Waterfall Cave",
    category: "environment",
    description: "Discovering a magical waterfall cave with crystal formations.",
    tags: ["waterfall", "cave", "crystal", "hidden", "magical"],
    estimatedDuration: 18,
    difficulty: "intermediate",
    recommendedSkills: ["skill-landscape-grading"],
    scenes: [{ title: "The Hidden Grotto", description: "A secret waterfall cave with crystal formations.", location: "Cave / grotto", timeOfDay: "timeless", mood: "discovery, wonder", shots: [
      { shotType: "wide", description: "Waterfall curtain from inside cave", prompt: "Wide shot from inside a cave looking out through a curtain of waterfall, light refracting through the water, a natural cathedral of stone and water", cameraMove: "slow-push", lens: "16mm", lighting: "waterfall-filtered", durationSec: 5, skills: ["skill-landscape-grading"] },
      { shotType: "close", description: "Crystal formations glowing", prompt: "Close-up of massive crystal formations jutting from the cave walls, each one catching and splitting light into prismatic rainbows, geological treasure", cameraMove: "slow-track", lens: "85mm", lighting: "crystal-refraction", durationSec: 4, skills: [] },
      { shotType: "medium", description: "Underground pool with reflections", prompt: "Medium shot of a perfectly still underground pool reflecting the crystal-covered ceiling above, a mirror world underground, the silence is absolute", cameraMove: "static", lens: "35mm", lighting: "reflected-crystal", durationSec: 4, skills: ["skill-landscape-grading"] },
      { shotType: "wide", description: "Light beam entering the cave", prompt: "Wide shot as a beam of sunlight finds its way through a crack in the ceiling, illuminating the cave interior in a column of golden light, dust motes dancing", cameraMove: "slow-tilt-up", lens: "24mm", lighting: "shaft-golden", durationSec: 5, skills: [] },
    ]}],
  },
  {
    id: "char-musician-practice",
    name: "Musician in the Zone",
    category: "characters",
    description: "A musician lost in practice, the intensity of artistic dedication.",
    tags: ["musician", "practice", "dedication", "instrument", "passion"],
    estimatedDuration: 18,
    difficulty: "beginner",
    recommendedSkills: ["skill-dramatic-lighting"],
    scenes: [{ title: "The Practice Room", description: "A musician in deep, intense practice.", location: "Practice room / studio", timeOfDay: "evening", mood: "intensity, passion, solitude", shots: [
      { shotType: "wide", description: "Sparse practice room", prompt: "Wide shot of a sparse practice room, a single chair, music stand, instrument case open, the monk-like dedication of a musician's private space", cameraMove: "slow-push", lens: "35mm", lighting: "single-overhead", durationSec: 4, skills: ["skill-dramatic-lighting"] },
      { shotType: "close", description: "Fingers moving on instrument", prompt: "Close-up of fingers moving across the instrument with incredible dexterity, years of practice visible in every movement, the physicality of music", cameraMove: "static", lens: "85mm", lighting: "warm-focus", durationSec: 4, skills: [] },
      { shotType: "medium", description: "Eyes closed, feeling the music", prompt: "Medium shot of the musician with eyes closed, completely lost in the music, body swaying with the melody, the external world ceased to exist", cameraMove: "slow-orbit", lens: "50mm", lighting: "dramatic-side", durationSec: 4, skills: [] },
      { shotType: "close", description: "Sheet music with pencil marks", prompt: "Close-up of sheet music covered in pencil marks, corrections, and notes, the manuscript of mastery, each annotation a lesson learned", cameraMove: "slow-pan", lens: "85mm", lighting: "desk-warm", durationSec: 3, skills: [] },
      { shotType: "medium", description: "Final note and silence", prompt: "Medium shot as the musician plays the final note, letting it ring, then sitting in the silence that follows, a small nod of satisfaction, closer to perfection", cameraMove: "static", lens: "50mm", lighting: "warm-fade", durationSec: 3, skills: ["skill-dramatic-lighting"] },
    ]}],
  },
];
