import type { CinematicTemplate } from "../types.js";

export const socialExtendedTemplates: CinematicTemplate[] = [
  {
    id: "social-morning-routine",
    name: "Morning Routine",
    category: "social",
    description: "Aesthetic morning routine GRWM video with satisfying sequences.",
    tags: ["morning", "routine", "aesthetic", "grwm", "lifestyle"],
    estimatedDuration: 16,
    difficulty: "beginner",
    recommendedSkills: [],
    scenes: [{ title: "Rise & Shine", description: "A picture-perfect morning routine.", location: "Bedroom / bathroom", timeOfDay: "morning", mood: "calm, aesthetic", shots: [
      { shotType: "close", description: "Alarm turning off peacefully", prompt: "Close-up of a hand gently turning off an alarm on a minimal phone, soft morning light, clean white bedding, the aesthetic start to a perfect morning", cameraMove: "static", lens: "50mm", lighting: "soft-morning", durationSec: 3, skills: [] },
      { shotType: "medium", description: "Stretching in morning light", prompt: "Medium shot of a person stretching in bed, morning sunlight streaming through sheer curtains, casting beautiful shadow patterns, peaceful awakening", cameraMove: "static", lens: "35mm", lighting: "window-golden", durationSec: 3, skills: [] },
      { shotType: "close", description: "Skincare routine close-ups", prompt: "Close-up montage of a skincare routine, cleanser foam, serum drops, moisturizer application, each step aesthetic and satisfying, self-care ritual", cameraMove: "static", lens: "85mm", lighting: "bathroom-bright", durationSec: 4, skills: [] },
      { shotType: "medium", description: "Outfit selection", prompt: "Medium shot of hands selecting an outfit from a neatly organized closet, holding options against the body in a mirror, the daily creative choice", cameraMove: "static", lens: "50mm", lighting: "closet-bright", durationSec: 3, skills: [] },
      { shotType: "close", description: "Final mirror check", prompt: "Close-up reflection in a round mirror, final hair adjustment, a confident smile, ready to take on the day, the satisfying conclusion of a morning ritual", cameraMove: "static", lens: "50mm", lighting: "mirror-flattering", durationSec: 3, skills: [] },
    ]}],
  },
  {
    id: "social-street-style",
    name: "Street Style Lookbook",
    category: "social",
    description: "Dynamic street fashion lookbook with urban backdrops and style transitions.",
    tags: ["fashion", "street-style", "lookbook", "urban", "transitions"],
    estimatedDuration: 16,
    difficulty: "beginner",
    recommendedSkills: [],
    scenes: [{ title: "Urban Style", description: "Showcasing multiple street fashion looks.", location: "Urban locations", timeOfDay: "golden-hour", mood: "confident, stylish", shots: [
      { shotType: "wide", description: "Walking toward camera on urban street", prompt: "Wide shot of a stylish person walking confidently toward camera on an urban street, outfit on full display, street art and architecture as backdrop", cameraMove: "static", lens: "35mm", lighting: "golden-street", durationSec: 3, skills: [] },
      { shotType: "medium", description: "Spin revealing outfit details", prompt: "Medium shot of the subject doing a casual spin, outfit details visible from all angles, fabric movement, accessories catching light, effortless style", cameraMove: "static", lens: "50mm", lighting: "natural-bright", durationSec: 3, skills: [] },
      { shotType: "close", description: "Accessory details", prompt: "Close-up montage of style details, chunky rings, designer bag clasp, sneaker logo, watch face, the details that make the outfit, fashion close-ups", cameraMove: "quick-cuts", lens: "85mm", lighting: "detail-natural", durationSec: 3, skills: [] },
      { shotType: "medium", description: "Transition to second look", prompt: "Medium shot of a creative transition to the next outfit, walking behind a pillar and emerging in a completely different look, seamless style change", cameraMove: "tracking-side", lens: "50mm", lighting: "natural-warm", durationSec: 4, skills: [] },
      { shotType: "wide", description: "Power pose final look", prompt: "Wide shot of the final look, power pose against a striking urban backdrop, full confidence, the outfit commanding the space, social media ready", cameraMove: "slow-push", lens: "35mm", lighting: "golden-hour", durationSec: 3, skills: [] },
    ]}],
  },
  {
    id: "social-diy-craft",
    name: "DIY Craft Tutorial",
    category: "social",
    description: "Satisfying DIY craft transformation from raw materials to finished piece.",
    tags: ["diy", "craft", "tutorial", "satisfying", "handmade"],
    estimatedDuration: 18,
    difficulty: "beginner",
    recommendedSkills: [],
    scenes: [{ title: "Make It", description: "Creating something beautiful with your hands.", location: "Craft workspace", timeOfDay: "day", mood: "creative, satisfying", shots: [
      { shotType: "aerial", description: "Materials laid out flat-lay", prompt: "Overhead shot of craft materials laid out in a satisfying flat-lay arrangement, tools organized, raw materials in neat piles, the starting canvas", cameraMove: "static-overhead", lens: "35mm", lighting: "bright-even", durationSec: 3, skills: [] },
      { shotType: "close", description: "Hands beginning the craft", prompt: "Close-up of hands beginning the craft, measuring and cutting with precision, the first deliberate steps of creation, ASMR-quality attention to detail", cameraMove: "static", lens: "85mm", lighting: "task-bright", durationSec: 4, skills: [] },
      { shotType: "close", description: "Satisfying process steps", prompt: "Close-up of the most satisfying step in the process, paint being applied evenly, clay being shaped, fabric being pressed, the therapeutic joy of making", cameraMove: "static", lens: "85mm", lighting: "warm-workspace", durationSec: 4, skills: [] },
      { shotType: "medium", description: "Assembly coming together", prompt: "Medium shot of the pieces coming together, the project taking shape, the vision becoming reality, hands working with purpose and skill", cameraMove: "timelapse", lens: "50mm", lighting: "natural-side", durationSec: 4, skills: [] },
      { shotType: "close", description: "Finished piece hero shot", prompt: "Close-up hero shot of the finished handmade piece, spinning slowly on display, beautiful and unique, the pride of handcrafted work, ready to be shown off", cameraMove: "slow-orbit", lens: "85mm", lighting: "product-beauty", durationSec: 3, skills: [] },
    ]}],
  },
  {
    id: "social-room-makeover",
    name: "Room Makeover Reveal",
    category: "social",
    description: "Dramatic room transformation with before/after reveal.",
    tags: ["room", "makeover", "transformation", "interior", "reveal"],
    estimatedDuration: 18,
    difficulty: "beginner",
    recommendedSkills: [],
    scenes: [{ title: "The Glow Up", description: "Transforming a space from boring to beautiful.", location: "Room / apartment", timeOfDay: "day", mood: "transformation, satisfaction", shots: [
      { shotType: "wide", description: "Before state of the room", prompt: "Wide shot of a bland uninspired room, plain walls, mismatched furniture, poor lighting, the before state that everyone can relate to", cameraMove: "slow-pan", lens: "16mm", lighting: "flat-unflattering", durationSec: 3, skills: [] },
      { shotType: "medium", description: "Demolition and clearing", prompt: "Medium shot timelapse of clearing the room, old furniture removed, walls being painted, the satisfying destruction before creation, progress in fast motion", cameraMove: "static", lens: "24mm", lighting: "work-bright", durationSec: 4, skills: [] },
      { shotType: "close", description: "New paint rolling on wall", prompt: "Close-up of fresh paint being rolled onto a wall in a satisfying even coat, the new color transforming the space with each stroke, oddly satisfying", cameraMove: "static", lens: "85mm", lighting: "bright-detail", durationSec: 3, skills: [] },
      { shotType: "medium", description: "Furniture and decor placement", prompt: "Medium shot timelapse of new furniture being arranged, art being hung, plants placed, pillows fluffed, the room taking shape, satisfying transformation", cameraMove: "static", lens: "35mm", lighting: "improving-warm", durationSec: 4, skills: [] },
      { shotType: "wide", description: "Final reveal with reaction", prompt: "Wide slow-motion reveal of the completed room, beautiful lighting, cohesive design, plants and art, a gasp of delight, the dramatic before-and-after payoff", cameraMove: "dolly-reveal", lens: "16mm", lighting: "golden-reveal", durationSec: 4, skills: [] },
    ]}],
  },
  {
    id: "social-couple-date",
    name: "Couple's Date Vlog",
    category: "social",
    description: "Romantic couple's date montage with cinematic feel.",
    tags: ["couple", "date", "romance", "vlog", "aesthetic"],
    estimatedDuration: 16,
    difficulty: "beginner",
    recommendedSkills: [],
    scenes: [{ title: "Date Night", description: "A beautiful couple's date captured cinematically.", location: "City / restaurant", timeOfDay: "evening", mood: "romance, joy", shots: [
      { shotType: "medium", description: "Getting ready together", prompt: "Medium shot of a couple getting ready together, stealing glances in the mirror, helping with accessories, the excited anticipation of a date night", cameraMove: "handheld-natural", lens: "35mm", lighting: "warm-interior", durationSec: 3, skills: [] },
      { shotType: "wide", description: "Walking hand in hand", prompt: "Wide shot of the couple walking hand in hand through a beautifully lit city street at dusk, warm string lights above, stolen smiles between them", cameraMove: "tracking-behind", lens: "35mm", lighting: "string-light-warm", durationSec: 3, skills: [] },
      { shotType: "close", description: "Clinking glasses at dinner", prompt: "Close-up of two glasses clinking at a candlelit dinner table, warm amber tones, blurred fairy lights behind, the toast to love", cameraMove: "static", lens: "85mm", lighting: "candlelight", durationSec: 3, skills: [] },
      { shotType: "medium", description: "Laughing together genuinely", prompt: "Medium shot of the couple laughing genuinely at the dinner table, leaning toward each other, unscripted joy, the comfort of real connection", cameraMove: "static", lens: "50mm", lighting: "restaurant-warm", durationSec: 3, skills: [] },
      { shotType: "wide", description: "Slow dancing under lights", prompt: "Wide shot of the couple slow dancing alone under string lights, forehead to forehead, the world around them blurred away, perfect ending to a perfect date", cameraMove: "slow-orbit", lens: "35mm", lighting: "fairy-light-bokeh", durationSec: 4, skills: [] },
    ]}],
  },
];
