import type { CinematicTemplate } from "../types.js";

export const socialTemplates: CinematicTemplate[] = [
  {
    id: "social-travel-vlog",
    name: "Travel Vlog Intro",
    category: "social",
    description: "Dynamic travel vlog intro with fast cuts and scenic b-roll.",
    tags: ["travel", "vlog", "dynamic", "scenic", "montage"],
    estimatedDuration: 15,
    difficulty: "beginner",
    recommendedSkills: [],
    scenes: [{ title: "Wanderlust", description: "Exciting travel montage opening.", location: "Various locations", timeOfDay: "golden-hour", mood: "excitement, wanderlust", shots: [
      { shotType: "aerial", description: "Drone over tropical beach", prompt: "Aerial drone shot flying over a pristine tropical beach, turquoise water, white sand, palm trees swaying, paradise from above", cameraMove: "forward-fly", lens: "24mm", lighting: "tropical-sun", durationSec: 3, skills: [] },
      { shotType: "medium", description: "Person walking through market", prompt: "Medium shot of a traveler walking through a vibrant Asian street market, colorful lanterns overhead, food stalls steaming, authentic cultural immersion", cameraMove: "tracking-behind", lens: "35mm", lighting: "lantern-warm", durationSec: 3, skills: [] },
      { shotType: "wide", description: "Sunset over ancient temple", prompt: "Wide shot of a stunning sunset behind ancient temple ruins, silhouetted against orange and purple sky, a moment of awe and wonder", cameraMove: "slow-pan", lens: "24mm", lighting: "sunset-dramatic", durationSec: 3, skills: [] },
      { shotType: "close", description: "Hands holding local food", prompt: "Close-up of hands holding a colorful local street food dish, steam rising, vibrant ingredients, the joy of trying something new", cameraMove: "static", lens: "50mm", lighting: "natural-warm", durationSec: 3, skills: [] },
      { shotType: "medium", description: "Jumping into water", prompt: "Medium shot of a person jumping off a cliff into crystal clear water below, arms spread, pure joy and freedom, splash impact", cameraMove: "tracking-side", lens: "35mm", lighting: "bright-tropical", durationSec: 3, skills: [] },
    ]}],
  },
  {
    id: "social-recipe-reel",
    name: "Recipe Reel",
    category: "social",
    description: "Satisfying overhead recipe video with crisp cuts and ASMR appeal.",
    tags: ["recipe", "food", "cooking", "overhead", "satisfying"],
    estimatedDuration: 18,
    difficulty: "beginner",
    recommendedSkills: ["skill-food-styling"],
    scenes: [{ title: "From Scratch", description: "Cooking a beautiful dish from scratch.", location: "Home kitchen", timeOfDay: "day", mood: "satisfying, warm", shots: [
      { shotType: "aerial", description: "Ingredients laid out overhead", prompt: "Overhead shot of fresh ingredients beautifully arranged on a marble countertop, mise en place, vibrant colors against white surface, recipe prep", cameraMove: "static-overhead", lens: "35mm", lighting: "bright-natural", durationSec: 3, skills: ["skill-food-styling"] },
      { shotType: "close", description: "Knife chopping vegetables", prompt: "Close-up of a sharp knife rapidly chopping fresh vegetables on a wooden cutting board, precise cuts, satisfying ASMR quality", cameraMove: "static", lens: "50mm", lighting: "kitchen-bright", durationSec: 3, skills: [] },
      { shotType: "close", description: "Ingredients hitting a hot pan", prompt: "Close-up of diced ingredients hitting a hot pan with oil, instant sizzle, steam rising, caramelization beginning, cooking action", cameraMove: "static", lens: "85mm", lighting: "stove-warm", durationSec: 3, skills: ["skill-food-styling"] },
      { shotType: "extreme-close", description: "Sauce being poured", prompt: "Extreme close-up of a rich sauce being poured over the dish, slow drizzle, coating every surface, glossy and appetizing", cameraMove: "static", lens: "100mm", lighting: "warm-directional", durationSec: 3, skills: [] },
      { shotType: "aerial", description: "Finished plated dish", prompt: "Overhead shot of the beautifully plated finished dish, garnish being placed, a final drizzle of oil, steam rising, ready to serve", cameraMove: "slow-pull-back", lens: "50mm", lighting: "beauty-overhead", durationSec: 3, skills: ["skill-food-styling"] },
      { shotType: "medium", description: "First bite reaction", prompt: "Medium shot of someone taking the first bite, eyes closing with satisfaction, a genuine smile of delight, the reward of cooking", cameraMove: "static", lens: "50mm", lighting: "warm-natural", durationSec: 3, skills: [] },
    ]}],
  },
  {
    id: "social-fitness-transformation",
    name: "Fitness Transformation",
    category: "social",
    description: "Before/after fitness transformation with workout montage.",
    tags: ["fitness", "transformation", "workout", "motivation", "progress"],
    estimatedDuration: 18,
    difficulty: "beginner",
    recommendedSkills: ["skill-slow-motion"],
    scenes: [{ title: "The Grind", description: "Workout montage showing dedication.", location: "Gym", timeOfDay: "morning", mood: "determination, progress", shots: [
      { shotType: "medium", description: "Morning alarm and getting up", prompt: "Medium shot of a person's hand slapping an alarm at 5am, determined swing out of bed, morning light beginning to glow, discipline starting early", cameraMove: "static", lens: "35mm", lighting: "pre-dawn", durationSec: 3, skills: [] },
      { shotType: "wide", description: "Empty gym, starting workout", prompt: "Wide shot of a nearly empty gym at dawn, our subject approaching the squat rack, chalking hands, focused and ready, the grind begins", cameraMove: "slow-push", lens: "24mm", lighting: "gym-fluorescent", durationSec: 3, skills: [] },
      { shotType: "close", description: "Heavy deadlift in slow motion", prompt: "Close-up slow motion of a heavy deadlift, veins visible, face showing maximum effort, weight rising from the ground, iron will", cameraMove: "static", lens: "50mm", lighting: "dramatic-gym", durationSec: 3, skills: ["skill-slow-motion"] },
      { shotType: "medium", description: "Battle ropes with intensity", prompt: "Medium shot of intense battle rope exercise, waves of rope in perfect rhythm, sweat flying, total body engagement, high energy", cameraMove: "slight-orbit", lens: "35mm", lighting: "gym-backlit", durationSec: 3, skills: [] },
      { shotType: "close", description: "Mirror selfie showing progress", prompt: "Close-up of a gym mirror showing visible muscle definition and progress, a proud but humble expression, the result of consistency", cameraMove: "static", lens: "50mm", lighting: "gym-mirror", durationSec: 3, skills: [] },
      { shotType: "medium", description: "Confident walk out of gym", prompt: "Medium shot of the person walking out of the gym into morning sunlight, towel over shoulder, a confident stride, another day conquered", cameraMove: "tracking-behind", lens: "35mm", lighting: "morning-golden", durationSec: 3, skills: [] },
    ]}],
  },
  {
    id: "social-unboxing-tech",
    name: "Tech Unboxing",
    category: "social",
    description: "Satisfying tech product unboxing with ASMR-quality close-ups.",
    tags: ["unboxing", "tech", "asmr", "product", "satisfying"],
    estimatedDuration: 16,
    difficulty: "beginner",
    recommendedSkills: ["skill-product-lighting"],
    scenes: [{ title: "The Unbox", description: "Premium tech product unboxing experience.", location: "Desk setup", timeOfDay: "day", mood: "anticipation, satisfaction", shots: [
      { shotType: "close", description: "Sealed box on desk", prompt: "Close-up of a sealed premium tech product box on a clean desk, perfect branding visible, the anticipation of what's inside, minimalist backdrop", cameraMove: "slow-orbit", lens: "50mm", lighting: "soft-studio", durationSec: 3, skills: ["skill-product-lighting"] },
      { shotType: "extreme-close", description: "Peeling the seal", prompt: "Extreme close-up of fingers slowly peeling the plastic seal on the box, satisfying peel sound implied, crisp packaging coming apart", cameraMove: "static", lens: "100mm", lighting: "detail-light", durationSec: 3, skills: [] },
      { shotType: "close", description: "Lid lifting to reveal product", prompt: "Close-up of the box lid being lifted, revealing the product nestled in premium packaging, a moment of reveal, clean design on display", cameraMove: "slow-push", lens: "50mm", lighting: "reveal-light", durationSec: 3, skills: ["skill-product-lighting"] },
      { shotType: "extreme-close", description: "Product first touch", prompt: "Extreme close-up of hands carefully lifting the product from its packaging for the first time, weight and build quality evident, premium materials", cameraMove: "static", lens: "85mm", lighting: "soft-directional", durationSec: 4, skills: [] },
      { shotType: "medium", description: "Product in use on desk", prompt: "Medium shot of the tech product set up and in use on a clean minimal desk setup, other matching gear visible, the complete setup looking clean", cameraMove: "slow-dolly-back", lens: "35mm", lighting: "desk-ambient", durationSec: 3, skills: [] },
    ]}],
  },
  {
    id: "social-pet-day",
    name: "Day in the Life - Pet",
    category: "social",
    description: "Adorable day-in-the-life video following a pet through their routine.",
    tags: ["pet", "cute", "day-in-life", "dog", "wholesome"],
    estimatedDuration: 18,
    difficulty: "beginner",
    recommendedSkills: [],
    scenes: [{ title: "Paws & Play", description: "A day following an adorable dog.", location: "Home / Park", timeOfDay: "day", mood: "joy, warmth", shots: [
      { shotType: "close", description: "Dog waking up stretching", prompt: "Close-up of an adorable golden retriever waking up, big stretch and yawn, morning light on soft fur, sleepy eyes blinking, the cutest morning routine", cameraMove: "static", lens: "50mm", lighting: "morning-soft", durationSec: 3, skills: [] },
      { shotType: "medium", description: "Excited for breakfast", prompt: "Medium shot of the dog excitedly spinning in circles as food bowl is prepared, tail wagging furiously, pure unbridled joy, the highlight of their morning", cameraMove: "handheld-follow", lens: "35mm", lighting: "kitchen-bright", durationSec: 3, skills: [] },
      { shotType: "wide", description: "Running in the park", prompt: "Wide shot of the dog sprinting freely across a green park, ears flapping, pure speed and happiness, golden hour light, living their best life", cameraMove: "tracking-side", lens: "35mm", lighting: "golden-hour", durationSec: 3, skills: [] },
      { shotType: "close", description: "Playing fetch mid-catch", prompt: "Close-up slow motion of the dog catching a ball mid-air, mouth open, eyes focused, paws leaving the ground, athletic grace mixed with goofiness", cameraMove: "static", lens: "85mm", lighting: "bright-natural", durationSec: 3, skills: [] },
      { shotType: "medium", description: "Cuddling on the couch", prompt: "Medium shot of the dog curled up on the couch next to their owner, head on a lap, content sighing, the bond between human and pet, warmth and love", cameraMove: "static", lens: "50mm", lighting: "warm-interior", durationSec: 3, skills: [] },
      { shotType: "close", description: "Sleeping peacefully", prompt: "Close-up of the dog sleeping peacefully, gentle breathing, a tiny paw twitch during a dream, the perfect end to a perfect day", cameraMove: "static", lens: "85mm", lighting: "warm-lamp", durationSec: 3, skills: [] },
    ]}],
  },
  {
    id: "social-music-performance",
    name: "Music Performance Reel",
    category: "social",
    description: "Dynamic solo music performance with dramatic lighting for social media.",
    tags: ["music", "performance", "artist", "dynamic", "concert"],
    estimatedDuration: 16,
    difficulty: "intermediate",
    recommendedSkills: ["skill-concert-lighting"],
    scenes: [{ title: "Perform", description: "Solo artist performance in dramatic setting.", location: "Concert stage", timeOfDay: "night", mood: "energy, passion", shots: [
      { shotType: "establishing", description: "Dark stage single spotlight", prompt: "Establishing shot of a dark empty stage, a single spotlight snapping on, illuminating a microphone stand, fog rolling across the floor, anticipation building", cameraMove: "slow-push", lens: "24mm", lighting: "single-spotlight", durationSec: 3, skills: ["skill-concert-lighting"] },
      { shotType: "medium", description: "Artist stepping into light", prompt: "Medium shot of an artist stepping into the spotlight, picking up the microphone, the first note about to drop, silhouette becoming a person", cameraMove: "static", lens: "50mm", lighting: "spotlight-dramatic", durationSec: 3, skills: [] },
      { shotType: "close", description: "Singing with emotion", prompt: "Close-up of the artist singing with raw emotion, eyes closed, feeling every word, sweat glistening under the spotlight, authentic performance", cameraMove: "slow-orbit", lens: "85mm", lighting: "concert-warm", durationSec: 4, skills: [] },
      { shotType: "wide", description: "Full stage with lighting effects", prompt: "Wide shot as full stage lighting activates, beams of colored light sweeping, fog catching every ray, the artist commanding the space, visual spectacle", cameraMove: "crane-wide", lens: "16mm", lighting: "full-concert", durationSec: 3, skills: ["skill-concert-lighting"] },
      { shotType: "medium", description: "Final note, lights fade", prompt: "Medium shot as the artist delivers the final powerful note, lights slowly dimming, leaving just the silhouette in a single spot, perfect ending", cameraMove: "slow-pull-back", lens: "50mm", lighting: "fade-to-spot", durationSec: 3, skills: [] },
    ]}],
  },
];
